jbosstm/narayana

- ArjunaCore/arjuna/src/test/resources/h2jbossts-properties.xml
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionImple.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionManager.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionSynchronization.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/IndirectRecoverableConnection.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ProvidedXADataSourceConnection.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/TransactionalDriverXAConnection.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/recovery/JDBC2RecoveryConnection.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/jdbc/TransactionalDriver.java
- ArjunaJTA/jdbc/pom.xml
- ArjunaJTA/jdbc/tests/classes/com/hp/mwtests/ts/jdbc/basic/JDBC2Test.java
- ArjunaJTA/jdbc/tests/classes/com/hp/mwtests/ts/jdbc/recovery/RecoveryTest.java
- ArjunaJTA/jta/src/test/resources/h2jbossts-properties.xml
- pom.xml
This is a prototype for discussion on https://developer.jboss.org/message/909265?et=watches.email.thread#909265
!XTS !QA_JTS_JACORB !BLACKTIE
> Allow the user to provide a reference to an XADataSource

- ArjunaJTS/idl/pom.xml
- ArjunaJTS/jtax/pom.xml
- ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/ibmorb/recoverycoordinators/ORBRunner.java
- ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/jacorb/recoverycoordinators/ORBRunner.java
- ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/javaidl/recoverycoordinators/ORBRunner.java
- ArjunaJTS/jts/pom.xml
- ArjunaJTS/orbportability/classes/com/arjuna/orbportability/ORB.java
- ArjunaJTS/orbportability/pom.xml
- ArjunaJTS/orbportability/tests/classes/com/hp/mwtests/orbportability/shutdown/OAPrePostShutdownTest.java
- pom.xml
!BLACKTIE !PERF !XTS !QA_JTA !QA_JTS_JACORB
The changes are twofold:
- I add a jar to the bootclasspath for testing a particular profile - ie it is isolated and only kicks in during surefire tests.
- secondly, when we run an orb we do some clean up after the run loop completes and that is not (CORBA) spec compliant so I removed that code. This meant there was a risk that destroy on the root poa would not get called so I added that check to the shutdown method on our ORB portability layer wrapper.
> JBTM-1339 JBTM-2423 New profile to use openjdk-orb

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/twophase/XAResourceRecordUnitTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/xa/JTATest.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
- ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/xa/JTSTest.java
an exception to the caller as we don't know the outcome and it may not be
able to be recovered by the recovery manager
!XTS !BLACKTIE !PERF !QA_JTA !QA_JTS_JACORB
> JBTM-2443 Updated so that when a commit_one_phase gets an RMFAIL back we can throw

- ArjunaJTS/integration/pom.xml
- ArjunaJTS/integration/src/test/java/com/arjuna/ats/TransactionListenerRegistryTest.java
- ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/spi/SPIUnitTest.java
- ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/spi/TxListener.java
- ArjunaJTS/pom.xml
- pom.xml
NO_TEST
added no test for the last commit in the PR.
!XTS !BLACKTIE !QA_JTA !QA_JTS_JACORB !PERF !QA_JTS_JDKORB
The change tests the new SPI method TransactionListenerRegistryLocator.getTransactionListenerRegistry().
The pom changes are to ensure we test with the different ORBs - I needed to enable/add the various orb profiles in ArjunaJTS/integration/pom.xml so instead of adding them there I configured it in the parent ArjunaJTS/pom.xml
> JBTM-2460 spi method to get the transaction registry

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
!XTS !BLACKTIE !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB
https://issues.jboss.org/browse/JBTM-2476
Can be verified in SimpleTest in the JTA surefire logs that a stack trace was printed
> JBTM-2476 Updated to print out stack activity of multiple threads when cancelled (e.g. by reaper)

- scripts/release/README.md
- scripts/release/update_jira.py
- scripts/release/utils/jira_helper.py
https://issues.jboss.org/browse/JBTM-2529
NO_TESTS
> [JBTM-2481] Create WildFly component upgrade issue with JIRA update script

- blacktie/wildfly-blacktie/build/server-provisioning.xml
- blacktie/wildfly-blacktie/feature-pack/feature-pack-build.xml
- blacktie/wildfly-blacktie/feature-pack/src/main/resources/configuration/standalone/template.xml
!XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JST_OPENJDKORD !PERF
> JBTM-2540 Can't build BlackTie subsystem since update to WFLY 10 CR4-SNAPSHOT

- ArjunaCore/arjuna/pom.xml
- ArjunaJTA/jta/pom.xml
- ArjunaJTA/jta/tests/byteman-scripts/commitMarkableResourceFailAfterPrepare.btm
- ArjunaJTA/jta/tests/byteman-scripts/fail2pc.btm
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceBase.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceMultiEnlist.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceReturnUnknownOutcomeFrom1PCCommit.java
https://issues.jboss.org/browse/JBTM-2115
https://issues.jboss.org/browse/JBTM-2573
https://issues.jboss.org/browse/JBTM-2574
PROFILE=JACOCO
> Update to fix the ArjunaJTA/jta tests to work under the codeCoverage

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/lastresource/JTATest2.java
https://issues.jboss.org/browse/JBTM-2584
!BLACKTIE !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_IBMORB !PERF
!XTS
> JBTM-2584 commit LRCO and a readonly resource

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/jca/XATerminatorUnitTest.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/TransactionImporterImple.java
- ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/jca/XATerminatorImpleUnitTest.java
!QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB !BLACKTIE !PERF !XTS !MAIN
https://issues.jboss.org/browse/JBTM-2614
My solution is, instead of adding the TransactionImple directly to the list of known imported transactions I add a holder object using putIfAbsent (keyed by Xid). If the put returns null then I know this is the first time we have seen the imported transaction and I construct the transaction and add it to the holder object using a setter method. The getter and setter are protected from each other using the wait/notify idiom.
> Make JCA txn import thread safe

- ArjunaJTA/cdi/tests/resources/arquillian.xml
- ArjunaJTA/jta/src/test/resources/arquillian.xml
- XTS/localjunit/WSTFSC07-interop/src/test/resources/arquillian.xml
- XTS/localjunit/WSTX11-interop/src/test/resources/arquillian.xml
- XTS/localjunit/crash-recovery-tests/src/test/resources/arquillian.xml
- XTS/localjunit/disabled-context-propagation/src/test/resources/arquillian.xml
- XTS/localjunit/unit/src/test/resources/arquillian.xml
- blacktie/blacktie-admin-services/src/test/resources/arquillian.xml
- compensations/src/test/resources/arquillian.xml
- rts/at/bridge/src/test/resources/arquillian.xml
- rts/at/integration/src/test/resources/arquillian.xml
- rts/at/webservice/src/test/resources/arquillian.xml
- txbridge/src/test/resources/arquillian.xml
- txframework/src/test/resources/arquillian.xml
In case that test is run against some slow database on a slow machine when jdbc  object store is used then server could not be started on time of 60 seconds and test start to fail.
This change adds configurable option to increase the arquillian settings of server startup timeout if necessary.
Adding configurable option `<property name="startupTimeoutInSeconds">${server.startup.timeout:60}</property>` for user could use `-Dserver.startup.timeout` with arbitrary value to change the server startup timeout for his use.
!BLACKTIE !PERF !QA_JTA !QA_JTS_JACORB
> [JBTM-2633] Update arquillian.xml in tests to configure startup timeout

- qa/tests/src/org/jboss/jbossts/qa/junit/testgroup/TestGroup_crashrecovery12.java
https://issues.jboss.org/browse/JBTM-2648
!MAIN !BLACKTIE !XTS !PERF
> [JBTM-2648] Add 500ms delay after starting the client in CrashRecovery12_Test03

- narayana-full/pom.xml
https://issues.jboss.org/browse/JBTM-2679
!QA_JTA !QA_JTS_JDKORB !BLACKTIE !PERF !MAIN
> [JBTM-2679] narayna-full to contain bits of jbossxts

- blacktie/blacktie/pom.xml
https://issues.jboss.org/browse/JBTM-2724
!XTS !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !MAIN
> JBTM-2724 Blacktie should not override maven-assembly-plugin version from parent

- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/utils/FileProcessId.java
- ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/BaseTransactionManagerDelegate.java
Based on static code analysis provided by Coverity tool proposing two fixes for locks on strings which is not recommended approach. String literals are centrally interned and could also be locked on by a library, which could lead to potentially have deadlocks or lock collisions with other code.
!QA_JTA !BLACKTIE !XTS !PERF
> [JBTM-2758][JBTM-2759] Locking on interned string

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/basic/ExceptionDeferrerTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/common/FailureXAResource.java
!BLACKTIE !PERF !QA_JTA !QA_JTS_JDKORB
This is a follow-up enhancement to enhance exception with suppressed ones in case that `prepare` of `XAResource` ends in heuristic state.
https://issues.jboss.org/browse/JBTM-2822
https://issues.jboss.org/browse/JBTM-2836
> [JBTM-2836] Adding support for suppressed exceptions in prepare for heuristic

- rts/at/bridge/pom.xml
- txbridge/pom.xml
https://issues.jboss.org/browse/JBTM-2853
https://issues.jboss.org/browse/JBTM-2858
!MAIN !QA_JTA !QA_JTS_JDKORB !BLACKTIE !PERF NO_WIN
> JBTM-2853 JBTM-2858 Disable failing tests TODO revert

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/utils/jtaxI18NLogger.java
This change is part of fix of jca inflow integration with new transaction client. The fix is mainly done in WFLY integration (see https://github.com/jbosstm/jboss-as/pull/69) and change is needed in wfly client as well (see https://github.com/wildfly/wildfly-transaction-client/pull/17#issuecomment-283989487).
The point why the change is needed in Narayana (and what I would kindly ask for review here) is that wfly client checks if underlaying TM (for JBoss it's Narayana) knows about transaction. And the `XATerminator` implementation, as it was written, consider knowledge only of top level transactions but not subordinate. That's why I'm adding check for subordinate ones and those one is then returned to wfly transaction client which then works with it.
!BLACKTIE !PERF …
> [WFLY-8275][JBEAP-8993] jca inflow integration with wildfly transaction client

- rts/at/bridge/pom.xml
- txbridge/pom.xml
This is an alternative fix for https://github.com/jbosstm/narayana/pull/1138. In fact there are fixes only at WFLY side and fix in test here in Narayana.
The point is that transaction client is hooked after transaction is imported by txn bridge in Narayana. The RTS/XTS hok then import (pull) the transaction from Narayana to wildfly transaction client global context.
For the fix would wok it needs the fix of WFLY-8275 which is discussed at https://github.com/jbosstm/narayana/pull/1144. I mean this PR is dependent on PR#1144. That's why one of the commits refers to  	WFLY-8275 but it won't be part of this PR at the end.
requires: https://github.com/jbosstm/jboss-as/pull/70
!BLACKTIE !PERF NO_WIN
https://issues.jboss.org/browse/JBTM-2853
https://issues.jboss.org/browse/JBTM-2858 …
> JBTM-2853 + JBTM-2858: based on XTS handler and RTS filter

- XTS/localjunit/crash-recovery-tests/src/main/java/com/arjuna/qa/extension/BaseServerKillProcessor.java
- XTS/localjunit/crash-recovery-tests/src/test/java/com/arjuna/qa/junit/BaseCrashTest.java
- rts/at/bridge/src/test/java/org/jboss/narayana/rest/bridge/inbound/test/integration/InboundBridgeRecoveryTestCase.java
- rts/at/bridge/src/test/java/org/jboss/narayana/rest/bridge/inbound/test/integration/InboundBridgeRecoveryWithMultipleDeploymentsTestCase.java
- rts/at/integration/src/test/java/org/jboss/narayana/rest/integration/test/integration/RecoveryIntegrationTestCase.java
After investigation and discussion with Andrew I propose this change.
The `Rule` could be loaded from different class loader which could cause errors of the already loaded rule wouldn't been visible - different class loader means different `Rule` for the Byteman. The `boot:` option is not needed if we rule does not transform some classes from `rt.jar` which seems not being the case here.
This change/fix causes Byteman `-agent:` being loaded only by system classloader.
!QA_JTA !QA_JTS_JDKORB !BLACKTIE !PERF
> [JBTM-2793] intermittent test failures on xts happening

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/SubordinateTransaction.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/TransactionImple.java
Implementation of SPI added to ImportedTransaction to get seferred transaction and WFTC/ejb could put them under suppressed part.
https://issues.jboss.org/browse/JBTM-2870
https://bugzilla.redhat.com/show_bug.cgi?id=1435549
!BLACKTIE !PERF
> [JBTM-2870] adding getDeferredThrowables to SubordinateTransaction API

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/SubordinateTransaction.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/TransactionImple.java
- pom.xml
Implementation of SPI added to `ImportedTransaction` to get seferred transaction and WFTC/ejb could put them under suppressed part.
https://issues.jboss.org/browse/JBTM-2870
https://bugzilla.redhat.com/show_bug.cgi?id=1435549
https://issues.jboss.org/browse/WFTC-9
https://issues.jboss.org/browse/JBEAP-9993
https://issues.jboss.org/browse/JBEAP-9996
!MAIN !QA_JTA !BLACKTIE !XTS !PERF NO_WIN
> [JBTM-2870] deferred suppressed throwables

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/SubordinateTransaction.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/TransactionImple.java
- pom.xml
Implementation of SPI added to ImportedTransaction to get seferred transaction and WFTC/ejb could put them under suppressed part.
https://issues.jboss.org/browse/JBTM-2870
https://bugzilla.redhat.com/show_bug.cgi?id=1435549
https://issues.jboss.org/browse/WFTC-9
https://issues.jboss.org/browse/JBEAP-9993
https://issues.jboss.org/browse/JBEAP-9996
!MAIN !QA_JTA !BLACKTIE !XTS !PERF NO_WIN
> [JBTM-2870] deferred suppressed throwables 5.5

- ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionClosingSynchronization.java
- ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxy.java
- ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionProxy.java
- ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionClosingSynchronization.java
- ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionProxy.java
- ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/TransactionHelper.java
- narayana-full/pom.xml
- tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/NarayanaJtaServletContextListener.java
- tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionManagerFactory.java
- tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionSynchronizationRegistryFactory.java
- tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/UserTransactionFactory.java
Splitting the pull request of adding recovery for compensation to two parts (this and https://github.com/jbosstm/narayana/pull/1166). This one rip of the part where javadoc for jms and tomcat modules were added. The original PR#1109 then consist only from changes for compensation.
https://issues.jboss.org/browse/JBTM-2799
https://issues.jboss.org/browse/JBTM-2806
!PERF !QA_JTA !QA_JTS_JDKORB !BLACKTIE !XTS NO_WIN !RTS
Split of the PR: https://github.com/jbosstm/narayana/pull/1109
The other part of split PR: https://github.com/jbosstm/narayana/pull/1166
> [JBTM-2799][JBTM-2806] javadoc for jms and tomcat modules

- scripts/pre-release.sh
I verified that `xargs sed -i 's/.../../g'` works fine on my Linux machine. As the same thing works in branch 5.2 I think it's good for Cygwin too.
I changed the check for MacOS where `xargs sed -i "" 's/.../.../g'` is used. But I don't have any MacOS for I can test it there.
> BUILD SCRIPT ONLY: fix to xargs-sed works on Linux, Cygwin and MacOS too

- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/utils/jtaxI18NLogger.java
- ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/recovery/XARecoveryModuleUnitTest.java
https://issues.jboss.org/browse/JBTM-2892
When method TransactionImple.enlistResource is called with empty params array `IndexOutOfBound` is emitted.
The check for array length does not correspond by one with index hit.
> [JBTM-2892] Not IndexOutOfBound exception when enlist on subordinate txn

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java
Having trace logging enabled causes `NullPointerException` being thrown instead of `SystemException` when `Synchronization` is null passed to `Transaction.enlistSynchronization`
https://issues.jboss.org/browse/JBTM-2897
> [JBTM-2897] on Transaction.registerSynchronization throw System not NullPointer

- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java
- ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/recovery/ImportedTransactionRecoveryUnitTest.java
- ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/recovery/TestXARecoveryHelper.java
If subordinate transaction is managed by Narayana it's safe to permit redefine Xid for each participant.
This issue came from our conversation with Tom and is loosely coupled with solving of https://issues.jboss.org/browse/JBTM-2124 (https://github.com/jbosstm/narayana/pull/1174)
https://issues.jboss.org/browse/JBTM-2893
> [JBTM-2893] xid of jts subordinate transaction to be edited

- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/DirectRecoverableConnection.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/IndirectRecoverableConnection.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ProvidedXADataSourceConnection.java
- ArjunaJTA/jdbc/tests/classes/com/arjuna/ats/internal/jdbc/DirectRecoverableConnectionUnitTest.java
- ArjunaJTA/jdbc/tests/classes/com/arjuna/ats/internal/jdbc/ProvidedXADataSourceConnectionUnitTest.java
!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !PERF
https://issues.jboss.org/browse/JBTM-2902
> Make sure empty credentials are not used to create new connection

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/JCAServerTransactionHeaderReader.java
- ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/NewTypeTest.java
Moving the reader to location where is build to jts jar distributed as part of Narayana release.
https://issues.jboss.org/browse/JBTM-2905
!QA_JTS_JDKORB !BLACKTIE !XTS !PERF !RTS
> [JBTM-2905] moving JCAServerTransactionHeaderReader to a runtime package

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/SubordinateAtomicAction.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
- ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/coordinator/ServerTransaction.java
- ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/interposition/coordinator/ServerTransaction.java
- XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/sagas/arjunacore/subordinate/SubordinateBACoordinator.java
- XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/twophase/arjunacore/subordinate/SubordinateATCoordinator.java
Was introduced here:
https://issues.jboss.org/browse/JBTM-1511
d213dae
The error I am protecting against is:
subordinate transaction called with doPrepare
subordinate transaction has 2 x resources
1st resource returns XARD_ONLY
must avoid the doPrepare call proceeding on and commiting the other resource
> dynamic1PC

- rts/at/tx/src/main/java/org/jboss/jbossts/star/resource/RESTRecord.java
- rts/at/tx/src/main/java/org/jboss/jbossts/star/service/Coordinator.java
- rts/at/tx/src/test/java/org/jboss/jbossts/star/test/BaseTest.java
- rts/at/tx/src/test/java/org/jboss/jbossts/star/test/CoordinatorTest.java
- rts/at/tx/src/test/java/org/jboss/jbossts/star/test/OptionalSpecTest.java
https://issues.jboss.org/browse/JBTM-2921
in case of the two phase unaware participant when optional link header
with link of 'commit-one-phase' is proposed it is expected to be called
during the transaction manager commit phase
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF
> [JBTM-2921] commit-one-phase to be invoked REST-AT

- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/drivers/modifiers/list.java
The list checks what the jdbc connection DatabaseMetaData.getDriverName() gets.
Adding string returned by jdbc driver from DB2 database.
This is per discussion from with Tom and @domhanak.
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !XTS
> [JBTM-2925] adding db2 driver name to jdbc driver list

- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionExtension.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/transactional/TransactionalInterceptorBase.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/StereotypeBean.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/StereotypeTransitiveBean.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/StereotypeWithTransactionalBean.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/TestException.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/TransactionalNeverStereotype.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/TransactionalRequiredStereotype.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/TransitiveStereotypeTest.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/TransitiveToNeverNoTransactional.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/TransitiveToRequiredNoTransactional.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/TransitiveToRequiredTransactionalNever.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/AddStereotypeAnnotationExtension.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/AddTransactionalAnnotationExtension.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/AnnotatedTypeWrapper.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/DummyBean.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/NoAnnotationBean.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/StereotypeChangedByExtensionTest.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/TransactionalChangedByExtensionTest.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/TransactionalLiteral.java
I finally got to a working implementation of the @Transactional @Stereotype issue. I followed the @mkouba steps:
- modify TransactionExtension - add ProcessManagedBean observer and store <Bean, AnnotatedType> map
- modify TransactionalInterceptorBase to use the AnnotatedType stored in TransactionExtension <Bean, AnnotatedType> map (the key - intercepted bean - is available)
- use BeanAttributes.getStereotypes() together with BeanManager.getStereotypeDefinition() to cover the transitive stereotype declarations
- add reflection fallback for intercepted non-contextual instances (e.g. EE components)
Now I would like ask @mkouba and @manovotn to check it. I expect the behavior needs some tuning.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS
> [JBTM-2927/WFLY-2485] transitive handling @Transactional on @Stereotype

- rts/lra/lra-cdi-rest/src/main/java/io/narayana/lra/cdi/LraAnnotationProcessingExtension.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/StartCdiCheckIT.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/AllAnnotationsNoPathBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/CompleteOptionalBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/CorrectBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/CorrectMethodLRABean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/LeaveWithoutPutBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/LraJoinFalseBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/LraJoinFalseMethodLRABean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/MultiForgetBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/NoPostOrGetBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/OnlyOneLraAnnotationBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/OnlyTwoLraAnnotationsBean.java
I find a small issue in the LRA CDI extension checking the structure of the LRA annotations on the class. Changed to accept `join` when used on LRA method level annotation.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS
> Lra cdi extension checking annotations incorrectly counts LRA method annotations

- rts/lra/lra-annotations/src/main/java/io/narayana/lra/annotation/LRA.java
- rts/lra/lra-annotations/src/main/java/io/narayana/lra/annotation/TimeLimit.java
- rts/lra/lra-cdi-rest/src/main/java/io/narayana/lra/cdi/LraAnnotationProcessingExtension.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/StartCdiCheckIT.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/CompleteOptionalBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/CorrectBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/CorrectMethodLRABean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/ForgetWithoutDeleteBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/LeaveWithoutPutBean.java
- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/MultiForgetBean.java
- rts/lra/lra-client/src/main/java/io/narayana/lra/client/LRAClient.java
- rts/lra/lra-client/src/main/java/io/narayana/lra/client/LRAClientAPI.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/RecoveryCoordinator.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java
- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java
- rts/lra/lra-test/src/main/java/io/narayana/lra/participant/model/Activity.java
- rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java
- rts/sra/src/main/java/io/narayana/sra/annotation/SRA.java
- rts/sra/src/main/java/io/narayana/sra/annotation/TimeLimit.java
- rts/sra/src/main/java/io/narayana/sra/client/SRAClient.java
These changes implement the spec updates made in https://github.com/jbosstm/microprofile-sandbox/pull/5 (my plan is to raise the spec PR today).
https://issues.jboss.org/browse/JBTM-2934 LRA nested and parent coordinators should optimise calls when in a single VM
https://issues.jboss.org/browse/JBTM-2935 Make LRA @complete optional
https://issues.jboss.org/browse/JBTM-2937 Do not recommend "X-" prefixed headers
https://issues.jboss.org/browse/JBTM-2938 LRA participant complete/compensate methods should use HTTP PUT
https://issues.jboss.org/browse/JBTM-2940 Ensure recovery handles participants that reply with 202 Accepted
> Jbtm 2940 Spec Updates

- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java
#https://issues.jboss.org/browse/JBTM-2936
> JBTM-2936 JAX-RS response headers from an LRA @Nested method doesn't include the parent LRA id

- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/utils/jtaxI18NLogger.java
- ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/resources/ExtendedResourceRecord.java
- ArjunaJTS/jts/classes/com/arjuna/ats/jts/logging/jtsI18NLogger.java
https://issues.jboss.org/browse/JBTM-2939
Not putting JTS participant during recovery when XAException.XAER_NOTA thrown to heuristic state. Assume such participant as completed.
> [JBEAP-13023][JBTM-2939] jts assume complete

- rts/lra/lra-client/src/main/java/io/narayana/lra/client/LRAClient.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAStatus.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
https://issues.jboss.org/browse/JBTM-2947
The specification used to return participant completion data to the client that closed an LRA. The spec has changed and now it just returns the status of the LRA.
Enables:  jbosstm/quickstart#208
> JBTM-2947 LRA end calls return the status

- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/xa/SynchronizationUnitTest.java
- XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/twophase/arjunacore/subordinate/SubordinateATCoordinator.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/common/AbstractBasicTests.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/outbound/client/TestClient.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/outbound/junit/OutboundBasicTests.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/outbound/service/TestServiceImpl.java
having empty heuristics list which then fails with NPE
This issue came from the observation on customer log.
I would like present the fix of the issue but currently I do not have a reproducer. I would like to check with you about this issue and if you are okI would prepare a testcase.
https://issues.jboss.org/browse/JBTM-2948
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF
> [JBTM-2948] for failed beforeCompletion failure it could happen

- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ClientLRARequestFilter.java
- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ClientLRAResponseFilter.java
Proposing a fix for not getting WARN messages on app startup using LRACLient which normally shows duplicate warns.
https://issues.jboss.org/browse/JBTM-2951
Warning means that registration of the REST provider is done several times - only `@Provider` annotation should be enough.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !mysql !postgres !db2 !oracle
> [JBTM-2951] providers are registered twice - by annotation and by descriptor

- rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/StartCdiCheckIT.java
this is a follow-up for https://issues.jboss.org/browse/JBTM-2932
The issue on the Newcastle cluster is that for some tests cdi container is not stopped. Now it seems there is not enough time to be done so and this is a hot fix to get cdi container more time to be stopped. 
The follow-up solution should be probably to run the whole Swarm as separate process and not as embedded.
FYI NO_TEST should include all of the following
!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !mysql !postgres !db2 !oracle
> [JBTM-2932] lra cdi checker add waiting a while to be sure weld container was stopped

- rts/lra/pom.xml
https://issues.jboss.org/browse/JBTM-2961
NO_TEST
> JBTM-2961 Temporarily disabling the lra cdi checker (fails on mac builds)

- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/recovery/JDBCXARecovery.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/jdbc/logging/jdbcI18NLogger.java
- ArjunaJTA/jdbc/src/test/resources/ds-direct.properties
- ArjunaJTA/jdbc/tests/classes/com/hp/mwtests/ts/jdbc/recovery/DummyXAResource.java
- ArjunaJTA/jdbc/tests/classes/com/hp/mwtests/ts/jdbc/recovery/RecoveryTest.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/CrashRecovery2.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/TestXAResourceRmFail.java
when try to commit fails with RETRY. Then recoverable should be still
saved in object store in way that recovery manager is capable to
deserialize it and use it for committing.
The most of the PR are tests the fix is only the line
https://github.com/jbosstm/narayana/pull/1264/files#diff-9613cb84dbca3e6a76d760b2b4626befL1273
https://issues.jboss.org/browse/JBTM-2973
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF  !RTS !AS_TESTS !mysql !postgres !db2 !oracle
> [JBTM-2973] direct recoverable connection to be recoverable

- rts/lra/lra-test/pom.xml
- rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java
https://issues.jboss.org/browse/JBTM-2986
IBM JDK does not know `jps` command to check running swarm containers to kill it at the end of the tests (post-verify maven step). Changing the maven plugin to start the swarm to know how to stop the started process.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !mysql !postgres !db2 !oracle
> [JBTM-2986] lra test using mvn plugin to kill coordinator instead of shell commands

- scripts/hudson/narayana.sh
Adding maven `-B` paramater (`--batch-mode, Run in non-interactive mode`) to not showing all the printing of progress of artifact downloading aka
```
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/nexus/maven/nexus-maven-plugins/1.6.6/nexus-maven-plugins-1.6.6.pom
1/18 KB   
3/18 KB   
5/18 KB   
7/18 KB   
9/18 KB   
11/18 KB   
13/18 KB   
15/18 KB   
18/18 KB  
```
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !PERF NO_WIN !postgres !db2 !oracle
> BUILD SCRIPT ONLY: using maven batch mode to not showing artifact download process

- ArjunaJTA/jta/classes/com/arjuna/ats/jta/resources/StartXAResource.java
PR https://github.com/jbosstm/narayana/pull/1279 introduced annotation `@Deprecated` to javadoc of `StartXAResource` but it causes errors on builds
```
[ERROR] /home/jenkins/workspace/btny-pulls-narayana/PROFILE/XTS/jdk/jdk8.latest/label/linux/ArjunaJTA/jta/classes/com/arjuna/ats/jta/resources/StartXAResource.java:37: error: unknown tag: Deprecated
[ERROR] * @Deprecated This interface is replaced by org.jboss.tm.FirstResource in the SPI
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64/jre/../bin/javadoc @options
```
and the profile `-Prelease` just fails. Changing for the javadoc correct lower-case version which passes now.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !mysql …
> [JBTM-2991] fixing javadoc @deprecated annotation

- scripts/hudson/narayana.sh
added between wfly artifact and version
the pom.xml is now in format
```
<groupId>org.wildfly</groupId>
<artifactId>wildfly-parent</artifactId>
<version>12.0.0.Alpha1-SNAPSHOT</version>
```
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !mysql !postgres !db2 !oracle
> [SCRIPTS ONLY] fixing issue of xml comments 

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
When doing rollback from Recovery Manager treat XAER_NOTA return code as debug instead of warning
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !mysql !postgres !db2 !oracle
> JBTM-2987 XAER_NOTA return code handling

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/utils/ThreadUtil.java
Add ThreadLocal cache to allow locking on WeakHashMap to be avoided for most use cases.
> JBTM-2990 performance fix for ThreadUtil lock contention.

- rts/lra/lra-annotation-checker/src/main/java/io/narayana/lra/checker/CheckerUtil.java
- rts/lra/lra-annotation-checker/src/test/java/io/narayana/lra/checker/LraCdiCheckIT.java
- rts/lra/lra-test/pom.xml
https://issues.jboss.org/browse/JBTM-2969
I badly missed the fact of the path separator. Fixing this ommision.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF  !AS_TESTS !mysql !postgres !db2 !oracle
NO_TEST
> [JBTM-2969] lra annotation checker - windows fix

- scripts/hudson/narayana.sh
The AS test could fail as there is not changed Narayana to the current one during XTS and RTS tests execusions.
From
```bash
./build.sh -f ./testsuite/integration/xts/pom.xml -B -Pxts.integration.tests.profile "$@" test
```
to
```bash
./build.sh -f ./testsuite/integration/xts/pom.xml -B -Pxts.integration.tests.profile -Dversion.org.jboss.narayana=${NARAYANA_CURRENT_VERSION} "$@" test
```
!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !mysql !postgres !db2 !oracle
> [BUILD SCRIPT ONLY] jboss as tests invocation to consider narayana version

- scripts/hudson/narayana.sh
Removing the `NO_TEST` github comment handling from narayana.sh in substitution with `NoCI` label. When the `NoCI` label is used then the `-poller` narayana ci script does not start the test build.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle !MAIN
/cc @zhfeng @mmusgrov
> [SCRIPTS ONLY] changing comment NO_TEST for github label NoCI

- tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/AbstractCase.java
- tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/app/TestExecutor.java
When tomcat is run and a non-existent test type is specified (e.g. `psql` instead of `pgsql`, aka. `-Dtest.db.type=psql`) then  NPE is thrown at the end of the test instead of being reported only(!) the test fails because of non-existent test type.
!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !mysql !postgres !db2 !oracle
> [JWS-883] not throwing NPE when wrong db test type is provided

- scripts/hudson/narayana.sh
It's not needed to build the WFLY as release as Narayana uses it only for tests.
This is test to get not having CI failures with error message
```
[ERROR] Failed to execute goal org.jboss.galleon:galleon-maven-plugins:1.0.0.CR3:provision (server-provisioning) on project wildfly-build: Failed to provision the state: Failed to locate /tmp/ecb7b9e6-6be5-4af7-aba6-b8fba83b78b5/staged/docs/licenses/servlet-feature-pack-licenses.xml -> [Help 1]
```
!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS  !TOMCAT !mysql !postgres !db2 !oracle
> Removing release profile from the jboss as build

- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-test/pom.xml
- rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java
- rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/TimedParticipant.java
- rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java
https://issues.jboss.org/browse/JBTM-2979
Note that the first commit in this PR (54a4551) is a merge of the commit in PR #1319 since this fix relies on JBTM-2977. The specific changes that relate to this fix are in the last commit (eaf42e4)
> Jbtm 2979 Timeout leaves LRA active and able to complete

- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/FormatConstants.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/utils/XAUtils.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/xa/XATxConverter.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java
- ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/recovery/ImportedTransactionRecoveryUnitTest.java
- ArjunaJTS/jts/classes/com/arjuna/ats/jts/extensions/Arjuna.java
- rts/at/bridge/src/main/java/org/jboss/narayana/rest/bridge/inbound/InboundBridge.java
- txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/BridgeDurableParticipant.java
https://issues.jboss.org/browse/JBTM-3025
This is a proposal for the fix for regression coming from https://issues.jboss.org/browse/JBTM-2893. The import JTS transaction changes node name of the Xid created for XAResource to the current node name and not leaving that set as it was in the inflow transaction.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle
> [JBTM-3025] Xid created from imported transaction should not change node name

- rts/lra/lra-test/pom.xml
I found there is started LRA coordinator in pre integration test phase even the tests are skipped (`-DskipTests`). This is an enhancement with maven hacking for not starting the test coordinator which slows down narayana build for 10-20 seconds when tests are skipped.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle
> [TEST ONLY] not starting lra-test coordinator when tests are skipped

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/UidWrapper.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/SubordinateJTAXAResourceOrphanFilter.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/TransactionImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/xa/XidImple.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/coordinator/ServerTransaction.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/utils/jtaxI18NLogger.java
- ArjunaJTS/jtax/pom.xml
- ArjunaJTS/jtax/src/test/resources/logging.properties
https://issues.jboss.org/browse/JBTM-2880
Some changes to reduce number of places where sysout println is used instead of logger. This is "a long running" task as the code base still contains places where logger is not prioritized.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle
> [JBTM-2880] replacing some of the exception print stacktrace calls for logger

- rts/lra/lra-annotation-checker/pom.xml
- rts/lra/lra-client/pom.xml
- rts/lra/lra-coordinator/pom.xml
- rts/lra/lra-filters/pom.xml
- rts/lra/lra-proxy/api/pom.xml
- rts/lra/lra-proxy/test/pom.xml
- rts/lra/pom.xml
- scripts/hudson/narayana.sh
as their existence in `pom.xml` pushes depreated code to the swarm factions depending on the project (e.g. on projects depending on lra-filters)
https://issues.jboss.org/browse/JBTM-3027
The change in quickstart will be realized when this PR is merged and could be observed at:
https://github.com/jbosstm/quickstart/pull/227
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle
> [JBTM-3027] removing dependency to lra annotations

- rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java
- rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java
https://issues.jboss.org/browse/JBTM-3028
@ochaloup The tests that fail are ones that expect a single recovery pass to be sufficient to finish the LRA. Due to artificial network delays recovery is no longer guaranteed in a single pass. I added some retry logic to do multiple recovery passes if required. But if the network issue continues then recovery may never complete and I argue (in the linked JIRA) that such a test setup is invalid.
I think the test only fix should be sufficient for the purposes of our CI.
> JBTM-3028 Retry recovery on slow networks

- rts/lra/lra-client/src/main/java/io/narayana/lra/client/Current.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ClientLRARequestFilter.java
- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ClientLRAResponseFilter.java
- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- rts/lra/lra-test/pom.xml
- rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java
- rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java
https://issues.jboss.org/browse/JBTM-2982
> JBTM-2982 Drive LRA participants from a separate thread

- XTS/WS-C/dev/src/com/arjuna/webservices/logging/wscI18NLogger.java
- XTS/WS-C/dev/src/com/arjuna/wsc/InvalidProtocolException.java
- XTS/WS-C/dev/src/com/arjuna/wsc/InvalidStateException.java
- XTS/WS-C/dev/src/com/arjuna/wsc/NoActivityException.java
- XTS/WS-C/dev/src/com/arjuna/wsc11/messaging/ActivationCoordinatorProcessorImpl.java
- XTS/WS-C/dev/src/com/arjuna/wsc11/messaging/RegistrationCoordinatorProcessorImpl.java
- XTS/WSAS/classes/com/arjuna/mwlabs/wsas/UserActivityImple.java
- XTS/WSTX/classes/com/arjuna/mwlabs/wst11/at/RegistrarImple.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wsc/tests/arq/RegistrationServiceTest.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/arq/TestCompletionCoordinatorProcessor.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/arq/TestCoordinatorCompletionCoordinatorProcessor.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/arq/TestCoordinatorCompletionParticipantProcessor.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/arq/TestCoordinatorProcessor.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/arq/TestParticipantCompletionCoordinatorProcessor.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/arq/TestParticipantCompletionParticipantProcessor.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/arq/TestParticipantProcessor.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/common/TestFaultedExceptionBusinessAgreementWithParticipantCompletionParticipant.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/common/TestNoExceptionBusinessAgreementWithCoordinatorCompletionParticipant.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/common/TestNoExceptionBusinessAgreementWithParticipantCompletionParticipant.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wst/tests/common/TestSystemExceptionBusinessAgreementWithCoordinatorCompletionParticipant.java
https://issues.jboss.org/browse/JBTM-3031
this is follow up to the JBTM-2928 as discussed at EAP7-911 where messages and tracability of errors during registration should be enhanced
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !TOMCAT !mysql !postgres !db2 !oracle
> [JBTM-3031] enhancing error messages for the XTS registration

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/CommitMarkableResourceRecordRecoveryModule.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
https://issues.jboss.org/browse/JBTM-3034
This reverts the change from JBTM-2734 at https://github.com/jbosstm/narayana/pull/1059/files#diff-8487f43e773b3321c5396187b559bfffL261 as it caused the regression for CMR processing. By reverting of the change there is, hopefully, no functionality harm - tested with XATerminator usecases, will be seen on this PR when test finishes too.
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !mysql !postgres !db2 !oracle
> [JBTM-3034] removing xid from processing when to be committed by AtomicActionRecoveryModule

- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/AbstractBean.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/JNDIBean.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionContext.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionExtension.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionScopeCleanup.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/transactional/TransactionalInterceptorBase.java
This pull request makes the `TransactionContext` and `TransactionalInterceptorBase` classes more dependency-injection friendly so that, for example, JNDI can be an optional rather than a required dependency.  My intention is that these changes are backwards compatible.
A full discussion of the issues involved can be found here: https://developer.jboss.org/thread/278367
The related issue can be found here: https://issues.jboss.org/browse/JBTM-3044
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS  !TOMCAT !mysql !postgres !db2 !oracle
> Make TransactionContext and TransactionalInterceptorBase DI-friendly

- rts/at/tx/pom.xml
https://issues.jboss.org/browse/JBTM-3046
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !mysql !postgres !db2 !oracle
The bug relates to a hang when an HTTP request is made to the REST-AT coordinator running in undertow. The test currently use an ancient version of undertow so this PR upgrades undertow to a more recent version.
> JBTM-3046 Upgrade undertow version for the tests

- ArjunaJTA/jta/src/test/resources/standalone-cmr.xml
https://issues.jboss.org/browse/JBTM-3050
Removing the IIOP subsystem from configuration of the `standalone-cmr.xml` as it not needed as the tests are part of the `ArjuntaJTA/jta` and CMR is not supported for the JTS.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle
> [JBTM-3050] fixing the cmr standalone.xml configuration as it does not need iiop

- pom.xml
- rts/lra/lra-tck/runner/pom.xml
- rts/lra/lra-tck/tck/pom.xml
- rts/lra/lra-tck/tck/src/main/java/org/eclipse/microprofile/lra/tck/RunTck.java
- rts/lra/pom.xml
https://issues.jboss.org/browse/JBTM-2942
Fixes JDK 9 build/test failures on JDK 9
NB there was one test that consistently failed. I opened https://issues.jboss.org/browse/JBTM-3051 to fix that.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle !XTS
> JBTM-2942 LRA fixes for JDK 9

- rts/lra/lra-client/src/main/java/io/narayana/lra/client/Current.java
- rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/lra-coordinator/pom.xml
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ClientLRAResponseFilter.java
- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
https://issues.jboss.org/browse/JBTM-3066
Enables: jbosstm/quickstart#235
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !mysql !postgres !db2 !oracle !JACOCO !QA_JTA NO_WIN !AS_TESTS 
The issue here is that I maintain LRA contexts in a java.util.Stack (see io.narayana.lra.client.Current) so if there is already a context present when a new LRA is started then the new one gets pushed onto the stack. The intention is that as the child finishes it gets popped so the previous one becomes the current one.
But when the JAX-RS filters need to propagate the contexts via JAX-RS headers the code is only looking at the first header instance to obtain the active context, for example:
> response.getHeaders().getFirst(LRA_HTTP_HEADER);
There were other similar errors …
> JBTM-3066 nested LRAs via the API

- STM/pom.xml
- pom.xml
- rts/at/integration/pom.xml
There is no class of depdencency `commons-logging:commons-logging` used in the project. It's not needed to be mentioned in `pom.xml`.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle
> Refactoring: removing unused commons-logging dependency declaration

- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/drivers/modifiers/list.java
https://issues.jboss.org/browse/JBTM-3078
The jdbc transactional driver checks what the jdbc connection `DatabaseMetaData.getDriverName()` gets.
Adding string returned by jdbc driver from MSSQL database.
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !XTS !JACOCO
> [JBTM-3078] Enriching jdbc transactional driver for MSSQL 

- STM/src/test/java/org/jboss/stm/TaxonomyTest.java
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle !JACOCO
https://issues.jboss.org/browse/JBTM-3074
Fixes test hang (caused by a thread waiting for a notification from another thread) on windows which has been seen twice. NB If there is still a bug in the test then the changes also do a notify() at the end of the test so at least it should not hang.
> JBTM-3074 Fail gracefully if a test fails

- narayana-release-process.sh
- scripts/pre-release.sh
and the lra-coordinator could be pushed to dockerhub
on top of it - making changes in Dockerfile is I think not intended. The changes adds SNAPSHOT which does not work well and Dockerfile can be created in different manner than go with the SNAPSHOT - as it's the current case of the jboss-dockerfiles repository.
The release script is already written in way to release correct version of the docker image to the dockerhub.
> RELEASE SCRIPT ONLY: correct place for jboss-dockerfiles repo

- rts/lra/pom.xml
https://issues.jboss.org/browse/JBTM-3091
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !XTS
This PR corrects a dependency on the wrong LRA MP TCK snapshot build
> JBTM-3091 Use the correct MP LRA TCK snapshot

- rts/lra/pom.xml
https://issues.jboss.org/browse/JBTM-3093
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !XTS !AS_TESTS !TOMCAT
PR 1401 reverted this change by mistake. This new PR adds it back in again.
> JBTM-3093 Disable the site plugin for LRA

- scripts/hudson/narayana-rebase.sh
… against a special branch. Especially when there is no such branch as `jdk-11` :)
MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO JDK11
> [SCRIPT ONLY] after fixing JBTM-3067 there is no need to rebase jdk11

- rts/lra/lra-test/tck/pom.xml
https://issues.jboss.org/browse/JBTM-3115
By default skip LRA TCK testing
Note that this change does not disable running a coordinator which is a more invasive change and I would prefer that @ochaloup does that.
> JBTM-3115 Do not run LRA TCK by default

- rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAInfo.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAStatusHolder.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/lra-test/tck/pom.xml
- rts/lra/lra-test/tck/src/test/java/io/narayana/lra/tck/LRATckInfo.java
- rts/lra/pom.xml
https://issues.jboss.org/browse/JBTM-3109
Based on the changes in LRA TCK the LRA status methods were renamed to
close and cancel.
https://github.com/eclipse/microprofile-lra/issues/94
https://github.com/eclipse/microprofile-lra/pull/98
> [JBTM-3109][lra#94] renaming LRA status complete/compensate to close/cancel

- scripts/pre-release.sh
https://issues.jboss.org/browse/JBTM-3120
Moving the repository of dockerfiles from https://github.com/jboss-dockerfiles/narayana to https://github.com/jboss-dockerfiles/narayana
> [JBTM-3120] using jboss-dockerfiles/narayana repository for dockerfiles when releasing

- XTS/WSTX/classes/com/arjuna/mw/wst11/UserTransaction.java
- XTS/WSTX/classes/com/arjuna/mwlabs/wst11/at/remote/UserSubordinateTransactionImple.java
- XTS/WSTX/classes/com/arjuna/mwlabs/wst11/at/remote/UserTransactionImple.java
- XTS/WSTX/classes/com/arjuna/mwlabs/wst11/at/remote/UserTransactionStandaloneImple.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wstx/tests/arq/WarDeployment.java
- rts/at/bridge/src/main/java/org/jboss/narayana/rest/bridge/inbound/InboundBridge.java
- rts/at/bridge/src/test/java/org/jboss/narayana/rest/bridge/inbound/test/common/AdvancedInboundBridgeResource.java
- rts/at/bridge/src/test/java/org/jboss/narayana/rest/bridge/inbound/test/integration/AbstractTestCase.java
- rts/at/bridge/src/test/java/org/jboss/narayana/rest/bridge/inbound/test/integration/InboundBridgeTestCase.java
- rts/at/bridge/src/test/java/org/jboss/narayana/rest/bridge/inbound/test/integration/InboundBridgeWithMultipleDeploymentsTestCase.java
- txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/InboundBridge.java
- txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/InboundBridgeManager.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/service/TestServiceImpl.java
The integration with WFLY with change of the WFTC-54 causes
that timeout set to 0 means the timeout elapsed and participant
is not permitted to be enlisted to transaction.
Let's use default timeout instead.
https://issues.jboss.org/browse/WFLY-11849
requires: https://github.com/jbosstm/jboss-as/pull/81
(adding the integration tests for txbridge to wfly)
Documentation is over here: https://github.com/jbosstm/documentation/pull/49
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF !TOMCAT !JACOCO !LRA
> [WFLY-11849] txbridge import transaction to use default timeout not null

- narayana-release-process.sh
- scripts/pre-release.sh
...and dockerfiles can be without update
The `narayana-full` is under community profile the release script needs to be updated.
JBoss docker files could not be updated and commit is not necessary in such case. We don't want the script go to `fatal` in empty commit.
> RELEASE SCRIPTS ONLY: narayana-full is under community profile

- STM/src/test/java/org/jboss/stm/TaxonomyNestedTest.java
- STM/src/test/java/org/jboss/stm/TaxonomyTest.java
https://issues.jboss.org/browse/JBTM-3105
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB BLACKTIE !XTS !PERF !RTS !AS_TESTS !TOMCAT !JACOCO !LRA !DB_TESTS !JDK11 !WIN !BLACKTIE
This update fixes the taxonomy test for verifying that STM implements the closed nested transaction model. It also improves/hardens those tests.
> JBTM-3105 STM with nested transactions and fix for taxonomy test failure

- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- rts/lra/lra-test/tck/pom.xml
- rts/lra/pom.xml
1. This PR updates LRA to use JAX-RS 2.1 (which adds reactive features to JAX-RS and is a version supported by Thorntail)
2. The PR also includes the commit to accommodate MP-LRA issue 117 which replaced the @NestedLRA annotation with an LRA.Type.Nested element (and exposes the parent context in a JAX-RS header when a nested LRA is active)
> Jbtm 3087 mp lra issue149

- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/LRAConstants.java
- rts/lra/lra-test/tck/pom.xml
https://issues.jboss.org/browse/JBTM-3144
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !R
Some MP-LRA TCK tests need to wait for a recovery cycle to validate eventual consistency and one of the tests periodically fails on CI hardware due to timing issues (but I have not seen it on my laptop).
This PR adds a synchronous recovery scan and also has the benefit of significantly speeding up the TCK run (since it avoids multiple long waits for the next scheduled scan).
> JBTM-3144 Intermittent LRA TCK test failures

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/AbstractRecord.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
- XTS/WS-C/dev/src/com/arjuna/services/framework/task/TaskManager.java
- XTS/WS-T/dev/src/com/arjuna/webservices/logging/wstI18NLogger.java
- XTS/WS-T/dev/src/com/arjuna/wst11/messaging/CompletionCoordinatorProcessorImpl.java
- XTS/WS-T/dev/src/org/jboss/jbossts/xts/recovery/participant/at/ATParticipantRecoveryRecord.java
- XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/twophase/arjunacore/ParticipantRecord.java
- XTS/WSTX/classes/com/arjuna/mwlabs/wst/at/participants/DurableTwoPhaseCommitParticipant.java
- XTS/WSTX/classes/com/arjuna/mwlabs/wst11/at/participants/CompletionCoordinatorImple.java
- XTS/localjunit/WSTX11-interop/src/main/java/com/jboss/transaction/txinterop/interop/ATTestCase.java
- XTS/localjunit/WSTX11-interop/src/main/java/com/jboss/transaction/txinterop/webservices/atinterop/client/SyncParticipantClient.java
- XTS/localjunit/crash-recovery-tests/src/test/java/com/arjuna/qa/junit/TestATCrashDuringSingleParticipantCommit.java
- XTS/localjunit/xtstest/src/org/jboss/jbossts/xts/servicetests/test/at/SingleParticipantPrepareAndCommitTest.java
- XTS/recovery/src/org/jboss/jbossts/xts/recovery/participant/at/XTSATRecoveryManagerImple.java
- XTS/recovery/src/org/jboss/jbossts/xts/recovery/participant/at/XTSATSubordinateRecoveryModule.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/junit/InboundCrashRecoveryTests.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/utility/TestXAResource.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/utility/TestXAResourceRecoveryHelper.java
https://issues.jboss.org/browse/JBTM-3138
https://issues.jboss.org/browse/JBTM-3147
A follow-up to https://issues.jboss.org/browse/JBTM-3079 where active xids were considered to not be processed by recovery manager.
Here adding a testcase which crashes after prepare phase is finished and I would expect the commit should be processed. Discussion on this topic is at the forum https://developer.jboss.org/thread/279243
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA !PERF
!MAIN XTS
> [JBTM-3138] XTS txbridge does not run commit during recovery when 1PC is used

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/SubordinateAtomicAction.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/TransactionImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/subordinate/SubordinateTestCase.java
- ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/subordinate/SubordinateTestCase.java
https://issues.jboss.org/browse/JBTM-3148
1PC for subordinate XAResource to return heuristics if failure on commit happens.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !RTS  !TOMCAT !JACOCO !LRA !PERF !XTS !AS_TESTS
MAIN
> [JBTM-3148] returning correct error code on one phase commit failure

- rts/lra/pom.xml
This is an interim upgrade of our LRA dependencies while we wait for pr 1450 (which is in progress). We need it as soon as possible since all of our builds are currently failing.
Note that we need an immediate fix because MP-LRA builds are expunged after 30 days
> JBTM-3087 Upgrade the version of the MP-LRA dependency

- ArjunaJTS/narayana-jts-ibmorb/pom.xml
- common/classes/com/arjuna/common/util/ConfigurationInfo.java
- common/classes/com/arjuna/common/util/propertyservice/PropertiesFactory.java
- common/pom.xml
- pom.xml
https://issues.jboss.org/browse/JBTM-3146
This is a second attempt at fixing JBTM-3146.
Note that the latest fix sets the JDK compiler for JDK8 compatibility during the build (which is the default since our parent is jboss-parent). This change is valid since JBoss projects are not currently using JDK 11 features yet.
> JBTM-3146 Make the parsing of XML and Java archives more flexible

- rts/lra/lra-coordinator/pom.xml
- rts/lra/lra-proxy/test/pom.xml
- rts/lra/lra-test/tck/pom.xml
- rts/lra/lra-test/tck/src/test/java/io/narayana/lra/tck/arquillian/ConfigAuxiliaryArchiveAppender.java
- rts/lra/lra-test/tck/src/test/resources/arquillian-thorntail.xml
- rts/lra/pom.xml
- rts/pom.xml
- rts/sra/pom.xml
https://issues.jboss.org/browse/JBTM-3145
As well as attempting to fix the default resteasy providers error, this PR also upgrades our mp-lra dependency. I had to disable some tests that I am still debugging but I would like to get this PR merged since the current mp-lra snapshot will be removed from the [eclipse snapshot repo](https://repo.eclipse.org/content/repositories/microprofile-snapshots/org/eclipse/microprofile/lra/microprofile-lra-api/1.0-SNAPSHOT/) soon.
> JBTM-3145 thorntail resteasy providers error and update microprofile-lra snapshot version

- ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/BaseTransactionManagerDelegate.java
They are no longer used in WildFly and have a performance cost
> JBTM-3166 TransactionListener's should not be enabled by default

- rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/lra-filters/pom.xml
- rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- rts/lra/lra-proxy/api/pom.xml
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/LRAProxyParticipant.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ParticipantProxy.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ProxyService.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/ClassPathIndexer.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRACDIExtension.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipant.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipantRegistry.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipantResource.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/jandex/DotNames.java
- rts/lra/lra-proxy/api/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
- rts/lra/lra-proxy/test/src/main/java/io/narayana/lra/proxy/test/api/LRAMgmtEgController.java
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
- rts/lra/lra-test/basic/pom.xml
- rts/lra/lra-test/basic/src/test/java/io/narayana/lra/arquillian/NonRootLRAParticipantIT.java
- rts/lra/lra-test/tck/pom.xml
- rts/lra/lra-test/tck/src/test/java/io/narayana/lra/tck/arquillian/ConfigAuxiliaryArchiveAppender.java
- rts/lra/pom.xml
This PR updates LRA to:
```xml
<version.microprofile.lra.api>1.0-20190519.061148-384</version.microprofile.lra.api>
<version.microprofile.lra.tck>1.0-20190519.061150-384</version.microprofile.lra.tck>
```
It provides mainly [spec issue 35](https://github.com/eclipse/microprofile-lra/issues/35) implementation and the update for the removal of LRAManagement from the spec.
Please note that possible CompletionStage optimization is left for another PR.
> JBTM-3087 Ensure the LRA implementation is up to date

- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/recovery/BasicXARecovery.java
- ArjunaJTA/jdbc/src/test/resources/h2recovery-multiple-properties.xml
- ArjunaJTA/jdbc/tests/classes/com/arjuna/ats/internal/jdbc/recovery/BasicXARecoveryTest.java
when multiple connections are configured
https://issues.jboss.org/browse/JBTM-3170
MAIN TOMCAT WIN
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !AS_TESTS !JACOCO !LRA
> [JBTM-3170] fix for wrong parsing jdbc connection property name

- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-test/tck/pom.xml
- rts/lra/lra-test/tck/src/test/resources/arquillian-thorntail.xml
- rts/lra/pom.xml
https://issues.jboss.org/browse/JBTM-3171
MAIN !TOMCAT !WIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !AS_TESTS !JACOCO
LRA includes the capability to receive JAX-RS notifications when an LRA is finished but the implementation does not set the "recovery header". This requirement was added in MP-LRA issue eclipse/microprofile-lra#209 with new tests to verify that the recovery header is set correctly.
The PR also updates the implementation to use the new name for MP-LRA config properties (that replace lra.tck.consistency.delay)
> JBTM-3171 Set recovery header on AfterLRA notifications.

- rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-test/basic/src/test/java/io/narayana/lra/arquillian/NonRootLRAParticipantIT.java
- rts/lra/lra-test/basic/src/test/java/io/narayana/lra/arquillian/resource/TestLRAParticipant.java
https://issues.jboss.org/browse/JBTM-3116
If an LRA is closing (due to a participant report 202 Accepted when asked to complete) then the current implementation returns the wrong status (Cancelling instead of Closing). This PR reports the status correctly.
> JBTM-3082 Wrong LRA status reported when it is Closing

- rts/lra/lra-annotation-checker/pom.xml
- rts/lra/lra-client/pom.xml
- rts/lra/lra-coordinator/pom.xml
- rts/lra/lra-proxy/api/pom.xml
- rts/lra/lra-proxy/pom.xml
- rts/lra/lra-service-base/pom.xml
- rts/lra/narayana-lra/pom.xml
https://issues.jboss.org/browse/JBTM-3181
as the `nexus-staging-maven-plugin` was not forgotten for the release profiles few times already I moved them to the profile in all lra pom.xml. For being obvious they are essential part for the `release` profile.
MAIN LRA
> [JBTM-3181] updating pom.xml for the lra-proxy-api to be released on nexus

- ArjunaJTA/cdi/pom.xml
- pom.xml
- rts/lra/lra-proxy/api/pom.xml
https://issues.jboss.org/browse/JBTM-3185
Update for jandex index version used at ARjunaJTA/cdi.
MAIN WIN LRA AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !JACOCO
> [JBTM-3185] updating use of jandex version for narayana-jta cdi

- ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/objectstore/CachedTest.java
A test correction for https://issues.jboss.org/browse/JBTM-3195 but the underlying issue still needs investigation
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !LRA
> JBTM-3195 Don't assert before all the threads return

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/Listener.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/SubordinateAtomicActionRecoveryModule.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/jca/SubordinateAtomicAction.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
https://issues.jboss.org/browse/JBTM-3210
Backport of master PR: https://github.com/jbosstm/narayana/pull/1514
Not being stuck with IllegalArgument exception during recovery and closing recovery listener connection when there is no plan of processing it.
MAIN XTS AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA
> JBTM-3210 recovery listener to not being stuck

- narayana-full/src/main/assembly/bin.xml
- rts/lra/lra-annotation-checker/pom.xml
- rts/lra/lra-client/pom.xml
- rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/lra-coordinator-jar/pom.xml
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-coordinator-thorntail/pom.xml
- rts/lra/lra-proxy/api/pom.xml
- rts/lra/lra-proxy/test/pom.xml
- rts/lra/lra-service-base/pom.xml
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/LRAHttpClient.java
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/RequestBuilder.java
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/ResponseHolder.java
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
- rts/lra/lra-test/lra-test-arquillian-extension/pom.xml
- rts/lra/lra-test/lra-test-arquillian-extension/src/main/java/io/narayana/lra/arquillian/ConfigAuxiliaryArchiveAppender.java
- rts/lra/lra-test/lra-test-basic/pom.xml
- rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/NonRootLRAParticipantIT.java
- rts/lra/lra-test/lra-test-basic/src/test/resources/arquillian-thorntail.xml
- rts/lra/lra-test/lra-test-tck/pom.xml
- rts/lra/narayana-lra/pom.xml
- rts/lra/narayana-lra/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- rts/lra/pom.xml
https://issues.jboss.org/browse/JBTM-3189
https://issues.jboss.org/browse/JBTM-3211
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !MAIN
The ultimate fix could be to wait for Java 11 HttpClient but this PR uses something similar (it replaces RestEasy client with Apache HttpClient). NB the coordinator uses an http client to contact participants and the server JAX-RS filter uses it to contact a coordinator.
> JBTM-3189 Cancel LRAs as soon as their timeLimit is reached

- ArjunaJTA/narayana-jta/src/main/resources/jbossts-properties.xml
- ArjunaJTS/narayana-jts-ibmorb/src/main/resources/jbossts-properties.xml
- ArjunaJTS/narayana-jts-idlj/src/main/resources/jbossts-properties.xml
- ArjunaJTS/narayana-jts-jacorb/src/main/resources/jbossts-properties.xml
https://issues.jboss.org/browse/JBTM-3216
forum at: https://developer.jboss.org/message/991332
MAIN QA_JTA QA_JTS_OPENJDKORB
!QA_JTS_JDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA
> [JBTM-3216] narrow and fix recovery setup in jbossts-properties.xml descriptors

- pom.xml
- rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/lra-coordinator-jar/pom.xml
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/JaxRsActivator.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/LRACoordinatorTestCase.java
- rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/LRAListener.java
- rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/TestBase.java
- rts/lra/lra-coordinator-jar/src/test/resources/arquillian.xml
- rts/lra/lra-coordinator-jar/src/test/resources/scripts/participant-byteman-rules.btm
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/LRAConstants.java
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/RequestBuilder.java
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
- rts/lra/lra-test/lra-test-tck/pom.xml
- rts/lra/lra-test/pom.xml
- scripts/hudson/narayana.sh
https://issues.jboss.org/browse/JBTM-3212
https://issues.jboss.org/browse/JBTM-3222
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !MAIN !LRA
This PR adds recovery testing for timed out LRAs
> JBTM-3112 Respect LRA deadlines during recovery.

- pom.xml
- rts/lra/lra-coordinator-jar/pom.xml
- rts/lra/pom.xml
https://github.com/jbosstm/narayana/pull/1530
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS MAIN !LRA
The latest byteman version fails rule check validation when there are multiple rules in a script
> JBTM-3226 Downgrade byteman version when using multi rule scripts

- rts/lra/pom.xml
https://issues.jboss.org/browse/JBTM-3227
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !MAIN LRA
This PR fixes the failing CI test (testForget)
> JBTM-3227: LRA branch upgrade LRA snapshot build dependency

- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/pom.xml
https://issues.redhat.com/browse/JBTM-3229
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !MAIN LRA
This PR builds on top of the https://github.com/jbosstm/narayana/pull/1535 so it can be updated separately but we can still verify that full TCK is passing with all changes. We can merge either one of them first and I will adjust the other if needed.
> JBTM-3229 Allow to enlist AfterLRA listeners after the LRA enters the ending phase

- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
https://issues.redhat.com/browse/JBTM-3234
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !MAIN LRA
> JBTM-3234 Coordinator#getNestedLRAStatus should return ParticipantStatus

- rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery1TestCase.java
- rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery2TestCase.java
https://issues.redhat.com/browse/JBTM-3231
There are two lra coordinator crash recovery tests but the second one often fails because the (arquillian) server cannot be started. I have not been able to duplicate the problem on my laptop so as an attempted workaround I have moved each test into its own junit test suite.
> JBTM-3231 Run both crash rec tests against the same server

- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
- rts/lra/lra-test/lra-test-arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/NarayanaLRARecovery.java
https://issues.redhat.com/browse/JBTM-3265
This is follow-up to the investigation on the PR: https://github.com/jbosstm/narayana/pull/1565
Direct link on the reasoning on this PR is here: https://github.com/jbosstm/narayana/pull/1565#pullrequestreview-374334136
MAIN LRA
> [JBTM-3265] afterLRA failure loading state before the finishing the LRA end method

- rts/at/bridge/pom.xml
…during jdk9 fixes
https://issues.redhat.com/browse/JBTM-2858
MAIN RTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !TOMCAT !JACOCO !LRA !AS_TESTS
> [JBTM-2858] activate restat inbound bridge, deactivated by mistake

- rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/lra-test/lra-test-arquillian-extension/pom.xml
- rts/lra/lra-test/lra-test-arquillian-extension/src/main/java/io/narayana/lra/arquillian/ConfigAuxiliaryArchiveAppender.java
- rts/lra/lra-test/lra-test-arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/NarayanaLRARecovery.java
- rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/FailingParticipantCallsIT.java
- rts/lra/lra-test/lra-test-tck/pom.xml
- rts/lra/lra-test/lra-test-tck/src/main/resources/META-INF/services/org.eclipse.microprofile.lra.tck.service.spi.LRARecoveryService
- rts/lra/narayana-lra/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- rts/lra/pom.xml
https://issues.redhat.com/browse/JBTM-3261
I am disabling all CI testing because there is currently no available MP LRA snapshot that the Narayana implementation would still be able to pass. I am going to work on bring LRA implementation in the master branch up to date with the specification after this PR is merged.
LRA !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3261 Merge LRA branch to the master branch

- rts/lra/lra-test/lra-test-tck/pom.xml
- rts/pom.xml
https://issues.redhat.com/browse/JBTM-3280
https://issues.redhat.com/browse/JBTM-3283
Un-ignoring `TckTests#timeLimit` as after testing it seems it was fixed meanwhile by some other fix.
Plus, fixing the -Dit.test when used with `TckRecoveryTests`.
Thanks to @xstefank to find the reason and the fix.
LRA JDK11
!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO
> JBTM-3280 unignore time limit is not failing on ci + JBTM-3283 fixing -Dit.test used

- rts/lra/lra-coordinator-thorntail/pom.xml
https://issues.redhat.com/browse/JBTM-3287
!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
Only changing the LRA module which is currently failing on test issue tracked in different JBTM thus skipping testing. lra-coordinator-thorntail doesn't contain any tests.
> JBTM-3287 Add LRA API dependency to ThornTail LRA coordinator

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/RecoveryRequired.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaLogger.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryMonitorTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryMonitorTest2.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryScanTest.java
https://issues.redhat.com/browse/JBTM-3273
!MAIN
!QA_JTS_JACORB
!QA_JTS_JDKORB
!QA_JTS_OPENJDKORB
AS_TESTS JDK11
!PERF
!XTS
!CORE
!BLACKTIE
!RTS
!mysql
!postgres
!db2
!oracle
!TOMCAT
!JACOCO
!LRA
> JBTM-3273 -> Avoid implementing InvocationHandler in jtaLogger

- scripts/hudson/narayana.sh
Solution for our CI environment on the unstable AS_TESTS axis.
See more at https://issues.redhat.com/browse/WFLY-13385
AS_TESTS
!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA
> CI SCRIPTS: stabilize AS_TESTS axis, see more at WFLY-13385

- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/RecoveryCoordinator.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/LRAStatusHolder.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java
- rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery2TestCase.java
- rts/lra/lra-test/lra-test-basic/pom.xml
- rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/FailedLRAIT.java
- rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/resource/LRAParticipantWithStatusURI.java
- rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/resource/LRAParticipantWithoutStatusURI.java
- rts/lra/lra-test/lra-test-tck/pom.xml
https://issues.redhat.com/browse/JBTM-3291
LRA MAIN !AS_TESTS !QA_JTA !JACOCO !QA_JTS_JACORB !TOMCAT !RTS !XTS !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
This PR changes the LRA implementation such that we now retain failure records (previously we reported the failure and then deleted them).
The OpenAPI doc for reading the records justifies their retention by saying:
"Failure records are vital pieces of data needed to aid failure tracking and analysis and are retained for inspection."
And I raised [JBTM-3297](https://issues.redhat.com/browse/JBTM-3297) to move these records to another part of the store so that standard LRA recovery processing does not need to read them.
> JBTM-3247 Do not delete LRA records on the failed list

- rts/lra/pom.xml
> LRA - upgrade eclipse mp-lra api and tck version to 20200428

- rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery2TestCase.java
https://issues.redhat.com/browse/JBTM-3307
This test is regularly failing so this PR temporarily disables it until JBTM-3307 makes the test more robust.
!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3307 Temporarily disable LRACoordinatorRecovery2TestCase

- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
https://issues.redhat.com/browse/JBTM-3312
I believe this else statement is wrong because the value of `res` is not changed since at least line [508](https://github.com/jbosstm/narayana/compare/master...xstefank:jbtm-3312?expand=1#diff-57ec69ca0d35bbed0ad018339b532a7dL508) which is in case of after LRA method present H_HAZARD. This state of the BasicAction is then changed in `runPostLRAActions()` method by a call to `super.phase2Commit(true);` which changes the state of the BasicAction to H_COMMIT but this value is not returned. So the switch in `toLRAStatus` gets the H_HAZARD value which is not present and thus the default …
> JBTM-3312 After LRA notifications can keep the LRA in Active state

- scripts/hudson/narayana.sh
the change of the connection-timeout has to be propagated into the jboss-cli.xml before the tests start
Another attempt around the AS_TESTS axis.
AS_TESTS
> CI SCRIPTS: a follow-up fix for stabilizing AS_TESTS axis (WFLY-1338)

- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/RunnableWithException.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionHandler.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/async/ContextPropagationAsyncHandler.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/transactional/TransactionalInterceptorBase.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/transactional/TransactionalInterceptorRequiresNew.java
- ArjunaJTA/cdi/pom.xml
- pom.xml
https://issues.redhat.com/browse/JBTM-3246
Adapting the code from Quarkus to handle asynchronous calls for context propagation MP spec.
The class 'ContextPropagationAsyncHandler' is deliberately published with the ASL v.2.
The result needs to be tested with WildFly and changes for MicroProfile. If the results passes the MP TCK will be checked with @kabir
MAIN AS_TESTS
> [JBTM-3246] adapting async handling for CDI interceptors

- rts/lra/lra-test/lra-test-tck/pom.xml
- rts/lra/lra-test/lra-test-tck/src/test/resources/arquillian-thorntail.xml
- scripts/hudson/narayana.sh
https://issues.redhat.com/browse/JBTM-3316
This fix could help in CI instability for `TckTests#timeLimit`
LRA
> [JBTM-3316] use LRA TCK timeout factor instead of delays

- ArjunaJTA/narayana-jta/pom.xml
- narayana-full/pom.xml
to build javadoc on JDK11
https://issues.redhat.com/browse/JBTM-3317
MAIN JDK11
> [JBTM-3317] adding dependencies on reactive to the shaded jars

- rts/lra/lra-test/lra-test-tck/pom.xml
- rts/lra/pom.xml
https://issues.redhat.com/browse/JBTM-3318
https://issues.redhat.com/browse/JBTM-3319
LRA
> [JBTM-3318][JBTM-3319] ignore the failing test on CI + using lra spec version 1.0-M1

- scripts/hudson/narayana.sh
…than the default value 5400
AS_TESTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS  !TOMCAT !JACOCO !LRA
> CI SCRIPTS: astests clustering needs greater surefire timeout

- rts/at/bridge/src/main/java/org/jboss/narayana/rest/bridge/inbound/InboundBridgeFilter.java
https://issues.redhat.com/browse/JBTM-3321
RTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !LRA
> [JBTM-3321] use non USER priority for REST-AT inbound bridge JAX-RS filter

- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqObjectStoreAdaptor.java
https://issues.redhat.com/browse/JBTM-3332
MAIN AS_TESTS
> [JBTM-3332] Add a constructor to the HornetQ/Artemis object store adaptor to support named bean lookup.

- common/tests/com/arjuna/common/tests/propertyservice/EmptyPropertiesFactoryTest.java
https://issues.redhat.com/browse/JBTM-3337
MAIN JDK11
> [JBTM-3337] fixing EmptyPropertiesFactoryTest as all the JDK properties have to be preserved

- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java
https://issues.redhat.com/browse/JBTM-3341
> JBTM-3341 Failed LRA is not kept in FailedTo* state in the object store

- narayana-release-process.sh
Ant uploading the compiled artifacts is still needed but website update can be avoided.
NO_TEST
> [SCRIPTS ONLY] release copy of artifacts is needed but we still avoid website update

- scripts/hudson/narayana.sh
> [SCRIPTS ONLY] fixing the command to run WFLY testsuite to not fail on TCK rest client tests

- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipant.java
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/AnnotationResolver.java
- rts/lra/narayana-lra/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
https://issues.redhat.com/browse/JBTM-3360
!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3360 ServerLRAFilter is relying on the wrong RESTEasy behavior

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/Listener.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedElement.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedXAResource.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedXid.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/RecoveryXids.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/SubordinateAtomicActionRecoveryModule.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/jca/SubordinateAtomicAction.java
- ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/jca/XATerminatorUnitTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryXidsUnitTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARecoveryModuleUnitTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/ImportNonUniqueBranchTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/ResourceManager.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceImpl.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceRecordWrappingPluginImpl.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceWrapperImpl.java
- ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
https://issues.redhat.com/projects/JBTM/issues/JBTM-3361
This PR is the back port of the fix for JBTM-3361 on master.
It includes a boolean system property called tx-recover-non-unique-xids (set it to true to enable the patch)
This previous run hung on SimpleIsolatedServers#testSimultaneousRecover and I am rerunning just the MAIN axis to get a stack trace and I updated the job to enable the property tx-recover-non-unique-xids.
XTS AS_TESTS
!QA_JTA !QA_JTS_OPENJDKORB
!TOMCAT !RTS !JACOCO !QA_JTS_JACORB !QA_JTS_JDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres oracle
> [JBTM-3361] backport to the 4.17 branch

- rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/CoordinatorContainerFilter.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/RecoveryCoordinator.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ProxyService.java
- rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipantResource.java
- rts/lra/lra-proxy/test/src/main/java/io/narayana/lra/proxy/test/service/ActivityService.java
- rts/lra/lra-service-base/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
- rts/lra/narayana-lra/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
https://issues.redhat.com/browse/JBTM-3368
Idea of this PR is having information on error response. This helps in debugging and test investigation and expecting for users as well.
LRA
> [JBTM-3368] provide error messages in the HTTP responses

- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/ImportNonUniqueBranchTest.java
[JBTM-3361](https://issues.redhat.com/browse/JBTM-3361) recovery for non-unique xids
The initial fix for JBTM-3361 included a reproducer as a unit test. But the reproducer should only be applied to the code that contained the bug and not to the fixed code. This PR removes the reproducer test (and I updated the issue description to say how the issue can be reproduced). 
MAIN
!JACOCO !AS_TESTS !XTS !TOMCAT !AS_TESTS !RTS JACOCO !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3361 disable reproducer - attach it to the case notes instead

- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/integration/CMRIntegrationTest.java
https://issues.redhat.com/browse/JBTM-3376
AS_TESTS
> [JBTM-3376] clean CMRIntegrationTest to be more transparent and get more info when it fails

- ArjunaJTA/jta/src/test/resources/standalone-cmr.xml
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/integration/CMRIntegrationTest.java
https://issues.redhat.com/browse/JBTM-3376
Making the test working on older WildFly app servers.
Making the test better in way of understanding the failures.
!MAIN AS_TESTS
!QA_JTS_JACORB !QA_JTA !XTS !QA_JTS_JDKORB
> JBTM-3376 clean CMR integration test 4.17

- narayana-full/src/main/assembly/bin.xml
fix narayanaa-full assembly quarkus lib directory to be involved
https://issues.redhat.com/browse/JBTM-3377
follow-up to https://github.com/jbosstm/narayana/pull/1703
LRA
> [JBTM-3377]: renaming LRA directory structure: follow-up

- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
fix of a failure which came from the fix https://issues.redhat.com/browse/JBTM-3349
fix for https://issues.redhat.com/browse/JBTM-3375 to run the `lra-test` quickstarts fine
LRA
> [JBTM-3349] follow-up: on joining to parent LRA the response should not be precondition failed

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedXAResource.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedXid.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/Objects.java
https://issues.redhat.com/browse/JBTM-3361
MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3361] remove java.util.Objects which is not available in JDK6

- rts/lra/client/pom.xml
- rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/client/src/main/resources/META-INF/services/javax.ws.rs.client.ClientBuilder
- rts/lra/jaxrs/src/main/resources/META-INF/services/javax.ws.rs.client.ClientBuilder
- rts/lra/service-base/pom.xml
- rts/lra/service-base/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
Hey,
I wanted to do a small contribution to the client after starting to use it. I hope you find my changes useful and relevant.
* Clean up unnecessary dependencies and reformat pom.
* Set PORT and PATH_KEY as constants. I couldn't import them properly in my code
* Fix the clientID param that was sending an object string representation.
* joinLRA with a null timelimit was throwing a NPE during the unboxing.
* Other SonarLint suggestions.
* The service provided has been replaced by the Microprofile implementation.
I didn't consider meaningful creating a Jira for this but if you feel it's a requirement even for such a small PR I'll do it.
Let me know if I didn't take something into account, specially regarding the pom.xml.
Thank you in advance.
Signed-off-by: ruromero <rromerom@redhat.com> …
> [JBTM-3381] Enhance LRA Client for Quarkus

- scripts/hudson/download-wildfly.sh
- scripts/hudson/narayana.sh
and provide a way to force not building JBoss AS when WFLY is downloaded
This is no change for the currently running CI matrix but it provides a helper functions and a way to skip the jboss as build when the CI job defines it.
Not building the AS may make pretty faster the axes like RTS, XTS, LRA.
AS_TESTS
> [SCRIPTS ONLY] adding a shell script to download WFLY

- scripts/hudson/narayana.sh
The CMR is not implemented in JBoss AS 7.2.0. AS the CMR is not available it's nonsense to force testing it as any such test fails.
MAIN
!QA_JTS_JACORB !QA_JTA !XTS !QA_JTS_JDKORB
> [SCRIPTS ONLY] allow to skip CMR tests when defined in job config

- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery1TestCase.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery2TestCase.java
- rts/lra/jaxrs/pom.xml
- rts/lra/pom.xml
- rts/lra/test/basic/pom.xml
- rts/lra/test/tck/pom.xml
https://issues.redhat.com/browse/JBTM-3389
LRA
> [JBTM-3389] removing apache httpclient depenendencies as not used anymore

- rts/lra/service-base/src/main/java/io/narayana/lra/LRAConstants.java
Revert of the adjustment for JBTM-3379 - https://issues.redhat.com/browse/JBTM-3379
LRA
> [JBTM-3379] Revert: make participant timeout configurable

- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/client/LRAIT.java
https://issues.redhat.com/browse/JBTM-3342
This fixes a rebase error where one of the merges broke one of the others (new `NarayanaLRAClient()` no longer throws URISyntaxException).
LRA
> JBTM-3394 fix merge conflict

- scripts/hudson/narayana.bat
- scripts/hudson/narayana.sh
NO_WIN !MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB BLACKTIE !PERF !LRA !DB_TESTS mysql db2 postgres oracle
> CI SCRIPT ONLY: Fail the build if wget of openjdk-orb jar does not work

- scripts/hudson/narayana.sh
- txframework/pom.xml
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB
I need to provide few more changes in 4.17 branch as not all axes work fine on JDK6 and AMS CI.
I ran jobs with this additional set of changes and with them it all seems should be working finally now.
> JDK6 changes to run on CI testing (4.17)

- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/client/NarayanaLRAClientIT.java
https://issues.redhat.com/browse/JBTM-3395
LRA
> [JBTM-3395] fixes of failures on the basic IT tests

- rts/lra/coordinator/pom.xml
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery2TestCase.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/TimeoutValueAdjuster.java
- rts/lra/pom.xml
- rts/lra/test/tck/pom.xml
https://issues.redhat.com/browse/JBTM-3307
LRA
> [JBTM-3307] enabling LRACoordinatorRecovery2TestCase with timeout adjustments

- ArjunaJTA/jta/src/test/resources/standalone-cmr.xml
- scripts/hudson/narayana.sh
After few prior PRs for 4.17 JDK6 compatibility and ability to run tests with JDK6 this one fixes some failures which I got on further running of the tests.
CMR tests requires a bit more time for data insertion and XTS has got troubles with network errors which seem to be caused by not asking for IPv4 explicitly.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB
> Intermittent test failure stabilization (4.17)

- ArjunaJTA/narayana-jta/pom.xml
- ArjunaJTS/narayana-jts-ibmorb/pom.xml
- ArjunaJTS/narayana-jts-idlj/pom.xml
- ArjunaJTS/narayana-jts-jacorb/pom.xml
I noticed this was missing from narayana-jta while importing the module into an IDE. I added it to some other poms and running CI to test it. It may be required in other shaded jars? …
> Indicate that the artemis journal is a provided dependency

- rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
- rts/lra/service-base/src/main/java/io/narayana/lra/LRAData.java
- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/client/NarayanaLRAClientIT.java
https://issues.redhat.com/browse/JBTM-3411
This is a change that I benefit when working with `NaraynaLRAClient` and when I'm creating new tests.
It's about adding cause for the thrown exception that could be processed in the code or assertion.
Plus, `URI` is more convenient format than String parsing.
LRA
> [JBTM-3411] enhance exception reporting for NarayanaLRAClient

- scripts/hudson/narayana-rebase.sh
- scripts/hudson/narayana.bat
- scripts/hudson/narayana.sh
Using github token instead of direct password for commenting on PRs.
For not getting errors like 
```
{
"message": "Requires authentication",
"documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue-comment"
}
```
!QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTA !XTS !RTS !AS_TESTS
> [SCRIPTS ONLY] using github token for posting comments on PRs

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/slot/PmemSlots.java
- ArjunaCore/arjuna/pom.xml
Adds a very fast objectstore alternative for systems with persistent memory hardware.
https://issues.redhat.com/browse/JBTM-3417
MAIN CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle
> JBTM-3417 Add Persistent Memory SlotStore backend

- ArjunaJTS/jtax/pom.xml
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
QA_JTS_JACORB
QA_JTS_JDKORB
QA_JTS_OPENJDKORB
I excluded TransactionImpleUnitTest from the surefire profile that tests [JacORB](https://www.jacorb.org/). This is because of the issue [JBTM-3403](https://issues.redhat.com/browse/JBTM-3403). All other profiles (jts-idlj and jts-openjdk) still run TransactionImpleUnitTest.
> [JBTM-3403] Excluded TransactionImpleUnitTest from the Jacorb surefire profile

- rts/lra/coordinator/pom.xml
https://issues.redhat.com/browse/JBTM-3343
With changing the tests in `lra/test` module I forgot to make this change in `lra/coordinator`. This change could be unnecessary when PR #1764 merged but until that it would be good to enable tests in `coordinator`. What this small adjustment enables.
LRA
> [JBTM-3343] fix for arq test being executed within coordinator module

- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/common/AbstractCrashRecoveryTests.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/common/OnServerRebootInstrumentator.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/junit/InboundCrashRecoveryTests.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/outbound/junit/OutboundCrashRecoveryTests.java
Tests for the fix of https://issues.redhat.com/browse/JBTM-3406
@jhalliday may you take a look, please?
XTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA
> [JBTM-3406] test that different node name is not recovered

- ArjunaJTS/jtax/pom.xml
- pom.xml
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/common/AbstractCrashRecoveryTests.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/common/OnServerRebootInstrumentator.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/junit/InboundCrashRecoveryTests.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/outbound/junit/OutboundCrashRecoveryTests.java
A test for https://issues.redhat.com/browse/JBTM-3406
The master PR: https://github.com/jbosstm/narayana/pull/1768
The 4.17 PR: https://github.com/jbosstm/narayana/pull/1771
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA
XTS MAIN
> [JBTM-3406](5.9) test that different node name is not recovered in XTS inbound txbridge recovery module

- ArjunaCore/arjuna/pom.xml
- narayana-full/pom.xml
- pom.xml
https://issues.redhat.com/browse/JBTM-3421
This is a follow up to JBTM-3417 (Add Persistent Memory SlotStore backend) to workaround a javadoc issue compiling on JDK 11. I'm not sure if it is the best fix but it will do as a stop gap (an example of the compilation failure is http://narayanaci1.eng.hst.ams2.redhat.com/job/narayana/PROFILE=CORE,jdk=jdk11.latest,label=linux/21/consoleFull).
We are using OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10-LTS, mixed mode, sharing)
MAIN CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3421 remove provided scope for artefact mashona:mashona-logwriting

- pom.xml
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/common/AbstractCrashRecoveryTests.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/common/OnServerRebootInstrumentator.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/junit/InboundCrashRecoveryTests.java
- txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/outbound/junit/OutboundCrashRecoveryTests.java
A test for https://issues.redhat.com/browse/JBTM-3406
The master PR: https://github.com/jbosstm/narayana/pull/1768
The 5.9 PR: https://github.com/jbosstm/narayana/pull/1770
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA
XTS MAIN
> [JBTM-3406](4.17) test that different node name is not recovered in XTS inbound txbridge recovery module

- blacktie/utils/cpp-plugin/pom.xml
https://issues.redhat.com/browse/JBTM-3423
BLACKTIE: NoSuchMethodError: org.apache.tools.ant.launch.Locator.fromJarURI(Ljava/lang/String; while generating IDL sources RTS: InboundBridgeRecoveryTestCase.testCrashBeforeCommit:137 Recovery failed
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
BLACKTIE
> BLACKTIE: NoSuchMethodError: org.apache.tools.ant.launch.Locator.fromJarURI

- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/FailedLongRunningAction.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
- rts/lra/service-base/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/FailedLRAIT.java
https://issues.redhat.com/browse/JBTM-3297
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3297: Move LRA failure records to another part of the store

- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
https://issues.redhat.com/browse/JBTM-3428
LRA
This is a second attempt at fixing JBTM-3428 (the first one was pr/1786 which was testing for lraRecoveryModule != null instead of == null)
> JBTM-3428 initialise LRA recovery module correctly

- rts/lra/pom.xml
Downgrade MP LRA to 1.0-RC2 for the CCR. This also removes the hardcoded staging repository of MP LRA 1.0. Please let me know whether a JBTM is needed for this change.
> Downgrade MP LRA to 1.0-RC2

- ArjunaJTS/jacorb/etc/jacorb.properties
- ArjunaJTS/jacorb/etc/jacorb_properties.template
- ArjunaJTS/jacorb/etc/orb.properties
- ArjunaJTS/jtax/src/test/resources/jacorb.properties
https://issues.redhat.com/browse/JBTM-3435
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS QA_JTA QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
I've changed it to only log fatal errors (value 1). If we want to disable logging completely then the value would need to be 0.
> JBTM-3435 Disable JacORB logging

- .github/workflows/lra-test.yml
https://issues.redhat.com/browse/JBTM-3372
!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN DB_TESTS !mysql !db2 !postgres !oracle
Examples:
https://github.com/xstefank/narayana/pull/3
https://github.com/xstefank/narayana/pull/2
Note that this action can't run the tests that depend on the running WFLY. If that is a requirement we need to setup WFLY download in the lra-coordinator-jar module.
> [JBTM-3372] Add GH Actions workflow for LRA testing

- pom.xml
- rts/lra/API.adoc
- rts/lra/client/pom.xml
- rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
- rts/lra/coordinator/pom.xml
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/CoordinatorContainerFilter.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/coordinator/src/test/resources/arquillian.xml
- rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
- rts/lra/pom.xml
- rts/lra/proxy/api/src/main/java/io/narayana/lra/proxy/logging/lraI18NLogger.java
- rts/lra/service-base/pom.xml
- rts/lra/service-base/src/main/java/io/narayana/lra/LRAConstants.java
- rts/lra/service-base/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
- rts/lra/service-base/src/test/java/io/narayana/lra/LRAConstantsTest.java
- rts/lra/test/arquillian-extension/pom.xml
- rts/lra/test/arquillian-extension/src/main/java/io/narayana/lra/arquillian/AppServerCoordinatorDeploymentObserver.java
- rts/lra/test/arquillian-extension/src/main/java/io/narayana/lra/arquillian/ArquillianParametrized.java
- rts/lra/test/basic/pom.xml
- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/api/CoordinatorApiIT.java
- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/api/CoordinatorApiWrongVersionIT.java
- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/api/ValidTestVersions.java
- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/api/ValidTestVersionsRule.java
- rts/lra/test/basic/src/test/resources/META-INF/services/javax.ws.rs.client.ClientBuilder
https://issues.redhat.com/browse/JBTM-3294
I'm publishing this withouth having finished similar work which I would like to do with `RecoveryCoordinator`. I hope for `Coordinator` this is acceptable to be discussed and hopefully merged.
LRA
/cc @xstefank
> [JBTM-3294] adding HTTP version headers for coordinator

- rts/lra/coordinator-thorntail/pom.xml
https://issues.redhat.com/browse/JBTM-3443
superseding the PR: https://github.com/jbosstm/narayana/pull/1801
CORE WIN LRA
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !AS_TESTS !TOMCAT !JACOCO
> [JBTM-3443] exclude orson dependency from thorntail-coordinator to not generate error on build

- README.md
This is just a minor enhancement in *readme* file to add a project version which would point to maven repository page.
These badges would be a quick info to the Narayana users/contributors or new comer to the repository. As whosever visit to any repository in git, tries to have a quick look into the readme of that project.
The eye catchy badges would give quick and important piece of information about our project without digging into files for the info.
Since the change is only in readme file, therefore triggering a CI build would not be necessary.
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> Adding version badge to readme file

- rts/lra/coordinator-quarkus/pom.xml
MAIN
When we do the release we use the `-Prelease` which activates the release profile. The maven behaviour for `<activeByDefault>true</activeByDefault>` is that `activeByDefault` profile is not activated when another profile is activated explicitly with `mvn -P...`.
As we use `-Prelease` for release then the `uber-jar` profile is not activated and the `-runnner.jar` is not deployed to nexus. The uber jar profile has to be activated regardless if `-P` is or isn't used.
> [RELEASE] on release deploy to deploy lra-coordinator-quarkus-runner jar as well

- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/SneakyThrow.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionHandler.java
- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/transactional/TransactionalInterceptorBase.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/TestTransactionalBean.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/TransactionalImplTest.java
https://issues.redhat.com/browse/JBTM-3454
MAIN AS_TESTS
> [JBTM-3454] JTA CDI should roll-back when java.lang.Error is thrown from the @Transactional method

- scripts/hudson/narayana.sh
spliting makes possible to separately download, build and test the application server. Such a parametrization is useful mostly for a customized CI jobs which runs some specific aspects of the testing.
Motivation: investigating on errors of 5.11.1.Final for WildFly builds - https://issues.redhat.com/browse/WFLY-14701
MAIN RTS LRA AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !TOMCAT !JACOCO
> [SCRIPTS ONLY] narayana.sh to split the AS_TESTS to multiple functions

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
https://issues.redhat.com/browse/JBTM-3468
AS_TESTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS  !TOMCAT !JACOCO !LRA
> [JBTM-3468] omit throwing NPE on generating stack trace in reaper worker thread

- rts/pom.xml
This PR fixes https://issues.redhat.com/browse/JBTM-3475
Profiles to test:
RTS
Skipped profiles:
!MAIN !CORE !TOMCAT !AS_TESTS !JACOCO XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3475] removed dependencies from RTS

- rts/lra/annotation-checker/pom.xml
- rts/lra/client/pom.xml
- rts/lra/coordinator-thorntail/pom.xml
- rts/lra/coordinator/pom.xml
- rts/lra/jaxrs/pom.xml
- rts/lra/pom.xml
- rts/lra/proxy/api/pom.xml
- rts/lra/proxy/test/pom.xml
- rts/lra/service-base/pom.xml
- rts/lra/test/arquillian-extension/pom.xml
- rts/lra/test/tck/pom.xml
https://issues.redhat.com/browse/JBTM-3481
I also changed the mp.lra version property to be the same for API and TCK. I don't remember why we needed this distinction, but it hasn't been used long.
> JBTM-3481 Upgrade MicroProfile LRA to 1.0

- scripts/hudson/narayana.sh
This provide a way to control the CI test execution in more granularity.
This makes possible to hook into the process and e.g. clone a specific
(a different) WildFly sources before the script itself is run in the CI
job.
MAIN RTS LRA XTS AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !TOMCAT !JACOCO
> [SCRIPTS ONLY] making the step of cloning of WildFly sources as an individual step

- ArjunaCore/arjuna/pom.xml
- ArjunaJTA/jta/pom.xml
- pom.xml
- qa/TaskImpl.properties.template
- qa/build.xml
- qa/config/jdbc_profiles/default/JDBCProfiles
- qa/pom.xml
- qa/run-tests.xml
This PR is for back porting to Narayana 5.9 the new oracle driver in [QA](https://github.com/jbosstm/narayana/pull/1829) and in [ArjunaCore.arjuna](https://github.com/jbosstm/narayana/pull/1844)
This PR backports JIRAs:
[JBTM-3486](https://issues.redhat.com/browse/JBTM-3486)
[JBTM-3450](https://issues.redhat.com/browse/JBTM-3450)
QA_JTA DB_TESTS oracle
Test to exclude:
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !mysql !db2 !postgres
> [JBTM-3450] Back ported JBTM-3450 to Narayana 5.9

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/RecoveryXids.java
https://issues.redhat.com/browse/JBTM-3488
MAIN AS_TESTS
> [JBTM-3488] Make orphan safety interval configurable without JVM restart

- rts/lra/client/pom.xml
- rts/lra/client/src/main/resources/META-INF/services/javax.ws.rs.client.ClientBuilder
This PR addressed [JBTM-3479](https://issues.redhat.com/browse/JBTM-3479)
LRA
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3479] Added resteasy-client and resteasy-jackson2-provider dependencies to the lra-client module

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/BaseTransaction.java
https://issues.redhat.com/browse/JBTM-3509
MAIN CORE TOMCAT AS_TESTS !RTS JACOCO !XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS mysql db2 postgres oracle
> JBTM-3509 Small optimisations in setting Transaction Timeout

- ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/transactional/TransactionalInterceptorBase.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/ejb/CdiWeldFailureWithEjbTest.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/ejb/StatelessEjbCaller.java
- ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/ejb/TransactionalEjbCalled.java
- CONTRIBUTING.md
https://issues.redhat.com/browse/JBTM-3503
superseding https://github.com/jbosstm/narayana/pull/1866
MAIN AS_TESTS
> [JBTM-3503] when Weld does not provide @Transactional annotations using prior way of searching it

- narayana-release-process.sh
- scripts/branch-names.sh
- scripts/hudson/narayana.sh
This PR addresses [JBTM-3519](https://issues.redhat.com/browse/JBTM-3519)
AS_TESTS RTS XTS
!MAIN !CORE !TOMCAT !JACOCO !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3519] Replaced 'master' with 'main' when the repository github.com/wildfly/wildfly is used

- rts/lra/test/README.adoc
- rts/lra/test/pom.xml
- scripts/hudson/narayana.sh
This PR addressed this [JIRA](https://issues.redhat.com/browse/JBTM-3427).
NOTE: there are two new testing axes for Long Running Action
MAIN CORE RTS LRA
!TOMCAT !AS_TESTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3427] split arq and arq.quarkus profiles

- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java
- rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
LRA
https://issues.redhat.com/browse/JBTM-3523
I would like to propose a change in the logging of the error during after lra call from coordinator. Currently it's hidden under `debug` without the whole stacktrace. When an error happens then it's "invisible" without details. When the call goes wrong then it leads to an unrecoverable lra records (`afterLRARequest` returns `false` and the `TwoPhaseOutcome.HEURISTIC_HAZARD` is returned, https://github.com/jbosstm/narayana/blob/b4bd01f695af5fb92bed70fe1502bb606b305579/rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java#L512) while the reason for the error is difficult …
> [JBTM-3523] print warning with cause when AfterLRA call does not proceed well

- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
https://issues.redhat.com/browse/JBTM-3531
LRA
> [JBTM-3531] print warning when exception causes the LRA record cannot be removed from object store

- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/Deployer.java
https://issues.redhat.com/browse/JBTM-3530
LRA
> [JBTM-3530] no Weld classloading error logs at lra/basic FailedLRAIT

- rts/lra/test/pom.xml
This PR addresses [JBTM-3526](https://issues.redhat.com/browse/JBTM-3526)
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3526] Split failsafe reports based on running arq profile

- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
- rts/lra/test/arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/NarayanaLRARecovery.java
https://issues.redhat.com/browse/JBTM-3538
This PR is designed to fix timeout test instabilities.
It is in 4 separate, but related, commits. It also reverts the recent change to use the reaper for timeouts since that does not work with WildFly (we can revisit that in a future commit after discussion with the resteasy team).
After fixing the timeout instability I found that 3 of the nested LRA tests failed which I fixed in the last commit.
LRA
> JBTM 3538 Fix for TCK timeout test failures

- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
- rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
https://issues.redhat.com/browse/JBTM-3541
LRA
> [JBTM-3541] adjustments on LRA log messages

- PULL_REQUEST_TEMPLATE.md
script only change. I've removed `MAIN` from the PR comment since `MAIN` does not do anything.
@tomjenkinson will you review this. I removed MAIN but there is a reference to in a test in `scripts/hudson/narayana.sh` that you added (sha 49d61042c51113e72a277c844902edad93c62e82) that I don't understand so I left it in there (but with my change the test definitely has no effect).
> remove reference to MAIN

- XTS/pom.xml
https://issues.redhat.com/browse/JBTM-3544
The previous PR added two unwanted jakarta dependencies to the XTS parent pom  I added these inadvertently.
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3544 fix previous commit by removing two unwanted dependencies

- rts/at/tx-jakarta/pom.xml
- rts/at/util-jakarta/pom.xml
- txbridge-jakarta/pom.xml
https://issues.redhat.com/browse/JBTM-3544
This PR follows on from #1920 and adds some missing source jars.
CORE !TOMCAT !AS_TESTS RTS !JACOCO XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3544 add missing source jars

- qa/config/jdbc_profiles/default/JDBCProfiles
- qa/tests/src/org/jboss/jbossts/qa/Utils/JDBCProfileStore.java
- qa/tests/src/org/jboss/jbossts/qa/Utils/JNDIManager.java
This PR addresses [JBTM-3553](https://issues.redhat.com/browse/JBTM-3553).
To test:
QA_JTA
To exclude:
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3553] The procedure to configure Oracle DB needs to be updated

- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/abstractrecords/DisposeRecord.java
- ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/DirectRecoverableConnection.java
Fixes https://issues.redhat.com/browse/JBTM-3562
Removes fields from child classes, where parent class provides the field.
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3562 Child class fields should not shadow parent class fields

- qa/run-tests.xml
- scripts/hudson/narayana.sh
This PR explicitly pick up an ORB implementation (i.e. OPENJDK_ORB, which is also used in WildFly) when the DB_TESTS testing axis is selected.
Axis to tests:
QA_JTA DB_TESTS mysql db2 postgres oracle
Axes to skip:
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA
> Picked up an ORB implementation for the DB_TESTS testing axis

- ArjunaCore/arjuna/pom.xml
- ArjunaCore/arjuna/src/test/resources/mysqljbossts-properties.xml
- ArjunaCore/arjuna/src/test/resources/oraclejbossts-properties.xml
- ArjunaJTA/jdbc/pom.xml
- ArjunaJTA/jta/pom.xml
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/PerformanceTestCommitMarkableResource.java
- ArjunaJTA/spi/pom.xml
- ArjunaJTA/spi/src/test/java/io/narayana/spi/util/XADSWrapperObjectFactory.java
- ArjunaJTA/spi/src/test/resources/module.xml
- README.md
- pom.xml
- qa/README.txt
- qa/TaskImpl.properties.template
- qa/build.xml
- qa/config/jdbc_profiles/_template/JDBCProfiles
- qa/config/jdbc_profiles/default/JDBCProfiles
- qa/config/jdbc_profiles/haverstraw/JDBCProfiles
- qa/config/jdbc_profiles/jaime/JDBCProfiles
- qa/pom.xml
- qa/run-tests.xml
- qa/tests/src/org/jboss/jbossts/qa/Utils/JDBCProfileStore.java
- qa/tests/src/org/jboss/jbossts/qa/Utils/JNDIManager.java
- scripts/hudson/narayana.sh
This PR is to backport the following JIRA:
- [JBTM-3486] Uncoupled ArjunaJTA.jta and ArjunaCore.arjuna from the QA module when it comes to the Oracle driver
- [JBTM-3480] Databases drivers are downloaded directly from Maven
- Removed the docker commands for setting up the databases
- [JBTM-3553] Introduced serviceName in JNDIManager to handle Oracle's services
- Change the database name from XE to XEPDB1 for certain database connection details
- [JBTM-3575] Introduced ServiceName when the JDBC object store is tested
- [SCRIPT] Modified both DB_TESTS and QA_TESTS to use OPENJDK_ORB
Passed axes:
!CORE !QA_JTS_JACORB !QA_JTS_OPENJDKORB !DB_TESTS !QA_JTA !QA_JTS_JDKORB !mysql !db2 !postgres !oracle
Skipped axes:
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !PERF !LRA
> Backport Updates to Oracle (and other DBs) to Narayana 5.11

- ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxyTests.java
- ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/ConnectionProxyTests.java
- ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelperTests.java
https://issues.redhat.com/browse/JBTM-3591
> JBTM-3591 Fix warnings from deprecated method Assert.assertThat

- scripts/hudson/narayana.sh
https://issues.redhat.com/browse/JBTM-3592
The PR corrects pr #1935 which forgot to revert the script change to use wildfly preview
JDK11 LRA !RTS !CORE !TOMCAT !AS_TESTS !XTS !JACOCO XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3592 Use standard wildfly (not preview)

- build-release-pkgs.xml
- narayana-release-process.sh
This PR changes the release scripts to use podman and changes the host that we rsync to and so there is nothing to automatically test. Next time you do a release please bear in mind these changes.
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle
> release-scripts for rsync and podman

- rts/at/tx/pom.xml
Remove defined explicit dependencies on undertow, using instead the version that is transitively provided by org.jboss.resteasy:resteasy-undertow   https://issues.redhat.com/browse/JBTM-3604
Resolve following errors:
JDK8, compilation error:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-2:testCompile (default-testCompile) on project restat-api: Compilation failure
[ERROR] /narayana/rts/at/tx/src/test/java/org/jboss/jbossts/star/test/BaseTest.java:[59,19] cannot access io.undertow.Undertow
[ERROR]   bad class file: /root/.m2/repository/io/undertow/undertow-core/2.3.0.Alpha1/undertow-core-2.3.0.Alpha1.jar(io/undertow/Undertow.class)
[ERROR]     class file has wrong version 55.0, should be 52.0`
JDK11, test errors: …
> [JBTM-3604] Remove explicit dependencies on undertow

- XTS/pom.xml
- compensations/pom.xml
- narayana-full/pom.xml
- pom.xml
- txbridge/pom.xml
- txframework/pom.xml
Update jaxws-ri dependency version from 2.3.0 to 2.3.5 https://issues.redhat.com/browse/JBTM-3605
JDK11 CORE AS_TESTS XTS !TOMCAT !RTS !JACOCO !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3605] Update jaxws-ri version from 2.3.0 to 2.3.5

- pom.xml
WildFly 26.1.1 is using jboss-parent 39: https://github.com/wildfly/wildfly/blob/26.1.1.Final/pom.xml#L29
!JDK8 JDK11
CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB PERF LRA DB_TESTS mysql db2 postgres oracle
> Update to same jboss-parent as in WildFly 26.1.1

- vertx/module/pom.xml
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle
Here is where it was skipped https://github.com/jbosstm/narayana/pull/1364/files#diff-ab5e55e6fb3251f6c514a7fa77dbe902e1e088cfbc2a8a7dcffd12deab4fa0f7R311
This is the Jira that commit is connected to: https://issues.redhat.com/browse/JBTM-2685
> Re-introduce the vertx/module testing that was disabled for JDK+ in 4e4a477e49feeb3784f3b469387964ff4dd8d29c

- code-coverage/pom.xml
https://issues.redhat.com/browse/JBTM-3590
!CORE !TOMCAT !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3590] Removed idlj surefire profiles from code-coverage

- ArjunaJTS/orbportability/config/idl-compiler-definitions.xml
JBTM-3950 leftover
Passed
!CORE !QA_JTS_JACORB !QA_JTS_OPENJDKORB
Failed:
QA_JTA 
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3950] removed idlj orb compiler

- ArjunaJTA/jms/pom.xml
- ArjunaJTS/jts/pom.xml
- pom.xml
- qa/pom.xml
- rts/at/util/pom.xml
https://issues.redhat.com/browse/JBTM-3637
Remove log4j ( https://mvnrepository.com/artifact/log4j/log4j)  from ./ArjunaJTA/jms/pom.xml ./ArjunaJTS/jts/pom.xml ./qa/pom.xml ./rts/at/util/pom.xml
CORE TOMCAT AS_TESTS RTS !JACOCO XTS QA_JTA QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3637] Remove references to Log4j 1

- pom.xml
- scripts/hudson/narayana.sh
Build and test narayana using the most recent WildFly version that supports JDK 17 and javaee.
CORE RTS LRA XTS AS_TESTS
JDK17 JDK11
!TOMCAT !JACOCO XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !DB_TESTS mysql db2 postgres oracle
> Wildfly jdk17

- rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
https://issues.redhat.com/browse/JBTM-3674
The PR only adds the Deprecated annotation to the class NarayanaLRAClient hence
NO_TEST
> JBTM-3674 Explicitly mark NarayanaLRAClient as deprecated

- ArjunaJTA/jms/pom.xml
- ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/JMSContextIntegrationTest.java
- ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/JmsIntegrationTests.java
- ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/JmsRecoveryIntegrationTests.java
- ArjunaJTS/integration/pom.xml
- ArjunaJTS/integration/src/main/java/com/arjuna/ats/internal/jbossatx/jts/InboundTransactionCurrentImple.java
- ArjunaJTS/integration/src/main/java/org/jboss/iiop/tm/InboundTransactionCurrent.java
https://issues.redhat.com/browse/JBTM-3698
NO_TEST 
I followed Wildfly implementation https://github.com/wildfly/wildfly/tree/main/transactions/src/main/java/org/jboss/iiop/tm  and I kept the original package (org.jboss.iiop.tm) used in wildfly for the new interface created InboundTransactionCurrent (previously present in dependency jboss-corba-ots-spi).
> Remove jboss-corba-ots-spi dependency

- ArjunaCore/arjuna/pom.xml
- ArjunaCore/arjunacore/pom.xml
- ArjunaJTA/narayana-jta/pom.xml
- ArjunaJTS/narayana-jts-idlj/pom.xml
- narayana-full/pom.xml
- pom.xml
make the javadoc-maven-plugin work with jakarta
some jakarta dependencies need to be excluded from javadoc because jdk modularity:
`[ERROR] Exit code: 1 - ~/narayana/narayana-full/target/distro-javadoc-sources/jakarta.xml.bind-api-4.0.0-sources/module-info.java:18: error: module not found: jakarta.activation
[ERROR]     requires transitive jakarta.activation;
[ERROR]                                ^
[ERROR] error: cannot access module-info
[ERROR]   cannot resolve modules`
jfree dependency update
> [JBTM-3588] make the javadoc-maven-plugin work with jakarta

- rts/lra/test/crash/src/test/java/io/narayana/lra/arquillian/resource/LRAListener.java
- scripts/hudson/narayana.sh
revert commit 2f453c6c1badf53fbae345d88c9fb9a4c15842b0 "2f453c6c1badf53fbae345d88c9fb9a4c15842b0" because it was  needed in order to produce a release for quarkus. 
This PR's goal is to build again wildfly application server from wildfly main repo 
The wildfly source used is https://github.com/jbosstm/jboss-as/pull/87
> Revert "wildfly-jdk17 use 27.0.0.Alpha1 for WildFly testing"

- narayana-full/src/main/assembly/bin.xml
- pom.xml
- rts/at/tx/pom.xml
- rts/pom.xml
Given that sra and lra use an old version of Quarkus on this branch, they are being disabled from the build.
A later version of Byteman is used.
The Undertow dependencies and not directly added (`master` does not add them either - https://github.com/jbosstm/narayana/blob/master/rts/at/tx/pom.xml)
!JACOCO !AS_TESTS !XTS !RTS (these should use the app server but WildFly 23.x (https://github.com/jbosstm/narayana/blob/5.11/scripts/hudson/narayana.sh#L393) is no longer maintained. !LRA (it downloads the latest nightly)
> 5.11 updates

- scripts/hudson/narayana.sh
Replaced `git` with `https` when using `git clone`
NO_TEST
> [SCRIPT_ONLY] Replaced git with https when 'git clone'

- ArjunaJTS/idl/idlj-openjdk/pom.xml
Addresses [JBTM-3716](https://issues.redhat.com/browse/JBTM-3716)
JDK17 JACOCO
!CORE !TOMCAT !AS_TESTS !RTS !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3716 - The JACOCO axis (i.e. code coverage) fails because of the execution order of maven plugins

- osgi/README.md
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/ObjStoreBrowserService.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/AttachCommand.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/DeleteCommand.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/DetachCommand.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/ForgetCommand.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/ListCommand.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/ProbeCommand.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/SelectCommand.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/TypesCommand.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/Activator.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/ObjStoreBrowserImpl.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/OsgiServer.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/OsgiTransactionManager.java
- osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/PlatformTransactionManagerImple.java
- osgi/jta/src/test/java/org/jboss/narayana/osgi/jta/OSGiJTATest.java
https://issues.redhat.com/browse/JBTM-3719
Deprecated OSGi module in Narayana project. Release 6.x will not include this module.
NO_TESTS
> [JBTM-3719] Deprecate OSGi module

- ArjunaJTA/jta/classes/com/arjuna/ats/jta/TransactionManager.java
Fix proposal for https://issues.redhat.com/browse/JBTM-3723
> JBTM-3723 Remove contention point on TransactionManager#transactionManager

- ArjunaJTA/jta/pom.xml
- rts/lra/test/pom.xml
- rts/lra/test/tck/pom.xml
Addresses [JBTM-3673](https://issues.redhat.com/browse/JBTM-3673)
To test:
JDK17 LRA AS_TESTS RTS 
Passed
!XTS !JACOCO !JDK11 !CORE !TOMCAT !QA_JTA !QA_JTS_OPENJDKORB PERF !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3673] Removed maven profile jdk17 and updated Arquillian dependencies

- pom.xml
Our smallrye dependency is way out of date. I have upgraded it to match what quarkus use but note that we only use it in the `cdi` module and even there the code path that could potentially use it is never exercised
CORE
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle
> upgrade smallrye-converter-api dependency

- qa/pom.xml
- rts/lra/pom.xml
removing hamcrest-library, this artifact was moved to:
org.hamcrest » hamcrest 2.2
Using hamcrest version 2.2
CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS QA_JTA QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle
> removing hamcrest-library

- ArjunaJTA/cdi/pom.xml
- pom.xml
https://issues.redhat.com/browse/JBTM-3751
Get rid of Jakarta transformation (variant of the artifact with -jakarta suffix) - instead use real Jakarta-namespaces-ready version.
CORE AS_TESTS RTS LRA XTS
!TOMCAT !JACOCO !QA_JTA !QA_JTS_OPENJDKORB !PERF !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3751] Upgrade org.jboss.invocation:jboss-invocation to 2.0.0.Final

- rts/lra/README.adoc
- rts/lra/coordinator/src/main/resources/META-INF/microprofile-config.properties
- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/client/LRAAsyncIT.java
https://issues.redhat.com/browse/JBTM-3753
Make the concurrency of the LRA coordinator start method (added the microprofile-config.properties)
Added a test in lra-test-basic
Added a README.md in LRA module
JDK17
CORE !TOMCAT AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle
> [JBTM-3753] Make the concurrency of the LRA coordinator start method

- pom.xml
Issue: https://issues.redhat.com/browse/JBTM-3759
JDK17 QA_JTA QA_JTS_OPENJDKORB JACOCO
> [JBTM-3759] Missing version in the bom for dependency log4j-core

- qa/pom.xml
This PR is a quick fix to replace `hamcrest-core` to `hamcrest`. I haven't raised a JIRA but let me know if you think one is needed. Thanks
JDK17 CORE QA_JTA QA_JTS_OPENJDKORB JACOCO
!TOMCAT !AS_TESTS !RTS !XTS !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle
Note: I have used @moulalis' changes from #2097 to compile QA. As a consequence, if my PR passes all test axis, #2097 can be merged
> [FIX_DEPENDENCY] replaced hamcrest-core with hamcrest in QA

- qa/tests/src/org/jboss/jbossts/qa/junit/TestGroupBase.java
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS mysql db2 postgres oracle
> JBTM-3768 Keep logs for both runs of emptyObjectStore

- ArjunaJTS/jts/pom.xml
IMPORTANT! At the moment, our CI is not able to trigger test axis automatically. As a result, your PR might take some time to be tested. We apologize for the inconvenience and appreciate your understanding. Thanks.
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS QA_JTA QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS mysql db2 postgres oracle
By default the pull request will run with `JDK11`, if you prefix a `!` to `JDK11` then it will not run with `JDK11`.
By …
> Don't include the jbossts-properties.xml in the test-jar

- narayana-bom/pom.xml
- rts/at/tx/src/main/resources/META-INF/services/jakarta.ws.rs.ext.Providers
Related to Jira issue: https://issues.redhat.com/browse/JBTM-3462
Quarkus does not inject providers from external library by default (https://quarkus.io/guides/cdi-reference). In order to inject them the validation service provider is needed: https://docs.jboss.org/resteasy/docs/6.2.2.Final/userguide/html_single/index.html#d5e4828
CORE RTS LRA
> SRA and quarkus

- narayana-bom/pom.xml
Removal of jboss-transaction-spi-jakarta (old and not used), the already present and jakarta native dependency is named jboss-transaction-spi
> Removal of jboss-transaction-spi-jakarta

- ArjunaJTA/jta/pom.xml
- ArjunaJTA/jta/src/test/resources/arquillian.xml
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/integration/CMRIntegrationTest.java
- narayana-bom/pom.xml
- pom.xml
- scripts/hudson/narayana.sh
This PR addresses [JBMT-2524](https://issues.redhat.com/browse/JBTM-2524)
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS
> [JBTM-2524] Added a new test to check CMR records and solved JBTM-2524

- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/FailAfterPrepareBase.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/PerformanceTestCommitMarkableResource.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResource.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceFailActivate.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceFailAfterCommit.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceFailAfterCommitOrphan.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceFailAfterPrepareTwoXAResources.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceGCFromCrashAfterCommit.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceMultiEnlist.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceReturnUnknownOutcomeFrom1PCCommit.java
- pom.xml
https://issues.redhat.com/browse/JBTM-3736
Update from 1.4.* to 2.* h2 dependency
From h2 version 1.4.198 MVCC setting is removed, MVStore uses row-level locks and PageStore uses table-level locks unconditionally.
for more details see https://github.com/h2database/h2database/releases/tag/version-1.4.198
CORE QA_JTA DB_TESTS
> [Jbtm 3736] Upgrade h2 dependency

- rts/at/tx/src/main/java/org/jboss/jbossts/star/resource/RESTRecord.java
- rts/at/tx/src/main/java/org/jboss/jbossts/star/service/TMApplication.java
From Jakarta EE cdi specification:
_If a bean class does not explicitly declare a constructor using @Inject, the constructor that accepts
no parameters is the bean constructor_.
This is needed only for bean classes (i.e. annotated as @ApplicationScoped ) and the TMApplication is not annotated. However it is possible that a project uses 'all' as bean-discovery-mode and 'not having a no-arg constructor or a constructor with @Inject annotation' might be a problem. Therefore I recommend having a no-arg constructor  and/or an @Inject constructor. 
related issue is https://github.com/eclipse/lsp4jakarta/issues/191
Note 1: The existing constructor cannot be annotated with @Inject because the parameters must be injectable as well according to the …
> Declare no-arg constructor to TMApplication

- rts/at/tx/src/main/java/org/jboss/jbossts/star/service/TMApplication.java
CORE
After my last PR the CI job failed due to a checkstyle error. Removing the trailing space.
See failure here: https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/narayana/PROFILE=CORE,jdk=openJDK11,label=jnlp-agent/160/console
> Removing trailing space

- ArjunaCore/arjuna/pom.xml
- ArjunaCore/arjunacore/pom.xml
- ArjunaJTA/cdi/pom.xml
- ArjunaJTA/narayana-jta/pom.xml
- ArjunaJTA/spi/pom.xml
- ArjunaJTS/idl/idlj-openjdk/pom.xml
- ArjunaJTS/jtax/pom.xml
- ArjunaJTS/jts/pom.xml
- ArjunaJTS/narayana-jts-idlj/pom.xml
- ArjunaJTS/orbportability/pom.xml
- XTS/localjunit/pom.xml
- compensations/pom.xml
- narayana-bom-test/pom.xml
- narayana-bom/pom.xml
- narayana-full/pom.xml
- pom.xml
- qa/pom.xml
- rts/at/bridge/pom.xml
- rts/at/integration/pom.xml
- rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/jandex/JandexAnnotationResolver.java
- rts/lra/test/basic/pom.xml
- rts/lra/test/pom.xml
- rts/lra/test/tck/pom.xml
- rts/pom.xml
- rts/sra/pom.xml
- txbridge/pom.xml
- vertx/module/pom.xml
https://issues.redhat.com/browse/JBTM-3735
As discussed on Zulip (https://narayana.zulipchat.com/#narrow/stream/323715-developers/topic/JBTM-3735.20Create.20narayana.20boms/near/359649317)
Properties specified in BOMs are not inherited as properties in root pom. So all occurrences of properties in submodules were deleted except the followings:
- plugin properties (these properties are still in root pom)
- root pom profile properties  (these properties are still in root pom)
- properties read in Java files with the Maven resolver (i.e. https://github.com/jbosstm/narayana/blob/7369ddc132d0b52162de23f64e89fe6952693a93/XTS/localjunit/WSTX11-interop/src/test/java/com/jboss/transaction/txinterop/interop/WarDeployment.java#L75 and https://github.com/jbosstm/narayana/blob/7369ddc132d0b52162de23f64 …
> [JBTM-3735] Move properties to BOMs

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/StateManager.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/TwoPhaseCoordinator.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/LogWriteStateManager.java
- XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/sagas/arjunacore/BACoordinator.java
- XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/sagas/arjunacore/ParticipantRecord.java
- XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/twophase/arjunacore/ATCoordinator.java
https://issues.redhat.com/browse/JBTM-3734
Replaced synchronized blocks with reentrantlocks as advised in JEP 425 to support virtual threads.
CORE
Edit:
The synchronized parts were replaced that caused thread pinnings in my own limited tests. These events occured at transaction start and end. To make locking consistent, all synchronized(this) and non-static synchronized methods were replaced in all subclasses of `StateManager`.  Additionally, I changed the `_syncLock` to be a `ReentrantLock` in `TwoPhaseCoordinator`. 
This should be enough for basic virtual thread work, although many other subclasses of `StateManager` contain different `synchronized(someCustomLock)` synchronizations, which will need to be investigated if someone hits thread pinnings on hot paths again.
> JBTM-3734 Replace synchronized with JUCL

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/utils/ThreadUtil.java
A minor additional fix for the ThreadUtil to use a lock instead of synchronized.
After `JtaContextProvider.resumeTransaction`, the `WeakHashMap` sometimes blocks the carrier threads when accessing a queue due to the synchronized block in `ThreadUtil`, see strack trace below (<== monitors:1). I found no places where there is a monitor used on ThreadUtil.class in any other place.
`
Thread[#264,ForkJoinPool-1-worker-16,5,CarrierThreads]
java.base/java.lang.VirtualThread$VThreadContinuation.onPinned(VirtualThread.java:183)
java.base/jdk.internal.vm.Continuation.onPinned0(Continuation.java:398)
java.base/jdk.internal.vm.Continuation.yield0(Continuation.java:390)
java.base/jdk.internal.vm.Continuation.yield(Continuation.java:357)
java.base/java.lang.VirtualThread.yieldContinuation(VirtualThread. …
> JBTM-3734 Replace synchronized with JUCL in ThreadUtil

- pom.xml
- rts/lra/test/tck/pom.xml
Update microprofile-lra-api and microprofile-lra-tck from 2.0-RC1 to 2.0
[JBTM-3743] jdk17 profile can be removed now that MP LRA TCK uses jdk17 compatible Arquillian version
CORE  RTS  LRA  JDK17
> Update microprofile-lra dependencies

- SECURITY.md
https://issues.redhat.com/browse/JBTM-3800
Update to include the email address to the community to use for reporting security related issues.
> New procedure for reporting security issues

- narayana-bom/pom.xml
openjdk-orb is already present in BOM and it is the one used in Narayana, which is already jakarta namespaced.
> remove unused openjdk-orb-jakarta dependency

- pom.xml
https://issues.redhat.com/browse/JBTM-3828 - Backport the upgrade to microprofile lra version to 2.0
The SHA being backported is 86c5d55e3566b994d36c2b80f285be60438b4a70
CORE !TOMCAT AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres
> Update microprofile lra version to 2.0

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/TransactionReaper.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/coordinator/ReaperElement.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/coordinator/ReaperElementManager.java
- ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/reaper/ReaperTestCase3.java
- ArjunaJTS/jtax/pom.xml
See https://issues.redhat.com/browse/JBTM-3830 - this ensures it takes more than a spurious wakeup for shutdown to continue.
I still need to also confirm that we're not entirely missing the removal in this case as well.
CORE PERFORMANCE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !LRA !DB_TESTS !mysql !db2 !postgres !oracle
By default the pull request will run with `JDK11`, if you prefix a `!` to `JDK11` then it will not run with …
> JBTM-3830 ensure that shutdown won't hang due to missed notification

- pom.xml
CORE TOMCAT! AS_TESTS! RTS! JACOCO! XTS! QA_JTA! QA_JTS_OPENJDKORB! PERFORMANCE! LRA! DB_TESTS!
I couldn't find the release notes of nexus-staging-maven-plugin releases, but the older version appeared not to be compatible with jdk17
> Update nexus-staging-maven-plugin to 1.6.13

- narayana-full/pom.xml
https://issues.redhat.com/browse/JBTM-3056
xts-test-servlet does not need to be in the full distro
XTS !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3056 xts-test-servlet is not needed in the full distribution

- code-coverage/pom.xml
https://issues.redhat.com/browse/JBTM-3862
CORE !TOMCAT !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TEST
!JDK11 JDK17
disable coverage-report for compensation because surefire tests are now disabled by default.
> [JBTM-3862] compensation leftover

- ArjunaJTS/integration/pom.xml
- ArjunaJTS/jts/pom.xml
- narayana-bom-test/pom.xml
- narayana-bom/pom.xml
- pom.xml
- rts/at/bridge/pom.xml
- rts/at/integration/pom.xml
https://issues.redhat.com/browse/JBTM-3868
I added a separate commit for the RTS and JTS dependencies on byteman artifacts. I was unable to figure out why those artifacts were treated as special cases so I thought it best to change them in a separate commit.
> JBTM-3868 upgrade and clean up byteman dependency

- pom.xml
https://issues.redhat.com/browse/JBTM-3871
!CORE !TOMCAT !AS_TESTS !RTS  !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS 
As described in spotbugs release notes (https://github.com/spotbugs/spotbugs-maven-plugin/releases/tag/spotbugs-maven-plugin-4.8.0.0) 4.8.x version is compatible with JDK21
JDK17
JACOCO
> Jbtm 3871 Update spotbugs maven plugin to 4.8.3.1

- PULL_REQUEST_TEMPLATE.md
https://issues.redhat.com/browse/JBTM-3871
Enable by default JDK17 for new PRs and enable JDK21 when needed. Update the PULL_REQUEST_TEMPLATE.md
NO_TEST
> [JBTM-3871] Build Narayana with JDK 21

- XTS/localjunit/unit/src/test/java/com/arjuna/wsc/tests/local/ServiceRegistrySecurityManagerTest.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wsc/tests/local/SinglePermissionSecurityManager.java
https://issues.redhat.com/browse/JBTM-3874
Removing tests related to Security Manager, because it is deprecated in JDK17 and will be removed in a future release.
See [JEP 411](https://openjdk.org/jeps/411)
!CORE !TOMCAT !AS_TESTS !RTS JACOCO XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS 
JDK17 JDK21
> [JBTM-3874] The Security Manager is deprecated

- scripts/hudson/narayana.sh
https://issues.redhat.com/browse/JBTM-3867
Avoid running code coverage with JDK11 because it doesn't work when AS tests are not executed
!CORE !TOMCAT !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS 
See failure on CI: https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/narayana/PROFILE=JACOCO,jdk=openJDK11,label=jnlp-agent/260/console
> [JBTM-3867] leftover

- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/OpenAPIIT.java
- rts/lra/test/pom.xml
- scripts/hudson/narayana.sh
https://issues.redhat.com/browse/JBTM-3852 (partial, only enable LRA_TESTS when JACOCO is ran)
!CORE !TOMCAT !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS mysql db2 postgres oracle
!JDK11
> JBTM-3852 Enable code coverage to be ran on LRA_TESTS when JACOCO PROFILE is ran

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARecoveryModuleScanUnitTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARecoveryModuleUnitTest.java
https://issues.redhat.com/browse/JBTM-3879
Patch XA recovery scan cursor handling
Add unit test to test the XAResourceWrapper and Recovery scan status
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS
> [JBTM-3879] Xa recovery scan cursor handling

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/abstractrecords/LastResourceRecord.java
- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAOnePhaseResource.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/lastresource/LastOnePhaseResource.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/lastresource/LastResourceAllowedTestCase.java
https://issues.redhat.com/browse/JBTM-3881
FYI I updated the PR to use rollback if any of the last phase participants produce a ONE_PHASE_ERROR during the prepare phase (see BasicAction#doPrepare) - this is what BasicAction already does in the single last phase resource case (LRCO). Since multiple last resources is inherently unsafe I believe it is valid to switch to rollback for the XA participants if two of the last resources produce a mixed outcome.
> JBTM-3881 Report heuristics for multiple one phase resources

- XTS/localjunit/unit/src/test/java/com/arjuna/wsc/tests/local/ServiceRegistrySecurityManagerTest.java
- XTS/localjunit/unit/src/test/java/com/arjuna/wsc/tests/local/SinglePermissionSecurityManager.java
- pom.xml
- scripts/hudson/narayana.sh
https://issues.redhat.com/browse/JBTM-3890
see comment about 3.0.8 version which backported fix https://issues.redhat.com/browse/JBEAP-27293?focusedId=25042672&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25042672
CORE AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERFORMANCE LRA DB_TESTS mysql db2 postgres oracle
JDK21
> [JBTM-3890] Building Narayana 6.0.2.Final with Java SE 21 fails (jandex plugin version problem)

- rts/at/tx/src/main/java/org/jboss/jbossts/star/resource/RESTRecord.java
- rts/at/tx/src/main/java/org/jboss/jbossts/star/service/TMApplication.java
https://issues.redhat.com/browse/JBTM-3905
backporting commit from main branch:
' Jakarta ee cdi specification bean constructors:
If a bean class does not explicitly declare a constructor using @Inject,
the constructor that accepts
no parameters is the bean constructor'
NOTE: this PR would fix failure shown in quickstart build (https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/btny-pulls-narayana-quickstart-60/4/console), see log https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/btny-pulls-narayana-quickstart-60/4/artifact/rts/at/jta-service/jpa/target/surefire-reports/org.jboss.narayana.quickstart.rest.bridge.inbound.jpa.test.TaskResourceTest-output.txt
> [JBTM-3905]  (6.0.) Declare no-arg constructor to TMApplication

- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/client/LRAAsyncIT.java
https://issues.redhat.com/browse/JBTM-3089
!CORE !AS_TESTS !RTS !JACOCO XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres !oracle
Reports the exception reason for LRA test failures.
> JBTM-3089 Report a reason for test failures

- CONTRIBUTING.md
Whilst reviewing our contributor guidelines I noticed that the guidelines should be more prominent so I have moved them (I didn't change the existing text) into the first paragraph of the "Before you contribute" section.
I also explicitly drew out out/added our code of conduct expectations using the text:
```
We expect all contributors and users to follow our [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct/) when communicating through project channels. These include, but are not limited to: chat, issues, code.
```
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS !mysql !db2 !postgres !oracle
Pull requests build and run with JDK11 and JDK17. Add the prefix `!` to disable these defaults. Include the text `JDK21` …
> hacktoberfest Clarify code of conduct expectations

- ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/xa/JTATest.java
- ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
- ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/xa/JTSTest.java
[JBTM-3725](https://issues.redhat.com/browse/JBTM-3725) (and partially JBTM-3843)
CORE !AS_TESTS !RTS !JACOCO !XTS QA_JTA QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS
> [JBTM-3725] Invoking rollback is not needed on XA_RB*

- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/RecoveryCoordinator.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATestBase.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/tools/osb/mbean/ObjStoreBrowserLRATest.java
- rts/lra/service-base/src/main/java/io/narayana/lra/LRAConstants.java
- rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
- rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/api/CoordinatorApiIT.java
https://issues.redhat.com/browse/JBTM-3929
This PR fixes a problem with the recovery url associated with each participant that participates in an LRA
!CORE !AS_TESTS !RTS! JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres oracle
> JBTM-3929 Participant failover support

- ArjunaJTA/jdbc/pom.xml
- XTS/localjunit/pom.xml
- pom.xml
- rts/at/tx/pom.xml
- rts/at/webservice/pom.xml
https://issues.redhat.com/browse/JBTM-3939
[Migrating the Deprecated forkMode Parameter to forkCount and reuseForks](https://github.com/jbosstm/narayana/commit/c462467b523add7ffe7200e478df02f56a959aed) as per https://maven.apache.org/surefire-archives/surefire-2.20.1/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html
Upgrade nexus-stagin-maven-plugin to 1.7.0
> Migrate the Deprecated forkMode Parameter to forkCount and reuseForks and JBTM-3939 Update nexus-staging-maven-plugin to 1.7.0

- rts/lra/coordinator/pom.xml
- rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/BytemanHelper.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATestBase.java
https://issues.redhat.com/browse/JBTM-3331 (Test for early timeouts during enlistment)
Includes three commits:
- one to add the test,
- a second one to add byteman support, and
- another to fix the original test and to include a bug fix
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres !oracle !JDK17
> JBTM-3331 Test for early timeouts during enlistment

- rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
https://issues.redhat.com/browse/JBTM-3330
I think this issue is outdated, but to be sure I added two tests to verify the case is covered in tests.
CORE !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS
> JBTM-3330 Nested closed LRA is kept in Closing state which is breaking the LRA state model

- narayana-bom-test/pom.xml
- rts/at/tx/pom.xml
- rts/at/tx/src/main/java/org/jboss/jbossts/star/service/TMApplication.java
- rts/at/tx/src/test/java/org/jboss/jbossts/star/test/BaseTest.java
Starting from quarkus 3.7 the minimum JDK version is 17.
Because the narayana supports JDK 11 we need to decide if we want to create jdk maven profiles or remove quarkus dependency from Narayana codebase.
I would prefer to move quarkus dependencies in quickstart and use maven jdk profile there if needed.
CORE !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS
> Quarkus dependency removal

- narayana-bom/pom.xml
- pom.xml
Update plugin dependencies
jboss.logmanager>2.1.19.Final
jboss-logging-processor>3.0.2.Final
jboss-logging>3.6.1.Final
jboss.openjdk-orb>10.1.0.Final
jboss.ws>3.0.0.Final
I removed the plugin version so that it uses the versions defined in the jboss-parent.
CORE AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS
> Update jboss dependencies

- ArjunaCore/arjuna/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_FailTest.btm
Test should fail when there are too many PeriodicRecover's passes
> [JBTM-3894] Test should fail when there are too many PeriodicRecover's passes

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
- ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/ObjStoreBrowserTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/tools/ObjStoreBrowserTest.java
Backport of JBTM-3859 (clear MBean cache before probing)
CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS !mysql !db2 !postgres !oracle
> 5.11 jbtm 3859

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
- ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/ObjStoreBrowserTest.java
- ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/tools/ObjStoreBrowserTest.java
Backport of JBTM-3859 (clear MBean cache before probing)
CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS !mysql !db2 !postgres !oracle
> JBTM-3859 clear MBean cache before probing

- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/AbstractRecord.java
- ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
- ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/resources/ExtendedResourceRecord.java
https://issues.redhat.com/browse/JBTM-3881
CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS !mysql !db2 !postgres !oracle !JDK21
ExtendedResourceRecord [caches the record type](https://github.com/jbosstm/narayana/blob/7.2.0.Final/ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/resources/ExtendedResourceRecord.java#L235) (type_id) which is causing an issue when it is called early in the prepare phase. This fix adds a method to clear the cached value so that the record is treated as a [RecordType.OTS_ABSTRACTRECORD](https://github.com/jbosstm/narayana/blob/7.2.0.Final/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/RecordType.java#L81) (record type151).
This fix that I have chosen for the QE test failure is not the only possible solution but I …
> JBTM-3881 clear ExtendedResourceRecord cache
