blacktie/wildfly-blacktie/build/server-provisioning.xml
pom.xml

!MAIN !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB

JBTM-2327 wildfly-blacktie does not contain jars in the release

---

scripts/hudson/narayana.bat

!QA_JTA !QA_JTS_JACORB !BLACKTIE !XTS

Updated to run the unit tests on windows

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/CrashAfterResourcesCommitTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/TestXAResourceRecordWrappingPlugin.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/TestXAResourceWrapper.java

JBTM-860. Use XAResourceWrapper metadata for assume complete

---

blacktie/hybrid/src/main/cpp/HybridSocketEndpointQueue.cxx

!MAIN !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB
NO_TEST

JBTM-2090 SIGPIPE issue

---

scripts/hudson/benchmark.sh
scripts/hudson/narayana.sh

PERF  !BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB

[JBTM-2337] Optional regression check on PRs

---

scripts/hudson/benchmark.sh
scripts/hudson/narayana.sh

[JBTM-2347] propagate narayana.sh args to benchmark.sh

---

compensations/src/main/java/org/jboss/narayana/compensations/impl/ParticipantImpl.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensationScoped/CompensationScopedTest.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensationScoped/MyCompensationHandler.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensationScoped/MyConfirmationHandler.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensationScoped/MyTransactionLoggedHandler.java

JBTM-2349. Close CompensationContext only after all participants are done

---

scripts/hudson/benchmark.sh
scripts/hudson/narayana.sh

!XTS !BLACKTIE !QA_JTA !QA_JTS_JACORB !MAIN PERFORMANCE_IMPROVEMENT

JBTM-2347 typo in PR comment text

---

compensations/src/main/java/org/jboss/narayana/compensations/impl/ParticipantInterceptor.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/TxCompensateInterceptor.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/TxConfirmInterceptor.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/TxLoggedInterceptor.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/BasicTest.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensatable/CompensatableBean.java

!PERF !MAIN !BLACKTIE !QA_JTA !QA_JTS_JACORB

JBTM-2353 Compensation handler should not throw exception, if there is no transaction

---

rts/at/integration/pom.xml
rts/at/integration/src/test/java/org/jboss/narayana/rest/integration/test/common/LoggingParticipant.java
rts/at/integration/src/test/java/org/jboss/narayana/rest/integration/test/common/TransactionalService.java
rts/at/integration/src/test/java/org/jboss/narayana/rest/integration/test/integration/AbstractIntegrationTestCase.java
rts/at/integration/src/test/java/org/jboss/narayana/rest/integration/test/integration/BasicIntegrationTestCase.java
rts/at/integration/src/test/java/org/jboss/narayana/rest/integration/test/integration/DistributedRecoveryIntegrationTestCase.java
rts/at/integration/src/test/java/org/jboss/narayana/rest/integration/test/integration/RecoveryIntegrationTestCase.java
rts/at/integration/src/test/resources/arquillian.xml
rts/at/tx/src/main/java/org/jboss/jbossts/star/resource/Transaction.java
rts/at/tx/src/test/java/org/jboss/jbossts/star/test/BaseTest.java
rts/at/tx/src/test/java/org/jboss/jbossts/star/test/CoordinatorTest.java

!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !PERF

JBTM-2356. REST-AT transaction should not be removed, if participant fails

---

blacktie/tx/src/main/cpp/HttpTxManager.cxx
blacktie/tx/src/test/cpp/TestTransactions.cxx

JBTM-2363 Blacktie c++ tx client build build failure

---

blacktie/tx/src/main/cpp/HttpTxManager.cxx

!XTS !QA_JTA !QA_JTS_JACORB !PERF

JBTM-2363 Update to fix the bug of removing the branch

---

scripts/hudson/narayana.sh

[JBTM-2381] Enable XTS trace logging from narayana.sh

---

pom.xml

!PERF !QA_JTA !QA_JTS_JACORB
https://issues.jboss.org/browse/JBTM-2391

JBTM-2391 updated version of WFLY to 10.0.0.Alpha1-SNAPSHOT

---

scripts/hudson/narayana.sh

JACOCO
https://issues.jboss.org/browse/JBTM-2404

JBTM-2404 Include a JACOCO profile

---

build-release-pkgs.xml

NO_TEST
Requires: https://github.com/jbosstm/documentation/pull/31

[JBTM-2393] Enable release profile when building docs

---

pom.xml

!XTS !BLACKTIE !QA_JTA !QA_JTS_JACORB !PERF

JBTM-2414 Upgrade to 10.0.0.Alpha2-SNAPSHOT

---

txframework/pom.xml
txframework/src/test/java/org/jboss/narayana/txframework/functional/ws/ba/bridged/BABridgedTest.java
txframework/src/test/java/org/jboss/narayana/txframework/functional/ws/ba/participantCompletion/BAParticipantCompletionTest.java

!PERF !MAIN !QA_JTA !QA_JTS_JACORB !BLACKTIE

[JBTM-2406] Enable race condition byteman rules

---

ArjunaCore/arjuna/pom.xml
narayana-full/pom.xml
pom.xml

JBTM-2424 Only depend on hornetq-journal

---

pom.xml

!BLACKTIE !PERF !XTS !QA_JTA !QA_JTS_JACORB

JBTM-2425 Use latest wildfly

---

ArjunaJTS/jtax/pom.xml
ArjunaJTS/jts/pom.xml
ArjunaJTS/orbportability/pom.xml
qa/run-tests.xml

!PERF !XTS !BLACKTIE !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB

JBTM-2304 don't copy openjdk-orb to build directory

---

pom.xml

JBTM-2429 disable java debugger

---

osgi/pom.xml

JBTM-2431 Make sure arq dependency versions are compatible

---

pom.xml

JBTM-2425 Upgrade to wildfly 10.0.0.Alpha4-SNAPSHOT

---

ArjunaJTS/jtax/pom.xml
ArjunaJTS/jts/pom.xml
pom.xml

JBTM-2430 Upgrade openjdk-orb jar

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/util/JMXServer.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSOSBTestBase.java

JBTM-2308 fix windows path issue

---

ArjunaJTA/jta/pom.xml
ArjunaJTS/jts/pom.xml

JBTM-2440 Disable byteman on the IBM J9 VM

---

ArjunaJTA/jta/pom.xml
ArjunaJTS/jts/pom.xml

NO_TEST
This reverts commit 55098aa7664e52414987e07ba8ad70b4eba56da0.

Revert "JBTM-2440 Disable byteman on the IBM J9 VM"

---

pom.xml

!BLACKTIE !QA_JTA !QA_JTS_JACORB !PERF

JBTM-2448 Upgrade wildfly to 10.0.0.Alpha5-SNAPSHOT

---

ArjunaCore/arjuna/pom.xml
ArjunaJTA/jdbc/pom.xml
ArjunaJTA/jta/pom.xml
ArjunaJTS/integration/pom.xml
ArjunaJTS/jts/pom.xml
XTS/localjunit/pom.xml

!XTS !BLACKTIE !QA_JTA !QA_JTS_JACORB !MAIN !PERF !QA_JTS_JDKORB

JBTM-2440 Disable BMUnitRunner tests with ibmjdk

---

XTS/WS-T/dev/src/com/arjuna/wst11/messaging/engines/CoordinatorEngine.java

!MAIN !BLACKTIE !PERF !QA_JTA !QA_JTS_JACORB

[JBTM-2426] Check if timerTask is not null before calling equals

---

ArjunaJTS/jts/classes/com/arjuna/ats/jts/TransactionServer.java

https://issues.jboss.org/browse/JBTM-2470
NO_TEST

Start embedded RM if -recovery is passed to transaction sever

---

narayana-full/pom.xml

https://issues.jboss.org/browse/JBTM-2455
!QA_JTA !QA_JTS_JACORB !BLACKTIE !XTS !PERF

JBTM-2455 Updated to re-enable the generation of the javadocs

---

compensations/pom.xml
compensations/src/main/java/org/jboss/narayana/compensations/impl/BeanManagerUtil.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/beanManager/BeanManagerTest.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/beanManager/BeanManagerUtilTestLocal.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/beanManager/BeanManagerUtilTestWeld.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/beanManager/DummyBean.java
pom.xml
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-2225
!MAIN !PERF !BLACKTIE !QA_JTA !QA_JTS_JACORB

[JBTM-2225] Update BeanManagerUtil not to use JNDI

---

pom.xml

!XTS !BLACKTIE !QA_JTA !QA_JTS_JACORB !PERF !QA_JTS_JDKORB

JBTM-2454 Upgrade weld dependency

---

blacktie/pom.xml
blacktie/wildfly-blacktie/subsystem/src/main/java/org/wildfly/extension/blacktie/BlacktieSubsystemAdd.java
blacktie/wildfly-blacktie/subsystem/src/main/java/org/wildfly/extension/blacktie/BlacktieSubsystemExtension.java

https://issues.jboss.org/browse/JBTM-2503
!XTS !QA_JTA !QA_JTS_JACORB !MAIN !PERF

JBTM-2503 Update to remove the deprecated api in the wildfly-blacktie

---

blacktie/wildfly-blacktie/feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/blacktie/main/module.xml
blacktie/wildfly-blacktie/subsystem/pom.xml
blacktie/wildfly-blacktie/subsystem/src/main/java/org/wildfly/extension/blacktie/BlacktieSubsystemAdd.java
blacktie/wildfly-blacktie/subsystem/src/main/java/org/wildfly/extension/blacktie/BlacktieSubsystemDefinition.java
blacktie/wildfly-blacktie/subsystem/src/main/java/org/wildfly/extension/blacktie/BlacktieSubsystemParser.java
blacktie/wildfly-blacktie/subsystem/src/main/java/org/wildfly/extension/blacktie/configuration/Attribute.java
blacktie/wildfly-blacktie/subsystem/src/main/resources/org/wildfly/extension/blacktie/LocalDescriptions.properties
blacktie/wildfly-blacktie/subsystem/src/main/resources/schema/wildfly-blacktie_1_0.xsd

https://issues.jboss.org/browse/JBTM-2499
!XTS !QA_JTA !QA_JTS_JACORB !MAIN !PERF

JBTM-2499 Update wildfly-blacktie to add the dependecy of the activemq

---

scripts/hudson/narayana.sh

Update narayana.sh to work on Mac

---

ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/jts/TransactionManagerService.java

!XTS !BLACKTIE !QA_JTA  !QA_JTS_JACORB !PERF 
https://issues.jboss.org/browse/JBTM-2514

JBTM-2514 Invoke orb shutdown when stoping the txn service

---

ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/jts/ExternalORBWrapper.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/jts/RecoveryManagerService.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/jts/TransactionManagerService.java

!XTS !BLACKTIE !QA_JTA !QA_JTS_JACORB !PERF
https://issues.jboss.org/browse/JBTM-2514
This PR follows on from https://github.com/jbosstm/narayana/pull/911 since we also need to avoid shutting down the external orb when shutting down our own

JBTM-2514 Do not shutdown external orb

---

blacktie/pom.xml
blacktie/wildfly-blacktie/feature-pack/src/main/resources/configuration/examples/subsystems-blacktie.xml

!XTS !MAIN !QA_JTA !QA_JTS_JACORB !PERF
https://issues.jboss.org/browse/JBTM-2521

Updated batch config to use batch-jberet.xml

---

ArjunaJTA/jta/src/test/resources/standalone-cmr.xml

https://issues.jboss.org/browse/JBTM-2524
!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !PERF

JBTM-2524 Update the cmr config

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java
pom.xml

https://issues.jboss.org/browse/JBTM-2523
!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !PERF

JBTM-2523 Upgrade the activemq-artimes to 1.1.0-wildfly-6

---

scripts/release/README.md
scripts/release/__init__.py
scripts/release/pre_release.py
scripts/release/update_jira.py
scripts/release/utils/__init__.py
scripts/release/utils/http_helper.py
scripts/release/utils/input_helper.py
scripts/release/utils/jira_helper.py

https://issues.jboss.org/browse/JBTM-2526
NO_TEST

[JBTM-2526] Create pre-release checking script

---

scripts/hudson/narayana.sh

Necessary for running this script on different platforms for QE perspectives.
!BLACKTIE !MAIN !PERF

[JBTM-2533] Changed 'scripts/hudson/narayana.sh' script to skip '-i' option of used 'sed' commands. 

---

XTS/WS-C/dev/src/com/arjuna/webservices/logging/wscI18NLogger.java
XTS/WS-C/dev/src/com/arjuna/webservices11/util/MapBuilderAction.java
XTS/WS-C/dev/src/com/arjuna/webservices11/util/PrivilegedMapBuilderFactory.java
XTS/WS-C/dev/src/com/arjuna/webservices11/util/PrivilegedServiceFactory.java
XTS/WS-C/dev/src/com/arjuna/webservices11/util/PrivilegedServiceHelper.java
XTS/WS-C/dev/src/com/arjuna/webservices11/util/ServiceAction.java
XTS/WS-C/dev/src/com/arjuna/webservices11/util/ServiceRegistryAction.java
XTS/WS-C/dev/src/com/arjuna/webservices11/wsaddr/JAXBContextUnmarshalAction.java
XTS/WS-C/dev/src/com/arjuna/webservices11/wsaddr/NativeEndpointReference.java
XTS/WS-C/dev/src/com/arjuna/webservices11/wsaddr/NativeEndpointReferenceContextAction.java
XTS/WS-C/dev/src/com/arjuna/webservices11/wscoor/client/ActivationCoordinatorClient.java
XTS/WS-C/dev/src/com/arjuna/webservices11/wscoor/client/WSCOORClient.java
XTS/WS-C/dev/src/com/arjuna/wsc11/RegistrationCoordinator.java
XTS/WS-T/dev/src/com/arjuna/webservices11/wsarjtx/client/WSARJTXClient.java
XTS/WS-T/dev/src/com/arjuna/webservices11/wsat/client/WSATClient.java
XTS/WS-T/dev/src/com/arjuna/webservices11/wsba/client/WSBAClient.java
XTS/WSTX/classes/com/arjuna/mw/wst11/common/CoordinationContextAction.java
XTS/WSTX/classes/com/arjuna/mw/wst11/common/CoordinationContextHelper.java

https://issues.jboss.org/browse/JBTM-2519
!MAIN !BLACKTIE !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTA !PERF

[JBTM-2519] XTS privileged actions

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java

https://issues.jboss.org/browse/JBTM-2550
!BLACKTIE !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

JBTM-2550 ClassNotFoundException when restore_state from the object store during recovering

---

ArjunaCore/arjuna/pom.xml
ArjunaJTA/jdbc/pom.xml
ArjunaJTA/jta/pom.xml
ArjunaJTA/spi/pom.xml
ArjunaJTS/narayana-jts-ibmorb/pom.xml
ArjunaJTS/narayana-jts-idlj/pom.xml
ArjunaJTS/narayana-jts-jacorb/pom.xml
XTS/localjunit/WSTFSC07-interop/pom.xml
XTS/localjunit/crash-recovery-tests/pom.xml
XTS/localjunit/disabled-context-propagation/pom.xml
XTS/localjunit/pom.xml
code-coverage/pom.xml
compensations/pom.xml
ext/pom.xml
pom.xml
scripts/hudson/narayana.sh
txframework/pom.xml

https://issues.jboss.org/browse/JBTM-2532
!BLACKTIE !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB

[JBTM-2532] Enable code coverage for XTS

---

osgi/jta/pom.xml
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/Activator.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/OsgiServer.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/OsgiTransactionManager.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/PlatformTransactionManagerImple.java
osgi/jta/src/main/resources/jbossts-properties.xml
osgi/jta/src/test/java/org/jboss/narayana/osgi/jta/OSGiJTATest.java
osgi/jta/src/test/resources/etc/org.jboss.narayana.cfg
osgi/jta/src/test/resources/etc/startup.properties
osgi/jta/src/test/resources/jbossts-properties.xml
osgi/pom.xml

!XTS !BLACKTIE !PERF !QA_JTA !QA_JTS_JDKORB

OSGi support improvements

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/jdbc/JDBCImple_driver.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/JTATransactionLogXAResourceOrphanFilter.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/TestJDBCAccess.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/TestJDBCStoreOffline.java

https://issues.jboss.org/browse/JBTM-2569
!PERF

JBTM-2569 Treat a failure to find a log as if the log existed

---

build.bat

https://issues.jboss.org/browse/JBTM-2576
PROFILE=MAIN

Use mvn.cmd instead of mvn.bat in build.bat

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/SubordinateTransaction.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/SubordinateAtomicAction.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/TransactionImple.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/subordinate/SubordinateTestCase.java
ArjunaJTS/integration/pom.xml
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/LocalServer.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/ProxyXAResource.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/ServerImpl.java
ArjunaJTS/integration/src/test/resources/fail2pc.btm
ArjunaJTS/integration/src/test/resources/leave-subordinate-orphan2.btm
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/TransactionImple.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/subordinate/SubordinateTestCase.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/interposition/coordinator/ServerTransaction.java

https://issues.jboss.org/browse/JBTM-2579
!BLACKTIE !PERF !XTS !QA_JTS_JDKORB !QA_JTS_JACORB !QA_JTA

JBTM-2579 Throw XAException in XATerminator::commit if a wrapped resource fails transiently

---

ArjunaJTS/integration/pom.xml

!BLACKTIE !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !XTS

JBTM-2582 Re-enable SimpleIsolatedServers

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/SubordinateJTAXAResourceOrphanFilter.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/SubordinateTransaction.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/SubordinateAtomicAction.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/TransactionImple.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/subordinate/SubordinateTestCase.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/TestResource.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/TestResourceRecovery.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/LocalServer.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/ProxyXAResource.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/ServerImpl.java
ArjunaJTS/integration/src/test/resources/fail2pc.txt
ArjunaJTS/integration/src/test/resources/leave-subordinate-orphan2.txt
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/TransactionImple.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/subordinate/SubordinateTestCase.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/interposition/coordinator/ServerTransaction.java

…the subordinate atomic action matches the Xid from the remote server as it won't
!QA_JTA !QA_JTS_JACORB !XTS

JBTM-2575 JBTM-2579

---

ArjunaJTA/cdi/pom.xml
ArjunaJTA/jta/pom.xml
XTS/localjunit/pom.xml
code-coverage/pom.xml
compensations/pom.xml
rts/at/bridge/pom.xml
rts/at/integration/pom.xml
scripts/hudson/narayana.sh
txbridge/pom.xml
txframework/pom.xml

https://issues.jboss.org/browse/JBTM-2572
!BLACKTIE !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_IBMORB !PERF
!XTS !MAIN

[JBTM-2572] Enable code coverage for the rest of the Arquillian tests

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalEnvironmentBeanMBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java
pom.xml

https://issues.jboss.org/browse/JBTM-2599
!PERF !QA_JTA !QA_JTS_JDKORB !QA_JTS_JACORB !XTS !BLACKTIE

JBTM-2599 - Update activemq-artemis to 1.1.0.wildfly-010

---

ArjunaJTA/cdi/tests/resources/arquillian.xml
XTS/localjunit/WSTFSC07-interop/src/test/resources/arquillian.xml
XTS/localjunit/WSTX11-interop/src/test/resources/arquillian.xml
XTS/localjunit/crash-recovery-tests/src/test/resources/arquillian.xml
XTS/localjunit/disabled-context-propagation/src/test/resources/arquillian.xml
XTS/localjunit/unit/src/test/resources/arquillian.xml
rts/at/bridge/src/test/resources/arquillian.xml
rts/at/integration/src/test/resources/arquillian.xml

!QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB !BLACKTIE !PERF !MAIN

[JBTM-2604] Use servlet protocol in arquillian tests

---

ArjunaJTA/jdbc/pom.xml
ArjunaJTS/orbportability/pom.xml
pom.xml
rts/at/tx/pom.xml

https://issues.jboss.org/browse/JBTM-2612
!PERF !QA_JTA !QA_JTS_JDKORB !BLACKTIE !XTS

JBTM-2612 Updated to install the JDBC module

---

pom.xml

This includes various maven plugin version updates and other enhancements
!PERF !QA_JTA !QA_JTS_JDKORB

Update jboss-parent pom 11 -> 19

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java

https://issues.jboss.org/browse/JBTM-2618
!XTS !BLACKTIE !QA_JTA !QA_JTS_JDKORB

JBTM-2618 Improve concurrent behavior of HornetqJournalStore

---

XTS/WSCF/classes/com/arjuna/mw/wscf/logging/wscfI18NLogger.java
XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/twophase/arjunacore/SynchronizationRecord.java

https://issues.jboss.org/browse/JBTM-2610
!MAIN !BLACKTIE !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB

[JBTM-2610] Log exception caught in SynchronizationRecord.beforeComletion

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/ActionStatusService.java
ArjunaCore/txoj/classes/com/arjuna/ats/internal/txoj/recovery/RecoveredTransactionalObject.java

https://issues.jboss.org/browse/JBTM-2625
!BLACKTIE !XTS !PERF

JBTM-2625 If the object store cannot be contacted return INVALID state

---

scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-2603
!MAIN !BLACKTIE !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB
XTS_TRACE=1

[JBTM-2603] Fix XTS trace log enable script and enabled for TXBridge

---

ArjunaJTA/jms/pom.xml
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionClosingSynchronization.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelper.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionClosingSynchronization.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/TransactionHelper.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/TransactionHelperImpl.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/ConnectionClosingSynchronizationTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxyTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/ConnectionProxyTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelperTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/SessionClosingSynchronizationTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/SessionProxyTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/TransactionHelperImplTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/helpers/BytemanHelper.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/helpers/JmsHelper.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/AbstractIntegrationTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/IntegrationTestRuntimeException.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/JmsIntegrationTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/JmsRecoveryIntegrationTests.java
ArjunaJTA/jms/src/test/resources/log4j.properties
ArjunaJTA/pom.xml
pom.xml

https://issues.jboss.org/browse/JBTM-2616
https://issues.jboss.org/browse/JBTM-2617
!QA_JTA !QA_JTS_JDKORB !QA_JTS_JACORB !QA_JTS_IBMORB !XTS !PERF !BLACKTIE

[JBTM-2616] and [JBTM-2617] JMS integration with recovery

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/JTAActionStatusServiceXAResourceOrphanFilter.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XAResourceOrphanFilterTest.java

https://issues.jboss.org/browse/JBTM-2583
!BLACKTIE !PERF !QA_JTA !QA_JTS_JDKORB !XTS
Needs: https://github.com/jbosstm/jboss-as/pull/44

JBTM-2583 Query the action status service in orphan detection

---

qa/tests/src/org/jboss/jbossts/qa/Utils/CrashRecoveryDelays.java
qa/tests/src/org/jboss/jbossts/qa/junit/TaskImpl.java

https://issues.jboss.org/browse/JBTM-2626
!XTS !BLACKTIE  !QA_JTS_JACORB !MAIN !PERF !QA_JTS_JDKORB

JBTM-2626 apply MFACTOR to qa task timeout

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/ExceptionDeferrer.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAOnePhaseResource.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/basic/ExceptionDeferrerTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/xa/JTATest.java

https://issues.jboss.org/browse/JBTM-2636

Deferred throwables backport

---

ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelper.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelperTests.java

https://issues.jboss.org/browse/JBTM-2640
!BLACKTIE !PERF !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB

[JBTM-2640] Add username and password to JmsXAResourceRecoveryHelper

---

ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelper.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelperTests.java

https://issues.jboss.org/browse/JBTM-2638
!BLACKTIE !PERF !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB

[JBTM-2638] Initiate connection in JmsXAResourceRecoveryHelper.getXAResources instead of recover

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/TwoPhaseCoordinator.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/atomicaction/TxStatsUnitTest.java

…during single rollback
!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB
https://issues.jboss.org/browse/JBTM-2643
Upstream for https://github.com/jbosstm/narayana/pull/991 (5.2 branch)

[JBTM-2643] "number-of-application-rollbacks" statistic incremented twice

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java

https://issues.jboss.org/browse/JBTM-2649
!PERF !QA_JTA !QA_JTS_JDKORB !BLACKTIE !XTS

JBTM-2649 Updated to make sure we overwrite the record

---

narayana-release-process.sh

NRP updates

---

compensations/src/main/java/org/jboss/narayana/compensations/impl/BAControler.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/BeanManagerUtil.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/ParticipantImpl.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/local/LocalBAControler.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/local/LocalParticipant.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/remote/RemoteBAControler.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/remote/RemoteParticipant.java

https://issues.jboss.org/browse/JBTM-2647
!MAIN !BLACKTIE !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB

[JBTM-2647] Allow enlisting handlers by instance to BAControler

---

ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionClosingSynchronization.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelper.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionClosingSynchronization.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/TransactionHelperImpl.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java

https://issues.jboss.org/browse/JBTM-2641
!PERF !BLACKTIE !XTS !QA_JTA_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB

[JBTM-2641] Add localisation to JMS module warnings

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java

https://issues.jboss.org/browse/JBTM-2636
!BLACKTIE !QA_JTA !QA_JTS_JACORB !XTS !PERF

JBTM-2636 Only addSuppressed on JDK6

---

osgi/jta/pom.xml

https://issues.jboss.org/browse/JBTM-2657
!XTS !BLACKTIE !QA_JTA !PERF !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

JBTM-2657 Missing narayana-osgi-jta artifact with the release profile

---

osgi/pom.xml

!XTS !BLACKTIE !QA_JTA !PERF !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

JBTM-2657 Update to install the osgi parent pom in the release profile

---

ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/jca/XATerminatorUnitTest.java

https://issues.jboss.org/browse/JBTM-2579
!BLACKTIE !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !PERF !XTS

Added a test to show JTA recovery of XATerminator

---

compensations/src/main/java/org/jboss/narayana/compensations/impl/BAController.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/BAControllerFactory.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensationInterceptorBase.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensationInterceptorMandatory.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensationInterceptorNever.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensationInterceptorNotSupported.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensationInterceptorRequired.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensationInterceptorRequiresNew.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensationInterceptorSupports.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/local/LocalBAController.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/remote/RemoteBAController.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensationScoped/CompensationScopedTest.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensationScoped/CompensationScopedTestLocal.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensationScoped/CompensationScopedTestRemote.java

https://issues.jboss.org/browse/JBTM-2650
Uses: https://github.com/jbosstm/jboss-as/pull/46
!PERF !MAIN !BLACKTIE !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB !QA_JTA

[JBTM-2650] Remove typo from BAControler interface and its implementations

---

qa/tests/src/org/jboss/jbossts/qa/junit/ExecutionWrapper.java

Updated to use the platforms file separator

---

XTS/sar/src/org/jboss/jbossts/xts/initialisation/ParticipantSideInitialisation.java

https://issues.jboss.org/browse/JBTM-2675
!BLACKTIE !QA_JTA !QA_JTS_JDKORB !MAIN !PERF

JBTM-2675 fix participant initialization shutdown

---

compensations/pom.xml
compensations/src/main/java/org/jboss/narayana/compensations/api/CompensatableAction.java
compensations/src/main/java/org/jboss/narayana/compensations/api/CompensatableWork.java
compensations/src/main/java/org/jboss/narayana/compensations/api/EnlistException.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensatableActionImpl.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensatableActionProducer.java
compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensationsCDIExtension.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensatableAction/CompensatableActionTestLocal.java
compensations/src/test/java/org/jboss/narayana/compensations/functional/compensatableAction/CompensatableActionTestRemote.java

https://issues.jboss.org/browse/JBTM-2622
!MAIN !BLACKTIE !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTSIBMORB !PERF

[JBTM-2622] Possible new compensations api

---

narayana-full/pom.xml

https://issues.jboss.org/browse/JBTM-2679
!QA_JTA !QA_JTS_JDKORB !BLACKTIE !PERF !MAIN

[JBTM-2679] narayna-full to contain bits of jbossxts from Narayana build of XTS folder

---

osgi/jta/pom.xml
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/ObjStoreBrowserService.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/AttachCommand.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/DeleteCommand.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/DetachCommand.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/ForgetCommand.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/ListCommand.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/ProbeCommand.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/SelectCommand.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/command/TypesCommand.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/ObjStoreBrowserImpl.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/OsgiServer.java
osgi/pom.xml
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-2624
!XTS !BLACKTIE !QA_JTA !QA_JTS_JDKORB !QA_JTS_JACORB !PERF

JBTM-2624 Update to support the admin commands in the karaf shell

---

ArjunaJTA/narayana-jta/pom.xml
ArjunaJTS/narayana-jts-ibmorb/pom.xml
ArjunaJTS/narayana-jts-idlj/pom.xml
ArjunaJTS/narayana-jts-jacorb/pom.xml

https://issues.jboss.org/browse/JBTM-2691
!XTS !BLACKTIE !PERF

JBTM-2691 Added the JMS jars to the uber jars

---

ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/helpers/JmsHelper.java

!BLACKTIE !XTS !QA_JTA !QA_JTS_JDKORB !PERF

JBTM-2694 Use InVM connector

---

osgi/jta/pom.xml

https://issues.jboss.org/browse/JBTM-2692
!XTS !BLACKTIE !QA_JTA !QA_JTS_JDKORB !QA_JTS_JACORB !PERF

JBTM-2692 Narayana OSGi bundle is missing optional packages

---

pom.xml

JBTM-2665 Bump the jboss-transaction-spi dependency version

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/jdbc/JDBCImple_driver.java

https://issues.jboss.org/browse/JBTM-2696
!PERF !BLACKTIE !QA_JTA !QA_JTS_JDKORB !XTS

JBTM-2696 Added some more logging when read_state fails

---

LICENSE

JBTM-2698 Added a LICENSE file

---

ArjunaJTS/idl/pom.xml
ArjunaJTS/jtax/pom.xml
ArjunaJTS/jts/pom.xml
ArjunaJTS/orbportability/pom.xml
osgi/jta/pom.xml
osgi/jta/src/test/resources/arquillian.xml
osgi/jta/src/test/resources/etc/startup.properties
osgi/pom.xml
scripts/hudson/narayana.sh

!BLACKTIE !XTS !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

JBTM-2689 narayana-osgi-jta integration test does not work with the karaf 4.x

---

ArjunaJTA/jdbc/pom.xml
ArjunaJTA/jdbc/tests/classes/com/hp/mwtests/ts/jdbc/basic/ConnectionImpleTest.java

!BLACKTIE !XTS !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB
https://issues.jboss.org/browse/JBTM-2676

[JBTM-2676] ConnectionImple.close and ConnectionImple.isClosed tests

---

compensations/pom.xml
compensations/src/main/java/org/jboss/narayana/compensations/impl/BeanManagerUtil.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/archive/EarArchiveTestLocal.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/archive/EarArchiveTestRemote.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/archive/TestConfirmationHandler.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/archive/TestService.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/archive/TestServiceClient.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/archive/TestServiceImpl.java
compensations/src/test/java/org/jboss/narayana/compensations/integration/archive/TestServiceService.java
compensations/src/test/resources/test-application.xml
pom.xml

https://issues.jboss.org/browse/JBTM-2704
Depends on https://github.com/jbosstm/jboss-as/pull/47
!MAIN !BLACKTIE !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_IBMORB

[JBTM-2704] Update BeanManagerUtil to work with ear archives

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/jca/XATerminatorUnitTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARRTestResource.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/TestResource.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/TransactionImporterImple.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/common/TestBase.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/jca/XATerminatorImpleUnitTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSOSBTestBase.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSObjStoreBrowserTest.java

https://issues.jboss.org/browse/JBTM-2614
https://issues.jboss.org/browse/JBTM-2708
https://issues.jboss.org/browse/JBTM-2709

4.17 JBTM-2614 JBTM-2708 JBTM-2709

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/jca/XATerminatorUnitTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARRTestResource.java

https://issues.jboss.org/browse/JBTM-2614
https://issues.jboss.org/browse/JBTM-2708
https://issues.jboss.org/browse/JBTM-2709
!XTS !BLACKTIE !PERF !QA_JTA !QA_JTS_JDKORB

master JBTM-2614 JBTM-2708 JBTM-2709

---

blacktie/pom.xml

https://issues.jboss.org/browse/JBTM-2711
!XTS !MAIN !PERF !QA_JTA !QA_JTS_JDKORB

JBTM-2711 Updated the referenced version of WildFly

---

compensations/src/main/java/org/jboss/narayana/compensations/impl/CompensatableActionImpl.java

https://issues.jboss.org/browse/JBTM-2718
!BLACKTIE !QA_JTA !QA_JTS_JACORB !QA_JTS_IBMORB !QA_JTS_JDKORB !MAIN !PERF

[JBTM-2718] Make CompensatableActionImpl.WorkInfo class static

---

ArjunaJTS/jts/classes/com/arjuna/ats/jts/extensions/AtomicTransaction.java

Related to: https://developer.jboss.org/message/956793#956793

AtomicTransaction equals fix

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/RecoveryEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/PeriodicRecoveryTest.java

https://issues.jboss.org/browse/JBTM-2720
https://github.com/jbosstm/documentation/pull/39
!PERF !QA_JTA !QA_JTS_JDKORB !XTS !BLACKTIE

JBTM-2720 master

---

blacktie/pom.xml
scripts/hudson/narayana.bat
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-2721
!PERF !QA_JTA !QA_JTS_JDKORB !XTS !MAIN

JBTM-2721 Fix version of WildFly rather than use SNAPSHOT

---

pom.xml

https://issues.jboss.org/browse/JBTM-2727
!NO_TESTS

[JBTM-2727] Add debug profile

---

blacktie/pom.xml

https://issues.jboss.org/browse/JBTM-2723
!XTS !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

JBTM-2723 Upgrade the apr to 1.5.2.BT2

---

ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/ControlWrapper.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/coordinator/ArjunaTransactionImple.java
ArjunaJTS/jts/classes/com/arjuna/ats/jts/logging/jtsI18NLogger.java

JBTM-2725 

---

blacktie/hybrid/src/main/cpp/HybridSocketEndpointQueue.cxx
blacktie/hybrid/src/main/include/HybridSocketEndpointQueue.h

https://issues.jboss.org/browse/JBTM-2743
!XTS !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

JBTM-2743 Blacktie integration-tests TestTPCancel hang

---

blacktie/jatmibroker-xatmi/src/main/java/org/jboss/narayana/blacktie/jatmibroker/xatmi/mdb/MDBBlacktieService.java

https://issues.jboss.org/browse/JBTM-2744
!XTS !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

JBTM-2744 Warning message show with the mdb BlacktieStompAdministrationService and BlacktieAdminServiceXATMI

---

blacktie/common/C/pom.xml
blacktie/common/java/pom.xml
blacktie/hybrid/src/main/cpp/HybridSocketEndpointQueue.cxx

https://issues.jboss.org/browse/JBTM-2719
!XTS !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !MAIN

JBTM-2719 tpcall get three seconds delay in the fooapp quickstart

---

blacktie/btadmin/src/test/resources/btconfig.xml
blacktie/jatmibroker-nbf/src/test/resources/btconfig.xml
blacktie/jatmibroker-xatmi/pom.xml
blacktie/jatmibroker-xatmi/src/main/java/org/jboss/narayana/blacktie/jatmibroker/core/conf/Server.java
blacktie/jatmibroker-xatmi/src/test/java/org/jboss/narayana/blacktie/jatmibroker/core/conf/AtmiBrokerEnvXMLTest.java
blacktie/jatmibroker-xatmi/src/test/resources/btconfig.xml
build.sh

!PERF !QA_JTA !QA_JTS_JDKORB !MAIN !XTS

JBTM-2755 + Revert Jbtm 2260

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java

https://issues.jboss.org/browse/JBTM-2753
!PERF !BLACKTIE !XTS

Only call xa_end if the XAResource is associated

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/SubordinateTransaction.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporter.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/jca/TransactionImple.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/internal/jbossatx/jta/jca/XATerminator.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/internal/jbossatx/jts/jca/XATerminator.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/ServerImpl.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/TransactionImporterImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/TransactionImple.java
pom.xml
rts/at/bridge/pom.xml
txbridge/pom.xml

https://issues.jboss.org/browse/JBTM-2749
!PERF !BLACKTIE !XTS !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

JBTM-2749 Thread safe method to import (or create) an Xid

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/SubordinateTransaction.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporter.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/jca/TransactionImple.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/internal/jbossatx/jta/jca/XATerminator.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/internal/jbossatx/jts/jca/XATerminator.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/LocalServer.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/ServerImpl.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/TransactionImporterImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/TransactionImple.java
pom.xml
rts/at/bridge/pom.xml
txbridge/pom.xml

https://issues.jboss.org/browse/JBTM-2749
!PERF !BLACKTIE !QA_JTA !QA_JTS_JDKORB !XTS

JBTM-2749 SPI implementation of ExtendedJBossXATerminator

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/ObjectStoreEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ActionBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/LogRecordWrapper.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/OSBTypeHandler.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/CommitMarkableResourceRecord.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jta/CommitMarkableResourceRecordBean.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jta/XAResourceMBean.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jta/XAResourceRecordBean.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/tools/FailureXAResource.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/tools/ForgetTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/tools/ObjStoreBrowserTest.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/ArjunaTransactionImpleWrapper.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/RecoveredTransactionWrapper.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/ServerTransactionWrapper.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/XAResourceRecordBean.java

!PERF !BLACKTIE !QA_JTA !QA_JTS_JACORB !XTS
https://issues.jboss.org/browse/JBTM-2728

JBTM-2728 XAResourceMBean forget operation

---

ArjunaJTA/jdbc/tests/classes/com/hp/mwtests/ts/jdbc/basic/ConnectionImpleTest.java

https://issues.jboss.org/browse/JBTM-2676
!BLACKTIE !XTS !QA_JTA !QA_JTS_JDKORB !PERF

JBTM-2676 Updated to test that the connection.close does not fail

---

ArjunaCore/arjuna/pom.xml
pom.xml
scripts/hudson/narayana.sh
tomcat/pom.xml
tomcat/tomcat-jta/pom.xml
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/NarayanaJtaServletContextListener.java
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionManagerFactory.java
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionSynchronizationRegistryFactory.java
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/UserTransactionFactory.java
tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/BaseITCase.java
tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/TestApplication.java
tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/TestExecutor.java
tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/TestXAResource.java
tomcat/tomcat-jta/src/test/resources/arquillian.xml
tomcat/tomcat-jta/src/test/resources/context.xml
tomcat/tomcat-jta/src/test/resources/jbossts-properties.xml
tomcat/tomcat-jta/src/test/resources/scripts.btm
tomcat/tomcat-jta/src/test/resources/web.xml

https://issues.jboss.org/browse/JBTM-2334
!XTS !BLACKTIE !PERF !QA_JTA !QA_JTS_JDKORB

[JBTM-2334] Narayana Tomcat module

---

pom.xml

Downgrade the SPI to 7.1.0.SP2

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/CompletionCounter.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/RemoteServer.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/RemoteServerImpl.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/TransactionImporterImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java

https://issues.jboss.org/browse/JBTM-2774
!PERF !BLACKTIE !XTS !QA_JTS_JACORB !QA_JTA
Backport to 4.17 of https://github.com/jbosstm/narayana/pull/1078

JBTM-2774 4.17

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/CompletionCounter.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/RemoteServer.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/RemoteServerImpl.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/TransactionImporterImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java

https://issues.jboss.org/browse/JBTM-2774
!PERF !BLACKTIE !XTS !QA_JTS_JDKORB !QA_JTA
Backport to 5.2 of https://github.com/jbosstm/narayana/pull/1078

JBTM-2774 5.2

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/CompletionCounter.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/RemoteServer.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/RemoteServerImpl.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/TransactionImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/TransactionImporterImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java

https://issues.jboss.org/browse/JBTM-2774
!PERF !BLACKTIE !XTS !QA_JTS_JDKORB !QA_JTA

JBTM-2774 master

---

ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/jta/RecoveryManagerService.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/logging/jbossatxI18NLogger.java

https://issues.jboss.org/browse/JBTM-2783
Requires: https://github.com/jbosstm/jboss-as/pull/58

[JBTM-2783] Add suspend and resume methods to RecoveryManagerService

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/JTATransactionLogXAResourceOrphanFilter.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/RecoverConnectableAtomicAction.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/CommitMarkableResourceRecord.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceFailAfterCommitOrphan.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/recovery/jts/jca/coordinator/RecoveredServerTransaction.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/JCAServerTransactionWrapper.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/JTSXAResourceRecordWrapper.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/JTSXAResourceRecordWrapperMBean.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/SubordinateAtomicTransaction.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/TransactionImple.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/TestXAResource.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/common/TestBase.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/jca/XATerminatorImpleUnitTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSOSBTestBase.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSObjStoreBrowserTest.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/recovery/recoverycoordinators/GenericRecoveryCoordinator.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/recovery/transactions/RecoveringTransaction.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/recovery/transactions/TransactionCacheItem.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/resources/ExtendedResourceRecord.java

https://issues.jboss.org/browse/JBTM-2767
https://issues.jboss.org/browse/JBTM-2769 (no test required)
https://issues.jboss.org/browse/JBTM-2770
https://issues.jboss.org/browse/JBTM-2771
!PERF !QA_JTA !QA_JTS_JDKORB !XTS !BLACKTIE

JBTM-2767 JBTM-2769 JBTM-2770 JBTM-2771

---

narayana-full/pom.xml
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/NarayanaJtaServletContextListener.java
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionManagerFactory.java
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionSynchronizationRegistryFactory.java
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/UserTransactionFactory.java

https://issues.jboss.org/browse/JBTM-2799
!BLACKTIE !PERF !XTS !QA_JTA !QA_JTS_JDKORB

[JBTM-2799] Javadoc Tomcat module

---

.gitignore
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/utils/ThreadUtil.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/jdbc/JDBCImple_driver.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/thread/ThreadActionData.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/objectstore/ObjectStoreTest.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/ObjStoreBrowserTest.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/context/ContextManager.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/interposition/resources/arjuna/Interposition.java
ArjunaJTS/jts/pom.xml
ArjunaJTS/jts/src/test/resources/log4j.properties
ArjunaJTS/jts/tests/classes/com/hp/mwtests/ts/jts/exceptions/TestException.java
ArjunaJTS/jts/tests/classes/com/hp/mwtests/ts/jts/local/hammer/AtomicObject3.java
ArjunaJTS/jts/tests/classes/com/hp/mwtests/ts/jts/orbspecific/resources/AtomicObject.java
ArjunaJTS/jts/tests/classes/com/hp/mwtests/ts/jts/orbspecific/resources/AtomicWorker3.java
ArjunaJTS/jts/tests/classes/com/hp/mwtests/ts/jts/utils/Util.java
pom.xml
qa/README.txt
qa/TaskImpl.properties.template
qa/tests/build-jts.xml
qa/tests/src/org/jboss/jbossts/qa/junit/TaskImpl.java
qa/tests/src/org/jboss/jbossts/qa/junit/TestGroupBase.java
qa/tests/src/org/jboss/jbossts/qa/junit/testgroup/TestGroup_txcore_recovery.java
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-2786
https://issues.jboss.org/browse/JBTM-2787
!MAIN !XTS !QA_JTA !QA_JTS_JDKORB !PERF !BLACKTIE
JDBCSTORE
Added hold as I will need to raise JBTM for some of these issues that are related to errors running the test harness

JBTM-2673 JBTM-2786-7 JBTM-2800-4

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/objectstore/StoreManager.java

https://issues.jboss.org/browse/JBTM-2807
!XTS !BLACKTIE !QA_JTA !QA_JTS_JDKORB !PERF

[JBTM-2807] StoreManager always returns the same store

---

ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionClosingSynchronization.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionClosingSynchronization.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/TransactionHelper.java
narayana-full/pom.xml

!XTS !BLACKTIE !PERF !QA_JTA !QA_JTS_JDKORB

[JBTM-2806] Javadoc JMS module

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/utils/ThreadUtil.java

https://issues.jboss.org/browse/JBTM-2808
!XTS !QA_JTA !QA_JTS_JDKORB !BLACKTIE

JBTM-2808 Must sync weakhashmap or hang occurs

---

blacktie/xatmi/src/main/cpp/XATMIc.cxx

https://issues.jboss.org/browse/JBTM-2811
!XTS !PERF !QA_JTA !QA_JTS_JDKORB !MAIN

JBTM-2811 release the session id lock before blocking receive

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceFailActivate.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/TestXAResourceRecovery.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARecoveryModuleUnitTest.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java
pom.xml
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-2701
!MAIN !QA_JTA !QA_JTS_JDKORB

BUILD SCRIPT: Build against 5_2_BRANCH

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/LogRecordWrapper.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/XAResourceRecordBean.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/ObjStoreBrowserTest.java

https://issues.jboss.org/browse/JBTM-2812
!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !PERF

JBTM-2812 Ensure JTS/JTA forget behaviour is consistent

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/ObjectStoreEnvironmentBean.java

https://issues.jboss.org/browse/JBTM-2818
NO_TEST

JBTM-2818 Fix javadoc typo

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/basic/ExceptionDeferrerTest.java

https://issues.jboss.org/browse/JBTM-2822
!XTS !BLACKTIE !QA_JTA !QA_JTS_JDKORB !PERF

JBTM-2822 Added support for suppressed exceptions in prepare

---

ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionControl.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionImple.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionManager.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/DirectRecoverableConnection.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/IndirectRecoverableConnection.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ProvidedXADataSourceConnection.java
ArjunaJTA/jdbc/tests/classes/com/arjuna/ats/internal/jdbc/ConnectionManagerUnitTest.java

https://issues.jboss.org/browse/JBTM-2829
!XTS !BLACKTIE !QA_JTA !QA_JTS_JDKORB !PERF

[JBTM-2829] Avoid NPE when comparing JDBC connections

---

ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/basic/ExceptionDeferrerTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/common/FailureXAResource.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/jca/SubordinateTxUnitTest.java

!BLACKTIE !PERF !QA_JTA !QA_JTS_JDKORB !XTS

Deferred throwable tests

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryShutdownTest.java

https://issues.jboss.org/browse/JBTM-2837
!BLACKTIE !PERF !QA_JTA !QA_JTS_JDKORB !XTS

JBTM-2837 always run periodic recovery phase 2 if phase 1 has ran

---

ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/tools/osb/mbean/jts/XAResourceRecordBean.java

https://issues.jboss.org/browse/JBTM-2834
NO_TEST because the last (rebased) commit only added an explanatory comment

JBTM-2834 always call forget

---

.gitignore
blacktie/blacktie/README
blacktie/jatmibroker-xatmi/pom.xml
blacktie/pom.xml
blacktie/wildfly-blacktie/subsystem/pom.xml
scripts/hudson/narayana.bat
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-2843
!MAIN !QA_JTA !QA_JTS_JDKORB !PERF !XTS

JBTM-2843 Updated the version of the build-tools

---

compensations/src/test/java/org/jboss/narayana/compensations/integration/archive/EarArchiveTestLocal.java

https://issues.jboss.org/browse/JBTM-2844
!BLACKTIE !QA_JTA !QA_JTS_JDKORB !PERF

[JBTM-2844] Move test service client instantiation to the method

---

scripts/hudson/narayana.sh

BUILD SCRIPT ONLY: Disable 5_BRANCH rebasing

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceFailAfterCommitOrphan.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java
tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/TestExecutor.java
vertx/module/src/main/java/org/jboss/stm/STMVerticle.java

Few issues from Coverity static code analysis are fixed in this PR.
https://issues.jboss.org/browse/JBTM-2847
!PERF !QA_JTS_JDKORB !BLACKTIE !XTS

[JBTM-2847] Fixing few minor issues gathered when checking static code analysis report

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/TransactionImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/jca/TransactionImple.java

https://issues.jboss.org/browse/JBTM-2848
!MAIN !QA_JTA !XTS !BLACKTIE !PERF

[JBTM-2848] Fix incorrect equals() operation

---

ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/TransactionImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/TransactionImple.java

https://issues.jboss.org/browse/JBTM-2848

[JBTM-2848] Apply equals() fix to JTS as well

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java

https://issues.jboss.org/browse/JBTM-2846
!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB

JBTM-2846 Make actionStatus volatile

---

scripts/hudson/narayana.sh

!XTS !QA_JTA !QA_JTS_JDKORB !PERF !BLACKTIE

BUILD SCRIPT ONLY: Add a RTS profile

---

blacktie/wildfly-blacktie/feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/blacktie/main/module.xml

https://issues.jboss.org/browse/JBTM-2852
!MAIN !QA_JTA !QA_JTS_JDKORB !XTS !RTS !PERF

JBTM-2852 Upgrade the BT subsystem to depend on the new SPI

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/CacheStore.java

https://issues.jboss.org/browse/JBTM-2865
!PERF !QA_JTA !QA_JTS_JDKORB !XTS !RTS NO_WIN !BLACKTIE !AS_TESTS

JBTM-2865 write to _work inside _workList lock

---

XTS/WSTX/classes/com/arjuna/mw/wst11/common/CoordinationContextHelper.java

https://issues.jboss.org/browse/JBTM-2868

JBTM-2868 invoke getContextClassLoader within privileged block

---

blacktie/core/src/main/cpp/ThreadLocalStorage.cxx

https://issues.jboss.org/browse/JBTM-2871
!PERF !QA_JTA !QA_JTS !XTS !RTS !AS_TESTS

JBTM-2871 Fix STL compilation error on Fedora 25

---

ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/SynchronizationImple.java

I felt this being a quick fix, decided to do so.
https://issues.jboss.org/browse/JBTM-2879

[JBTM-2879] before completition swallow exception

---

ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/SynchronizationImple.java
scripts/hudson/narayana-rebase.sh

https://issues.jboss.org/browse/JBTM-2879
master PR: https://github.com/jbosstm/narayana/pull/1163

[JBTM-2879] before completition swallow exceptionple 5.5

---

ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/transactional/TransactionalInterceptorBase.java

WildFly 11 and EAP 7.1 switch to WFTC (https://github.com/wildfly/wildfly-transaction-client) which defines it's own security permissions of security manager for some of the actions.
When UserTransaction setting availability (https://github.com/wildfly/wildfly-transaction-client/blob/master/src/main/java/org/wildfly/transaction/client/LocalUserTransaction.java#L79) it requires `modifyUserTransactionAvailability`. This makes troubles e.g. for MDB invocations (see Jeff's comment at JBEAP-9599).
I think Narayana should process the call in doPrivileged section for not forcing user to set permission `modifyUserTransactionAvailability` when he just want to send a jms message (even it's under security manager).
This PR wraps the call in the privileged section.
!QA_JTA !QA_JTS_JDKORB !BLACKTIE …

[WFLY-8379] setAvailability of UserTransaction should be done in doPrivileged section

---

scripts/hudson/narayana.sh

!XTS !QA_JTA !QA_JTS_JDKORB !PERF !BLACKTIE

BUILD SCRIPT ONLY: update to check the result of building the jboss-as test suits

---

STM/src/main/java/org/jboss/stm/internal/reflect/InvocationHandler.java

https://issues.jboss.org/browse/JBTM-2881
!PERF !QA_JTA !QA_JTS_JDKORB !BLACKTIE !QA_JTS_JACORB !QA_JTS_OPENJDKORB !XTS !RTS 
NO_WIN !RTS

JBTM-2881 Do not hide application exceptions

---

qa/config/jdbc_profiles/default/JDBCProfiles

!MAIN !QA_JTS_JDKORB !QA_JTS_JACORB !QA_JTS_OPENJDKORB !XTS !BLACKTIE NO_WIN !RTS !AS_TESTS

Updated with the IP addresses of the default dev databases

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java

https://issues.jboss.org/browse/JBTM-2901
!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !PERF !RTS

JBTM-2901 skip recovery pass 2 if it has already ran

---

ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionManager.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelper.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/XAResourceConsumer.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/XAResourceFunction.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/ConnectionManagerTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelperTests.java

!BLACKTIE !PERF !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB
https://issues.jboss.org/browse/JBTM-2903
Similar fix will be needed for JDBC side as well, but the code for that lives in Spring Boot repository.

[JBTM-2903] Update connection management in JMS integration

---

ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/JmsXAResourceRecoveryHelper.java

https://issues.jboss.org/browse/JBTM-2903
!XTS !RTS !AS_TESTS !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDK !QA_JTS_JACORB !PERF NO_WIN

JBTM-2903 updated javadoc

---

ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/jca/XATerminatorImpleUnitTest.java
ArjunaJTS/jts/classes/com/arjuna/ats/jts/logging/jtsI18NLogger.java

https://issues.jboss.org/browse/JBTM-2907
https://issues.jboss.org/browse/JBEAP-11528
!BLACKTIE !XTS !PERF !RTS

[JBTM-2907] doRecover for JTS XATerminator implementation

---

ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/TransactionImple.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/jca/XATerminatorImpleUnitTest.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/recovery/transactions/TransactionCache.java

https://issues.jboss.org/browse/JBTM-2908
https://issues.jboss.org/browse/JBEAP-11154
!BLACKTIE !XTS !PERF !RTS !MAIN !QA_JTA !QA_JTS_JDKORB NO_WIN

[JBTM-2908] fix for moving jts jca transaction to assume completed

---

ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionImple.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/recovery/BasicXARecovery.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/jdbc/logging/jdbcI18NLogger.java
ArjunaJTA/jdbc/src/test/resources/h2recoveryproperties.xml
ArjunaJTA/jdbc/src/test/resources/jndi.properties
ArjunaJTA/jdbc/tests/classes/com/arjuna/ats/internal/jdbc/recovery/BasicXARecoveryTest.java
ArjunaJTA/jdbc/tests/classes/com/hp/mwtests/ts/jdbc/basic/JDBC2Test.java

https://issues.jboss.org/browse/JBTM-2909
https://issues.jboss.org/browse/JBTM-2910
https://issues.jboss.org/browse/JBTM-2911

Interposed sync

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/AtomicAction.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/SubordinateAtomicAction.java

replaces https://github.com/jbosstm/narayana/pull/1196#pullrequestreview-46496333

JBTM-2914 fix to set the timeout value

---

ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/drivers/modifiers/list.java

@tomjenkinson The patch for MariaDB we were talking about.

Add MariaDB driver name for IsSameRMModifier

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/SubordinateAtomicAction.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/subordinate/jca/coordinator/ServerTransaction.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/interposition/coordinator/ServerTransaction.java
XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/sagas/arjunacore/subordinate/SubordinateBACoordinator.java
XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/twophase/arjunacore/subordinate/SubordinateATCoordinator.java

Was introduced here: 
https://issues.jboss.org/browse/JBTM-1511
https://github.com/jbosstm/narayana/commit/d213dae6dc7a657cdfe4430ebad1ffd19e9f5607

Disable dynamic1PC during prepare for subordinates

---

ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/drivers/modifiers/ModifierFactory.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/jdbc/common/JDBCEnvironmentBean.java
tomcat/tomcat-jta/src/main/resources/jbossts-properties.xml

https://issues.jboss.org/browse/JBTM-2918
https://issues.jboss.org/browse/JBTM-2919
!XTS !BLACKTIE !PERF !RTS NO_WIN

Allow an override so we attempt to override for all connections

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java

https://issues.jboss.org/browse/JBTM-2922

Don't call ENDRSCAN if periodic recovery will do this anyway

---

ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/drivers/modifiers/ModifierFactory.java

https://issues.jboss.org/browse/JBTM-2924 
!PERF !QA_JTA !BLACKTIE !XTS !RTS !AS_TESTS !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

Added a trace statement to help identify the modifier in use

---

tomcat/tomcat-jta/pom.xml
tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/TestExecutor.java
tomcat/tomcat-jta/src/test/resources/arquillian.xml

!PERF !QA_JTA !BLACKTIE !XTS !RTS !AS_TESTS !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

verify tomcat test

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/stats/DummyXAResource.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/stats/StatSuccessUnitTest.java

https://issues.jboss.org/browse/JBTM-2926

JBTM-2926 Spurious stats for heuristics

---

scripts/hudson/narayana.sh

!BLACKTIE !XTS !PERF NO_WIN !JTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !MAIN !QA_JTS_OPENJDKORB !RTS

BUILD SCRIPT ONLY: Try to reduce check out size

---

pom.xml

JBTM-2685 JDK9 work

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/LRAClient.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java

https://issues.jboss.org/browse/JBTM-2935

JBTM-2935 @Complete should be optional

---

qa/tests/src/org/jboss/jbossts/qa/junit/TaskImpl.java

HQ_TESTS !MAIN !QA_JTA !QA_JTS_JACORB !XTS !RTS !BLACKTIE NO_WIN !AS_TESTS !QA_JTS_OPENJDKORB

Wait for process to die in QA tests (HQ store)

---

rts/lra/lra-annotations/src/main/java/io/narayana/lra/annotation/LRA.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/InvalidLRAExceptionMapper.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/LRAClient.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/LRAClientAPI.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/LRAStatus.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAStatus.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/InvalidLRAStateException.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/InvalidStateExceptionMapper.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ParticipantProxy.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ParticipantProxyResource.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ProxyService.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/participant/LRAManagement.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/participant/LRAParticipant.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/participant/TerminationException.java
rts/lra/lra-proxy/test/src/main/java/io/narayana/lra/proxy/test/api/LRAMgmtEgController.java
rts/lra/lra-proxy/test/src/main/java/io/narayana/lra/proxy/test/model/Participant.java
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java

These changes implement the spec updates made in https://github.com/jbosstm/microprofile-sandbox/pull/5 (my plan is to raise the spec PR soon).
https://issues.jboss.org/browse/JBTM-2944

JBTM-2944 LRA spec updates

---

XTS/WSCF/classes/com/arjuna/mwlabs/wscf/model/twophase/arjunacore/ParticipantRecord.java
XTS/WSTX/classes/com/arjuna/mw/wstx/logging/wstxI18NLogger.java
XTS/WSTX/classes/com/arjuna/mwlabs/wst/at/participants/DurableTwoPhaseCommitParticipant.java
XTS/WSTX/classes/com/arjuna/mwlabs/wst/at/participants/VolatileTwoPhaseCommitParticipant.java
XTS/bridge/src/org/jboss/jbossts/xts/bridge/at/BridgeWrapper.java
txbridge/src/main/java/org/jboss/jbossts/txbridge/outbound/BridgeSynchronization.java
txbridge/src/main/java/org/jboss/jbossts/txbridge/utils/txbridgeI18NLogger.java

More logging for XTS participants.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !AS_TESTS

[JBTM-2610][JBTM-2880] more logs in case of XTS troubles

---

.gitignore
README.md
pom.xml
rts/lra/lra-cdi-rest/src/main/java/io/narayana/lra/cdi/LraAnnotationProcessingExtension.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/StartCdiCheckIT.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/AllAnnotationsNoPathBean.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/CompleteOptionalBean.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/CorrectBean.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/CorrectMethodLRABean.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/ForgetWithoutDeleteBean.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/LeaveWithoutPutBean.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/MultiForgetBean.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/NoPostOrGetBean.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/OnlyOneLraAnnotationBean.java
rts/lra/lra-cdi-rest/src/test/java/io/narayana/lra/cdi/bean/OnlyTwoLraAnnotationsBean.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/LRAClientAPI.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAStatus.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/Implementations.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java
rts/lra/lra-coordinator/src/test/java/io/narayana/lra/test/LRASmokeIT.java
rts/lra/lra-filters/pom.xml
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ParticipantProxyResource.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ProxyService.java
rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java
rts/lra/pom.xml

https://issues.jboss.org/browse/JBTM-989
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !db2 !mysql !postgres !oracle

Adding checkstyle for the LRA modules

---

rts/lra/lra-client/pom.xml
rts/lra/lra-client/src/main/java/io/narayana/lra/client/Current.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/GenericLRAException.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/IllegalLRAStateException.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/IllegalLRAStateExceptionMapper.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/InvalidLRAIdException.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/InvalidLRAIdExceptionMapper.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/LRAClient.java
rts/lra/lra-client/src/main/java/io/narayana/lra/client/ParentLRAJoinException.java
rts/lra/lra-client/src/main/java/io/narayana/lra/logging/LRALogger.java
rts/lra/lra-client/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/RecoveryCoordinator.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java
rts/lra/lra-filters/pom.xml
rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/lra-proxy/api/pom.xml
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ParticipantProxy.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ParticipantProxyResource.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ProxyService.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/proxy/logging/LRAProxyLogger.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/proxy/logging/lraI18NLogger.java
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java

This is an enhancement of logging in LRA module.
* using LRA logger by lra package categorized logging
* `System.out.println` and `Exception.printStacktrace` should be eliminated
* having more detailed info in log when some exception occurs.
I would be happy if you @mmusgrov can check the approach of enhancing the log details if it is not against your vision. Thanks.
https://issues.jboss.org/browse/JBTM-2950
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !AS_TESTS !mysql !postgres !db2 !oracle

[JBTM-2950] enhancing LRA logging

---

scripts/hudson/benchmark.sh

!RTS !XTS !BLACKTIE !QA_JTS_JDKORB !QA_JTS_JACORB !QA_JTS_OPENJDKORB !MAIN !AS_TESTS NO_WIN !QA_JTA

BUILD SCRIPT ONLY: Change paratemers to check for regression

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/SubordinateAtomicActionRecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/SubordinationManagerXAResourceOrphanFilter.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XAResourceOrphanFilterTest.java
ArjunaJTA/narayana-jta/src/main/resources/jbossts-properties.xml
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/IsolatableServersClassLoader.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/impl/ServerImpl.java
ArjunaJTS/narayana-jts-ibmorb/src/main/resources/jbossts-properties.xml
ArjunaJTS/narayana-jts-idlj/src/main/resources/jbossts-properties.xml
ArjunaJTS/narayana-jts-jacorb/src/main/resources/jbossts-properties.xml

https://issues.jboss.org/browse/JBTM-2685

Add an XAResourceOrphanFilter that can check if there is a subordinate transaction in flight for an Xid

---

qa/tests/src/org/jboss/jbossts/qa/junit/TaskImpl.java
scripts/hudson/narayana.sh

!RTS !XTS !BLACKTIE !PERF !QA_JTS_JACORB !QA_JTS_OPENJDKORB !MAIN !AS_TESTS NO_WIN !QA_JTA

TEST CHANGE ONLY: Do not wait so long for the process to die

---

scripts/hudson/benchmark.sh

!RTS !XTS !BLACKTIE !QA_JTS_JDKORB !QA_JTS_JACORB !QA_JTS_OPENJDKORB !MAIN !AS_TESTS NO_WIN !QA_JTA

BUILD SCRIPT ONLY: Run the benchmark for 2 minutes

---

rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java

204 is expected
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !mysql !postgres !db2 !oracle

[JBTM-2954] fix of status code on getStatus to be correct when lra is active

---

STM/src/main/java/org/jboss/stm/internal/reflect/InvocationHandler.java

https://issues.jboss.org/browse/JBTM-1732
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !RTS

JBTM-1732 sync to memory when a new STM proxy is created

---

pom.xml

https://issues.jboss.org/browse/JBTM-2963
!RTS !XTS !BLACKTIE !QA_JTS_JDKORB !QA_JTS_JACORB !QA_JTS_OPENJDKORB !MAIN !AS_TESTS NO_WIN !QA_JTA

JBTM-2963 Upgrade Artemis to 1.5.5.jbossorg-008

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/abstractrecords/LastResourceRecord.java

https://issues.jboss.org/browse/JBTM-2983
Based on the question at https://stackoverflow.com/questions/48213996/transaction-commit-error-is-not-captured-in-ejb-code I investigated on the behaviour and I consider it wrong.
The point is that if commit on the non-XA resource fails the caller does not get response that the commit failed. I think the wrong error code is returned here. I think even the comment is wrong as recovery will not be taken for one phase commit resource.
Particular test is expected for WFLY as it's about integration with WFLY settings, txn spi and jca using the LastResource interface https://github.com/ochaloup/wildfly/tree/last-resource-fail-on-commit
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !mysql !postgres !db2 !oracle

[JBTM-2983] Returning a correct error code for one phase resource

---

ArjunaJTA/jta/classes/com/arjuna/ats/jta/resources/StartXAResource.java

https://issues.jboss.org/browse/JBTM-2991
NO_TEST

JBTM-2991 Deprecate old StartXAResource to move to SPI

---

narayana-release-process.sh

* hint what awestruct is
* fail if jenkins failure occurs and user don't want to continue
NO_TEST

[SCRIPTS ONLY] two amendments in release script

---

narayana-release-process.sh
rts/lra/lra-client/pom.xml

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !mysql !postgres !db2 !oracle

Release script adjustments

---

scripts/hudson/narayana.sh

JBTM-2999 Change git url for jboss-as part of the build

---

scripts/hudson/narayana.sh

JBTM-2999
!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !mysql !postgres !db2 !oracle

Jbtm 2999 change git urls to the git:// protocol

---

.gitignore
XTS/WS-C/dev/src/com/arjuna/wsc11/RegistrationCoordinator.java

https://issues.jboss.org/browse/JBTM-3007
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !mysql !postgres !db2 !oracle

[JBTM-3007] NPE would be thrown when exception does not exist

---

tomcat/tomcat-jta/pom.xml
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionalDataSourceFactory.java
tomcat/tomcat-jta/src/test/resources/context.xml

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !XTS !AS_TESTS

JBTM-3009 Update to add transactional datasource factory in tomcat-jta

---

narayana-release-process.sh

https://issues.jboss.org/browse/JBTM-3011
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !mysql !postgres !db2 !oracle

[JBTM-3011] docker lra image to be pushed during narayana release

---

tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionalDataSourceFactory.java

https://issues.jboss.org/browse/JBTM-3014
!RTS !QA_JTS_OPENJDKORB !AS_TESTS !QA_JTA !QA_JTS_JACORB !BLACKTIE !QA_JTS_JDKORB !XTS NO_WIN !MAIN !PERF

JBTM-3014 Support all the pooling parameters of the DBCP2 in the TransactionalDataSourceFactory

---

.gitignore
tomcat/tomcat-jta/src/test/resources/context.xml
tools/pom.xml

https://issues.jboss.org/browse/JWS-883
!RTS !QA_JTS_OPENJDKORB !AS_TESTS !QA_JTA !QA_JTS_JACORB !BLACKTIE !QA_JTS_JDKORB !XTS NO_WIN !PERF

[JWS-883] Database allocation via DBAllocator, Docker, H2

---

tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/BaseITCase.java
tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/app/TestExecutor.java

!RTS !QA_JTS_OPENJDKORB !AS_TESTS !QA_JTA !QA_JTS_JACORB !BLACKTIE !QA_JTS_JDKORB !XTS NO_WIN !MAIN !PERF

JBTM-3015 Fix the TestExecutor to close the connection at the end of test

---

tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionalDataSourceFactory.java

!RTS !QA_JTS_OPENJDKORB !AS_TESTS !QA_JTA !QA_JTS_JACORB !BLACKTIE !QA_JTS_JDKORB !XTS NO_WIN !MAIN !PERF

JBTM-3016 NoSuchFieldException throws when setting the pool properties

---

tomcat/tomcat-jta/pom.xml
tomcat/tomcat-jta/src/main/java/org/jboss/narayana/tomcat/jta/TransactionalDataSourceFactory.java
tomcat/tomcat-jta/src/test/java/org/jboss/narayana/tomcat/jta/integration/TestTransactionalDataSourceFactory.java

https://issues.jboss.org/browse/JBTM-3016
!RTS !QA_JTS_OPENJDKORB !AS_TESTS !QA_JTA !QA_JTS_JACORB !BLACKTIE !QA_JTS_JDKORB !XTS NO_WIN !MAIN !PERF

JBTM-3016 Update to use the BasicManagedDataSource

---

scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-3018
NO_TEST
change bash function name to work on macs

JBTM-3018 change bash function name for mac

---

rts/lra/lra-client/pom.xml
rts/lra/lra-filters/pom.xml
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java
rts/lra/pom.xml

https://issues.jboss.org/projects/JBTM/issues/JBTM-3022

Jbtm 3022 Build deprecated lra-annotation module

---

README.md

JBTM-3024 Add microprofile-lra build instructions

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java
rts/lra/lra-test/pom.xml
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/model/Activity.java
rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java
rts/lra/pom.xml

https://issues.jboss.org/browse/JBTM-2977

JBTM-2977 Handle network failures when ending participants

---

rts/lra/lra-test/pom.xml

https://issues.jboss.org/browse/JBTM-3026
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle

[JBTM-3026] lra test to prefer ipv4 as coordinator startup java argument

---

rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/JaxRsActivator.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
rts/lra/lra-test/pom.xml
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/TimedParticipant.java
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/model/Activity.java
rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java

https://issues.jboss.org/browse/JBTM-2978

JBTM-2978 Compensation should not be considered done in case of network error

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/ExtendedRecoveryModule.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryDriver.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/RecoveryMonitor.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/WorkerService.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaLogger.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryMonitorTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryMonitorTest2.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XATestResource.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XATestResourceXARecovery.java

https://issues.jboss.org/browse/JBTM-3017

JBTM-3017 RecoveryMonitor test in verbose mode

---

rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/ActivityController.java
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/StandardController.java
rts/lra/lra-test/src/main/java/io/narayana/lra/participant/api/TimedParticipant.java
rts/lra/lra-test/src/test/java/io/narayana/lra/participant/SpecIT.java

https://issues.jboss.org/browse/JBTM-3035

JBTM-3035 Ensure LRA context is propagated across non-LRA aware services

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryMonitorTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryScanTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XATestResourceXARecovery.java

https://issues.jboss.org/browse/JBTM-3017

JBTM-3017 Reset recovery failure flag on first recovery pass

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/ExtendedRecoveryModule.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryDriver.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/RecoveryMonitor.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/WorkerService.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaLogger.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryMonitorTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryMonitorTest2.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryScanTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XATestResource.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XATestResourceXARecovery.java

This is a backport for issue https://issues.jboss.org/browse/JBEAP-14959, 
!PERF !BLACKTIE

5.5 JBEAP-14959

---

ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/JNDIBean.java
ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionExtension.java

Signed-off-by: Laird Nelson <ljnelson@gmail.com>
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !mysql !postgres !db2 !oracle

JBTM-3045: Fixes Standalone JTA 1.2 Quickstart failure

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/abstractrecord/RecordTypeManager.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionImple.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/recovery/BasicXARecovery.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java

Few minor code changes found by the static code analysis. There are about
- null pointer exception checks
- unused code
- typos
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !TOMCAT !mysql !postgres !db2 !oracle !AS_TEST

[JBTM-2847] refactoring based on reports from static code analysis

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/Listener.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryMonitorDeadlockTest.java

https://issues.jboss.org/browse/JBTM-3047
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF !mysql !postgres !db2 !oracle

[JBTM-3047] adjusting stopping listener for avoid deadlock on client scan call

---

ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/atomicaction/AtomicActionUnitTest.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/atomicaction/TxStatsSystemErrorUnitTest.java

https://issues.jboss.org/browse/JBTM-3048
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF !mysql !postgres !db2 !oracle

JBTM-3048 Use TwoPhaseOutcome constants in test classes

---

ArjunaJTA/jta/classes/com/arjuna/ats/jta/common/JTAEnvironmentBean.java

for xa orphan detection filters
https://issues.jboss.org/browse/JBTM-3053
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !mysql !postgres !db2 !oracle

[JBTM-3053] printing to debug the node identifier which is used

---

ArjunaJTA/narayana-jta/pom.xml
XTS/WS-C/pom.xml
XTS/WS-T/pom.xml
XTS/WSTX/pom.xml
XTS/bridge/pom.xml
blacktie/.gitignore
blacktie/blacktie-admin-services/ear/pom.xml
blacktie/blacktie-admin-services/pom.xml
blacktie/common/C/pom.xml
blacktie/pom.xml
narayana-full/pom.xml
pom.xml
rts/at/tx/pom.xml
rts/at/util/pom.xml
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-3052 !JACOCO NO_WIN !BLACKTIE !MAIN !XTS !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !PERF !RTS !AS_TESTS !TOMCAT !mysql !postgres !db2 !oracle

JBTM-3052 Updated JBoss Parent to version 28

---

scripts/hudson/narayana.sh

!QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTA !XTS !MAIN !BLACKTIE !RTS !AS_TESTS !PERF !JACOCO

JWS-1126 Updated to Tomcat 9.0.11

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java

https://issues.jboss.org/browse/JBTM-3064
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !mysql !postgres !db2 !oracle !JACOCO !QA_JTA NO_WIN

JBTM-3064 After a crash add active LRA's back into the active list

---

STM/src/test/java/org/jboss/stm/TaxonomyTest.java

https://issues.jboss.org/browse/JBTM-3058
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !mysql !postgres !db2 !oracle !JACOCO !QA_JTA NO_WIN !AS_TESTS

JBTM-3058 STM behaviour (taxonomy) tests

---

scripts/hudson/narayana.sh

!QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !mysql !postgres !db2 !oracle !JACOCO !QA_JTA NO_WIN !AS_TESTS
I just need to check QA_JTS_OPENJDK and QA_JTS_JDKORB. It should be OK to just put the openjdk-orb in the classpath and no need to use the --patch-module. I will close the [WFLY-9569](https://issues.jboss.org/browse/WFLY-9569) if this PR is merged.

JBTM-2685 update to make sure the openjdk qa tests running with the jdk9

---

pom.xml

!QA_JTS_JACORB !BLACKTIE  !PERF  !TOMCAT !QA_JTS_OPENJDK !QA_JTS_JDKORB. !JACOCO !QA_JTA NO_WIN !AS_TESTS

JBTM-3076 Upgrade the arquillian core and wildfly-arquillian-container

---

scripts/hudson/narayana-rebase.sh

https://issues.jboss.org/projects/JBTM/issues/JBTM-3057
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !XTS !AS_TESTS !JACOCO !TOMCAT

JBTM-3067 Allow to rebase on the JDK-11 branch

---

blacktie/pom.xml

!QA_JTS_JACORB  !PERF !TOMCAT !QA_JTS_OPENJDK !QA_JTS_JDKORB. !JACOCO !QA_JTA NO_WIN !AS_TESTS !RTS !XTS

JBTM-3076 blacktie need to be run with wildfly.arquillian 2.0.0.Final

---

qa/run-tests.xml
qa/tests/build-jts.xml

!QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF NO_WIN !RTS !XTS !MAIN !JACOCO !TOMCAT !AS_TESTS
Testing QA_JTA to check the ant.java.version

JBTM-3084 QA tests on JDK9

---

compensations/pom.xml

the compensations project is setup only when xts environment is available
https://issues.jboss.org/browse/JBTM-3085
https://issues.jboss.org/browse/WFLY-11421
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle

[JBTM-3085] based on changes at WFLY-11421

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/InboundBridge.java
txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/InboundBridgeManager.java
txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/InboundBridgeRecoveryManager.java
txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/common/AbstractBasicTests.java
txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/junit/InboundCrashRecoveryTests.java

Possible changes for JIRA: https://issues.jboss.org/browse/JBEAP-15945
Upstream JIRA: https://issues.jboss.org/browse/JBTM-3079
Upstream PR: https://github.com/jbosstm/narayana/pull/1387

[JBEAP-15945] InboundBridge recovery aborts live transactions

---

scripts/hudson/narayana.bat

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF  !RTS !XTS !AS_TESTS !JACOCO !TOMCAT

BUILD SCRIPT ONLY: Detect the java version on windows

---

ArjunaJTA/cdi/pom.xml

based on the forum discussion at https://developer.jboss.org/message/986965#986965 the cdi artifact to be released
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle

[RELEASE] artifact org.jboss.narayana.jta:cdi should be part of the release

---

rts/lra/pom.xml

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !XTS

JBTM-3091 Depend on specific LRA snapshot builds

---

rts/lra/pom.xml

https://issues.jboss.org/browse/JBTM-3093
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !XTS !AS_TESTS !TOMCAT

JBTM-3093 Disable the site plugin for LRA

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ProxyService.java
rts/lra/lra-proxy/test/src/main/java/io/narayana/lra/proxy/test/model/Activity.java
rts/lra/lra-tck/tck/pom.xml
rts/lra/pom.xml

!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !mysql !postgres !db2 !oracle !JACOCO !QA_JTA NO_WIN !AS_TESTS
These changes are to align our implementation with the latest microfprofile-lra.

JBTM-3087 Implement the latest LRA spec changes

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/jdbc/logging/jdbcI18NLogger.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/utils/jtaxI18NLogger.java
ArjunaJTS/jts/classes/com/arjuna/ats/jts/logging/jtsI18NLogger.java
XTS/WS-C/dev/src/com/arjuna/webservices/logging/wscI18NLogger.java
XTS/WSAS/classes/com/arjuna/mw/wsas/logging/wsasI18NLogger.java
XTS/WSTX/classes/com/arjuna/mw/wstx/logging/wstxI18NLogger.java
common/classes/com/arjuna/common/logging/commonI18NLogger.java
txbridge/src/main/java/org/jboss/jbossts/txbridge/utils/txbridgeI18NLogger.java

https://issues.jboss.org/browse/JBTM-3107
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF WIN !RTS  !JACOCO !mysql !postgres !db2 !oracle !JDK11 !JDK9

[JBTM-3107] removing and escaping single quote characters from log message format

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTA/jta/tests/byteman-scripts/recovery-helper.txt
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/TestXAResource.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARecoveryModuleHelpersUnitTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARecoveryModuleUnitTest.java

to avoid potential deadlock scenario
https://issues.jboss.org/browse/JBTM-3111
https://issues.jboss.org/browse/WFLY-11706
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle

[JBTM-3111][WFLY-11706] ordering XARecoveryModule locks

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/jdbc/drivers/edb_driver.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/jdbc/drivers/postgres_driver.java

https://issues.jboss.org/browse/WFLY-11739
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO !AS_TEST DB_TESTS mysql postgres db2 oracle

[WFLY-11739] add support for PostgreSQL Plus 10.1

---

rts/lra/lra-test/tck/pom.xml
rts/lra/pom.xml

https://issues.jboss.org/browse/JBTM-3114
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle

[JBTM-3114] Update LRA versions to fixed snapshots

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/exceptions/FatalError.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/exceptions/ObjectStoreError.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/exceptions/ObjectStoreException.java
ArjunaCore/pom.xml
ArjunaCore/txoj/classes/com/arjuna/ats/txoj/exceptions/LockStoreException.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/exceptions/NotImplementedException.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/exceptions/RollbackException.java
ArjunaJTA/narayana-jta/pom.xml
common/classes/com/arjuna/common/util/propertyservice/StringPropertyReplacer.java
narayana-full/pom.xml
pom.xml

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !XTS !AS_TESTS !JACOCO !TOMCAT
JDK9 and JDK11
https://issues.jboss.org/projects/JBTM/issues/JBTM-3057
This PR replaces the https://github.com/jbosstm/narayana/pull/1379

JBTM-3057 javadoc failures on JDK9+

---

build.sh
rts/lra/lra-proxy/test/pom.xml
rts/lra/lra-test/tck/pom.xml
rts/lra/pom.xml
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-3104
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !MAIN !RTS

[JBTM-3104] adding LRA tests profile for LRA not being executed as part of the MAIN

---

README.md

https://issues.jboss.org/browse/JBTM-3119

[JBTM-3119] adding few sentences about tests in Narayana to README.md

---

ArjunaJTA/spi/src/test/java/io/narayana/spi/util/XADSWrapper.java
ArjunaJTS/jts/tests/classes/com/hp/mwtests/ts/jts/remote/timeout/TimeoutClient.java
rts/lra/lra-test/tck/src/test/java/io/narayana/lra/tck/arquillian/NarayanaLRABaseUrlProvider.java
rts/sra/src/main/java/io/narayana/sra/demo/api/FlightController.java
rts/sra/src/main/java/io/narayana/sra/demo/api/HotelController.java
rts/sra/src/main/java/io/narayana/sra/demo/api/TripController.java

https://issues.jboss.org/browse/JBTM-3124
https://issues.jboss.org/browse/JBTM-3125
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO

[JBTM-3125][JBTM-3124] small format and infinite loop call fixes

---

rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java

https://issues.jboss.org/browse/JBTM-3123
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !MAIN !mysql !postgres !db2 !oracle

[JBTM-3123] LRA POST to start has Incorrect @ApiResponse annotation

---

narayana-release-process.sh
pom.xml
rts/pom.xml

This PR contains:
* A change that was detected during the last release run.
* Moving the LRA to the community profile
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !TOMCAT !JACOCO !LRA !XTS !AS_TESTS !XTS

BUILD AND RELEASE SCRIPTS

---

scripts/hudson/narayana.sh

SCRIPTS ONLY: disable LRA for JACOCO

---

narayana-release-process.sh

A small addition to the fixed release script.
NO_TEST

RELEASE SCRIPTS ONLY: adding few more information to the error messages

---

scripts/hudson/narayana.sh

fix for error message
```
./scripts/hudson/narayana.sh: line 811: [: =: unary operator expected
```
!MAIN !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA DB_TESTS mysql postgres db2 oracle

SCRIPTS ONLY: unary operator expected error fix

---

rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/lra-service-base/src/main/java/io/narayana/lra/Current.java
rts/lra/pom.xml

https://issues.jboss.org/browse/JBTM-3126
This PR is a bug fix and an upgrade of the MP-LRA dependency

JBTM-3126 Do not start nested LRAs unles @NestedLRA is present

---

qa/tests/src/org/jboss/jbossts/qa/Utils/JNDIManager.java

https://issues.jboss.org/browse/JBTM-3130
!MAIN !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA DB_TESTS mysql postgres db2 oracle

JBTM-3130 Update JNDI manager for newer mysql and oracle drivers

---

rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ClientLRARequestFilter.java
rts/lra/lra-service-base/src/main/java/io/narayana/lra/Current.java

https://issues.jboss.org/browse/JBTM-3127

[JBTM-3127] LRA TCK Test Failure (mixedMultiLevelNestedActivity)

---

vertx/module/pom.xml

https://issues.jboss.org/browse/JBTM-3129
!MAIN !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !AS_TESTS !TOMCAT JACOCO !LRA !DB_TESTS !mysql !postgres !db2 !oracle !QA_JTA JDK11 !JDK8

JBTM-3129 disable the site plugin for the codeCoverage profile on JDK 11

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/objectstore/StoreManager.java

https://issues.jboss.org/browse/JBTM-3134
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !JACOCO !LRA
DB_TESTS db2

[JBTM-3134] adding exception message to StoreManager.init when class init fails

---

blacktie/pom.xml
narayana-release-process.sh
pom.xml

!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB BLACKTIE !XTS !PERF !RTS !AS_TESTS !TOMCAT !JACOCO !LRA !DB_TESTS !JDK11

JBTM-3136 Use https for dependencies

---

XTS/localjunit/xtstest/README.md
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-3139
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA MAIN XTS

[JBTM-3139] clarification that xtstest is only a supportive module with no tests

---

pom.xml

https://issues.jboss.org/browse/JBTM-3142

 JBTM-3142 Depend on the latest jboss-parent pom

---

ArjunaJTS/narayana-jts-ibmorb/pom.xml
common/classes/com/arjuna/common/util/ConfigurationInfo.java
common/classes/com/arjuna/common/util/propertyservice/PropertiesFactory.java
common/pom.xml

https://issues.jboss.org/browse/JBTM-3146

JBTM-3146 Make the parsing of XML and Java archives more flexible

---

ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/IsolatableServersClassLoader.java

https://issues.jboss.org/browse/JBTM-3153
Updating testcase for not being stuck in case there is an error during recovery.
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !AS_TESTS !TOMCAT !JACOCO !LRA
MAIN JDK11 WIN

[JBTM-3153] race condition at SimpleIsolatedServers

---

scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-3154
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !TOMCAT !JACOCO !LRA
AS_TESTS MAIN XTS RTS

[JBTM-3154] ./ path for -f maven test does not work in 3.6.1

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java

https://issues.jboss.org/browse/JBTM-3157

JBTM-3157 LRA participant does not respect JAX-RS path definitions

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/lra-service-base/src/main/java/io/narayana/lra/LRAConstants.java
rts/lra/lra-test/tck/pom.xml
rts/lra/pom.xml

This PR adds support for the following MP-LRA issues:
- issue164 Support notifications that an LRA has finished (@AfterLRA)
- issue173 Clarify how to report in progress compensations (in particular use 500 to report FailedToCompensate/FailedToComplete)

JBTM-3087 Add support for LRA issues 164 and 173

---

ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/BaseTransactionalDriverXAConnection.java

Related to Jira issue JBTM-3162
[https://issues.jboss.org/browse/JBTM-3162](https://issues.jboss.org/browse/JBTM-3162)

[JBTM-3162] Double check removed

---

ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/BaseTransactionManagerDelegate.java

MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS PERF WIN !RTS AS_TESTS !TOMCAT !JACOCO !LRA

Don't create the EnumSet and TransactionEvent unless it is required

---

scripts/hudson/narayana.sh

!MAIN !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS PERF WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

BUILD SCRIPT ONLY: comment on the PERF pull job

---

rts/sra/pom.xml

https://issues.jboss.org/browse/JBTM-3164
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !LRA

[JBTM-3164] RTS SRA not needed all microprofile fractions as dependencies

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-filters/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/pom.xml

LRA TCK test failures are expected. They will be fixed by https://github.com/eclipse/microprofile-lra/pull/204. After this is merged I will update this PR. Otherwise, it's good for review.

JBTM-3087 Ensure the LRA implementation is up to date

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/common/JTAEnvironmentBean.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/BaseTransactionManagerDelegate.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/logging/jbossatxI18NLogger.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/TransactionListenerRegistryTest.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/spi/SPIUnitTest.java

https://issues.jboss.org/browse/JBTM-3167
https://issues.jboss.org/browse/JBTM-3166
original PR for JBTM-3166: https://github.com/jbosstm/narayana/pull/1472
@mmusgrov @tomjenkinson 
I'm fixing the test failures and I fixed the issues that I consider the original PR has. Please review and comment with remarks.
MAIN AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA

[JBTM-3167][JBTM-3166] fixes for test failures brought by JBTM-3166

---

scripts/hudson/narayana.bat

!AS_TESTS !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !TOMCAT !JACOCO !LRA

Updated to use a local copy of WFLY

---

narayana-release-process.sh

anymore (is disabled), removing it from the release checks
/cc @mmusgrov

BUILD SCRIPT ONLY: narayana-codeCoverage job does not exists

---

rts/lra/lra-service-base/pom.xml

https://issues.jboss.org/browse/JBTM-3175
MAIN LRA

[JBTM-3175] adding lra-base-release release profile to pom.xml

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/AbstractRecord.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java

https://issues.jboss.org/browse/JBTM-3178
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !LRA

JBTM-3178 Add warning for AbstractRecord create failure

---

ArjunaJTS/narayana-jts-ibmorb/pom.xml
ArjunaJTS/narayana-jts-idlj/pom.xml
ArjunaJTS/narayana-jts-jacorb/pom.xml

https://issues.jboss.org/browse/JBTM-3179
MAIN

[JBTM-3179] enable adding java source files to narayana-jts-* source jars

---

rts/lra/lra-service-base/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
rts/lra/narayana-lra/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java

https://issues.jboss.org/browse/JBTM-3186

JBTM-3186 Safeguard LRA filters for situations when CDI is not available

---

rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java

https://issues.jboss.org/browse/JBTM-3180

JBTM-3180 Do not use null Entities on JAX-RS PUT requests

---

ArjunaCore/txoj/classes/com/arjuna/ats/txoj/LockManager.java
ArjunaCore/txoj/classes/com/arjuna/ats/txoj/logging/txojI18NLogger.java

https://issues.jboss.org/browse/JBTM-3188
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !LRA

JBTM-3188 Ensure lock store config uses the correct object store MBean

---

rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipant.java
rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipantResource.java

https://issues.jboss.org/browse/JBTM-3184

JBTM-3184 LRA TckParticipantTests do not finish started LRAs

---

rts/lra/narayana-lra/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java

https://issues.jboss.org/browse/JBTM-3191
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !MAIN

JBTM-3191 Align LRA client expectations for LRA coordinator default port

---

rts/lra/lra-coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java

https://issues.jboss.org/browse/JBTM-3192

JBTM-3192 Fix compensatorLink expectations in LRA coordinator

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java
osgi/jta/pom.xml
pom.xml

https://issues.jboss.org/browse/JBTM-3196
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !LRA !PERF

JBTM-3196 Upgrade to Artemis 2.9.0

---

narayana-full/src/main/assembly/bin.xml

https://issues.jboss.org/browse/JBTM-3199
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !LRA !MAIN

JBTM-3199 Include lra-coordinator war in the distribution

---

ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/IsolatableServersClassLoader.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/IsolatableServersClassLoaderTest.java

https://issues.jboss.org/browse/JBTM-3201
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !LRA

JBTM-3201 Synchronize the loadClass test method

---

blacktie/blacktie/pom.xml
scripts/hudson/narayana.sh

https://issues.jboss.org/browse/JBTM-3202
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !MAIN !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !LRA

JBTM-3202 Updated to deal with long file names

---

blacktie/hybrid/src/test/cpp/TestSocketSession.cxx

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !XTS NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !LRA !PERF !MAIN

TEST CHANGE ONLY: Make sure to null terminate the string

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/Listener.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/SubordinateAtomicActionRecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/subordinate/jca/SubordinateAtomicAction.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java

https://issues.jboss.org/browse/JBTM-3210
Not being stuck with `IllegalArgument` exception during recovery and closing recovery listener connection when there is no plan of processing it.
MAIN XTS AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA

JBTM-3210 recovery listener to be stuck

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/objectstore/CachedTest.java
ArjunaCore/txoj/classes/com/arjuna/ats/txoj/LockManager.java
ArjunaCore/txoj/classes/com/arjuna/ats/txoj/logging/txojI18NLogger.java
ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionManager.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/IsolatableServersClassLoader.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/server/IsolatableServersClassLoaderTest.java
blacktie/hybrid/src/test/cpp/TestSocketSession.cxx
narayana-release-process.sh
osgi/jta/pom.xml
pom.xml
rts/lra/lra-test/pom.xml
scripts/hudson/narayana.sh

There are most of the changes to fix scripts and to stabilize the release process. The other ones are:
* https://issues.jboss.org/browse/JBTM-3188 Ensure lock store config uses the object store MBean
** fix for the functionality perspective of Narayana tooling
* https://issues.jboss.org/browse/JBTM-3194 All access to shared states is under the connections monitor to remove deadlock
** deadlock fix
* https://issues.jboss.org/browse/JBTM-3195 Don't assert before all the threads return
** stabilize tests
* https://issues.jboss.org/browse/JBTM-3196 warn if no AIO
** better logging
* https://issues.jboss.org/browse/JBTM-3201 Synchronize the loadClass test method
** stabilize tests
* https://issues.jboss.org/browse/JBTM-3203 Updated to deal with long file names
** stabilize tests
MAIN QA_JTA …

Syncing the 5.9 branch with master

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/CacheStore.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/objectstore/CachedTest.java

https://issues.jboss.org/browse/JBTM-2867
https://issues.jboss.org/browse/JBTM-3195
MAIN XTS !AS_TESTS !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !TOMCAT JACOCO !LRA !XTS

JBTM-2867 JBTM-3195 Synchronize access to the state

---

STM/pom.xml
narayana-full/pom.xml

https://issues.jboss.org/browse/JBTM-2652
!MAIN XTS !AS_TESTS !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !TOMCAT JACOCO !LRA !XTS

JBTM-2652 Include STM javadocs in the distribution

---

rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipantRegistry.java

https://issues.jboss.org/browse/JBTM-3161
!MAIN XTS !AS_TESTS !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !TOMCAT JACOCO  !XTS

JBTM-3161 Include a no-args public constructor

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/narayana-lra/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java

https://issues.jboss.org/browse/JBTM-3206
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !MAIN

JBTM-3206 Consult matching URIs when calculating participant URIs

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/xa/TxStatsJTATest.java

https://issues.jboss.org/browse/JBTM-3218
MAIN

[JBTM-3218] statistics of 1PC should not be reported twice

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java

https://issues.jboss.org/browse/JBTM-3224
MAIN

[JBTM-3224] fix formatting of init object store error message

---

PULL_REQUEST_TEMPLATE.md

@xstefank thanks for the suggestion!
!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

Added a pull request template

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java

https://issues.redhat.com/browse/JBTM-3242

JBTM-3242 Set Location header to newly created LRA's

---

rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/internal/Implementations.java

https://issues.redhat.com/browse/JBTM-3243

JBTM-3243 Use PostConstruct/PreDestroy for ApplicationScoped bean (instead of Observer)

---

rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3229
The test for this is in the eclipse repo: https://github.com/eclipse/microprofile-lra/pull/267

JBTM-3229 Fix up previous commit

---

pom.xml
rts/lra/lra-coordinator-jar/pom.xml
rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3226
MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3226 upgrade byteman

---

narayana-release-process.sh
tools/maven/conf/settings.xml

MAIN TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA NO_WIN DB_TESTS mysql db2 postgres oracle

Force our maven tool to use https for the central repo

---

rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java
rts/lra/lra-service-base/src/main/java/io/narayana/lra/LRAHttpClient.java
rts/lra/lra-test/lra-test-arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/NarayanaLRARecovery.java
rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/FailingParticipantCallsIT.java
rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/resource/FailingAfterLRAListener.java

https://issues.redhat.com/browse/JBTM-3239
!LRA !MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
I have disabled the test for now while the PR is under review.

JBTM 3239 Ensure post LRA actions are retried in the presence of failures

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryManager.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/Connection.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/Listener.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/WorkerService.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/RecoveryDriverUnitTest.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/RecoverySocketUnitTest.java

https://issues.redhat.com/browse/JBTM-3257
https://issues.redhat.com/browse/JBTM-3259
MAIN AS_TESTS

[JBTM-3257] not throwing NPE when request command on recovery trigger is

---

rts/lra/lra-coordinator/pom.xml
rts/lra/lra-test/lra-test-basic/pom.xml
rts/lra/lra-test/lra-test-basic/src/test/resources/arquillian-thorntail.xml
rts/lra/lra-test/lra-test-basic/src/test/resources/logging.properties
rts/lra/lra-test/lra-test-tck/pom.xml
rts/lra/lra-test/lra-test-tck/src/test/resources/arquillian-thorntail.xml
rts/lra/lra-test/lra-test-tck/src/test/resources/logging.properties
rts/lra/lra-test/pom.xml
rts/lra/pom.xml
scripts/hudson/narayana.sh

Here is the link for the issue : https://issues.redhat.com/browse/JBTM-3231
LRA !MAIN !AS_TESTS !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO

JBTM-3231 LRA testrecovery2 fails

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java

https://issues.redhat.com/browse/JBTM-3088
MAIN QA_JTA AS_TESTS
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA

[JBTM-3088] protect against NPE on recovery second pass

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/StateManager.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/TxControl.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/state/OutputBuffer.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/xa/XATxConverter.java

https://issues.redhat.com/browse/JBTM-3262
!AS_TESTS !TOMCAT !JACOCO !LRA !BLACKTIE
!PERF  !QA_JTA !RTS !QA_JTS_OPENJDKORB !XTS !QA_JTS_JDKORB !QA_JTS_JACORB

JBTM-3262  improve string serialization

---

ArjunaJTS/integration/pom.xml
ArjunaJTS/jtax/pom.xml
ArjunaJTS/jts/pom.xml
ArjunaJTS/orbportability/pom.xml
XTS/WS-C/pom.xml
XTS/WS-T/pom.xml
XTS/WSTX/pom.xml
XTS/localjunit/pom.xml
compensations/pom.xml
rts/at/bridge/pom.xml
rts/at/util/pom.xml
rts/lra/pom.xml
txbridge/pom.xml
txframework/pom.xml

https://issues.redhat.com/browse/JBTM-3268
FYI @mayankkunwar 
MAIN JDK9 JDK11

[JBTM-3268] configure maven to compile Narayana on JDK9

---

scripts/hudson/narayana.sh

!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

BUILD SCRIPT ONLY: Disable performance testing for 5.2 branch

---

scripts/hudson/narayana.sh

!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

BUILD SCRIPT ONLY: Disable performance testing for 5.9 branch

---

scripts/hudson/narayana.sh

MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

PROFILE HANDLING: Update the names of the PROFILEs

---

scripts/hudson/narayana.sh

!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE PERF !LRA !NO_WIN !DB_TESTS mysql db2 postgres oracle

PROFILE HANDLING: Don't comment on profiles that are not expected

---

rts/at/bridge/src/main/java/org/jboss/narayana/rest/bridge/inbound/InboundBridgeFilter.java

https://issues.redhat.com/browse/WFLY-13295
This PR does not fix the whole WFLY-13295. There is need a change in the WFLY RTS subsystem as well.
The changes are in the similar fashion as they are here. They are summarized under this commit
https://github.com/ochaloup/wildfly/commit/c282cb5ebcaad776719e9ea236b7918fe490b3ab
(I can't create a PR for WFLY for now as I added a test for WFLY and it fails. It will be failing until Narayana is issued and version upgrade provided for WFLY)
MAIN RTS AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !TOMCAT !JACOCO !LRA

[WFLY-13295] RTS inbound bridge has to be activated for plain EJBs

---

rts/at/integration/src/main/java/org/jboss/narayana/rest/integration/RecoveryManager.java

for removal not showing warning in the server log
https://issues.redhat.com/browse/JBTM-3270
MAIN RTS AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !TOMCAT !JACOCO !LRA

[JBTM-3270] tracking persisted REST-AT participant 

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/objectstore/RecoveryStore.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/slot/RAMSlots.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/slot/SlotStore.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/slot/SlotStoreAdaptor.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/slot/SlotStoreEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/slot/SlotStoreEnvironmentBeanMBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/slot/SlotStoreKey.java

This is part one, with the in-memory backend.
https://issues.redhat.com/browse/JBTM-3276
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
I have set the PR to only test MAIN. I will investigate the AS_TEST, JACOCO and LRA Jenkin's axis failures.

JBTM-3276 SlotStore implementation.

---

rts/lra/pom.xml

!MAIN !RTS !AS_TESTS !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !TOMCAT !JACOCO !LRA

LRA - upgrade eclipse mp-lra api and tck version

---

ArjunaCore/arjuna/pom.xml
ArjunaJTA/jta/pom.xml
pom.xml
scripts/hudson/narayana.sh

!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN DB_TESTS !mysql db2 !postgres !oracle

TEST CHANGE ONLY: Use DB2 driver from Maven central

---

build.sh
pom.xml
rest-tx/tx/pom.xml
rest-tx/util/pom.xml
scripts/hudson/narayana.sh

…the app server
!MAIN TOMCAT AS_TESTS RTS JACOCO XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE !PERF LRA NO_WIN DB_TESTS mysql db2 postgres oracle

Get 4.17 branch working

---

scripts/hudson/narayana.sh

MAIN LRA XTS RTS AS_TESTS  TOMCAT
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !JACOCO

CI SCRIPT: on testing using -fae maven option

---

pom.xml
rts/lra/lra-coordinator-jar/pom.xml
rts/lra/lra-coordinator-thorntail/pom.xml
rts/lra/lra-coordinator/pom.xml

https://issues.redhat.com/browse/JBTM-3286

JBTM-3286 Expose OpenAPI and Swagger definitions for LRA coordinator

---

rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/Transaction.java
rts/lra/lra-test/lra-test-tck/pom.xml
rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3284

JBTM-3284 Fix TckRecoveryTests

---

PULL_REQUEST_TEMPLATE.md

!NO_WIN NO_WIN MAIN - this should mean it will run on Windows as !NO_WIN and MAIN are present
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA  !DB_TESTS !mysql !db2 !postgres !oracle

PULL_REQUEST_TEMPLATE CHANGE: Run Windows too by default

---

rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/resource/SimpleLRAParticipant.java

https://issues.redhat.com/browse/JBTM-3291
!LRA !MAIN !AS_TESTS !QA_JTA !JACOCO !QA_JTS_JACORB !TOMCAT !RTS !XTS !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
This PR adds a missing file that should have been included in PR #1603

JBTM-3247 Add missing file for FailedLRAIT test

---

narayana-full/src/main/assembly/bin.xml
rts/lra/lra-coordinator-war/pom.xml
rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3293

JBTM-3293 Add lra-coordinator-war module

---

PULL_REQUEST_TEMPLATE.md
pom.xml
rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3302
MAIN CORE
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA !DB_TESTS mysql db2 postgres oracle

[JBTM-3302] adding information about checkstyle rules to PR template

---

rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/FailedLRAIT.java

https://issues.redhat.com/browse/JBTM-3310
!AS_TESTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO LRA

JBTM-3310 only report failed LRAs

---

rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3087
!AS_TESTS

JBTM-3087 Upgrade MP-LRA snapshot dependencies

---

rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java

https://issues.redhat.com/browse/JBTM-3313

JBTM-3313 FailedLRAIT tests in basic testsuite fail

---

rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3087
!AS_TESTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO LRA

JBTM-3087 Upgrade microprofile snapshot dependency version

---

build.sh
scripts/hudson/narayana.sh

!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

XTS on 5.2 branch

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryDriver.java

https://issues.redhat.com/browse/JBTM-3315
Adding two methods {{synchronousVerboseScan}} and {{asynchronousVerboseScan}}
(+ reformatting on WFLY checkstyle)
MAIN AS_TESTS

[JBTM-3315] Adding verbose scan method for RecoveryDriver

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java

Possible fix for Jira issue [JBTM-3328](https://issues.redhat.com/browse/JBTM-3328)
MAIN AS_TESTS

JBTM-3328 - Possibly unneccessary logging on XA endAssociation

---

rts/pom.xml

https://issues.redhat.com/browse/JBTM-3327

JBTM-3327 Update Quarkus to 1.5.0.Final

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryManager.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/objectstore/TestBackwardsCompatibilityForSha0b511d470f7a.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/RecoverySocketUnitTest.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAOnePhaseResource.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/basic/JTATest.java

https://issues.redhat.com/browse/JBTM-3324

[JBTM-3324] static analysis coverity fixes

---

rts/lra/lra-test/lra-test-arquillian-extension/src/main/java/io/narayana/lra/arquillian/ConfigAuxiliaryArchiveAppender.java
rts/lra/lra-test/lra-test-arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/LRAAnnotationAdjuster.java
rts/lra/lra-test/lra-test-arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/NarayanaLRARecovery.java
rts/lra/lra-test/lra-test-tck/pom.xml
scripts/hudson/narayana.sh

https://issues.redhat.com/browse/JBTM-3318
LRA

[JBTM-3318] tckrecoverytests timeout fixes

---

common/classes/com/arjuna/common/util/propertyservice/AbstractPropertiesFactory.java
common/tests/com/arjuna/common/tests/propertyservice/EmptyPropertiesFactoryTest.java
common/tests/com/arjuna/common/tests/propertyservice/PropertiesFactoryUtil.java

https://issues.redhat.com/browse/JBTM-3337
MAIN

[JBTM-3337] assert empty property on startup

---

common/classes/com/arjuna/common/util/propertyservice/AbstractPropertiesFactory.java
common/tests/com/arjuna/common/tests/propertyservice/EmptyPropertiesFactoryTest.java
common/tests/com/arjuna/common/tests/propertyservice/PropertiesFactoryUtil.java

https://issues.redhat.com/browse/JBTM-3337
master PRs:
* https://github.com/jbosstm/narayana/pull/1639
* https://github.com/jbosstm/narayana/pull/1642
MAIN JDK11

[JBTM-3337] loaded property should be checked on emptiness

---

narayana-release-process.sh

* jira issues are at issues.redhat.com
* release script to use crumb token to pass jenkins XSS defence
MAIN

[SCRIPTS ONLY] using the redhat issues and run with XSS crumb

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java

MAIN TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle

JBTM-3345  XA_RB* not an error when from end(TMFAIL)

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalEnvironmentBean.java
pom.xml

change poolSize to have default limit.
upgrade artemis-journal to pull in https://issues.apache.org/jira/browse/ARTEMIS-2837
MAIN TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle

JBTM-3346 Journal store file count grows unbounded

---

ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaLogger.java

https://issues.redhat.com/browse/JBTM-3273
Clean-up the code based on the static code analysis which follows-up the JBTM-3273.

[JBTM-3273] cleanup follow-up based on coverity report

---

rts/lra/lra-client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/TestBase.java
rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/NonRootLRAParticipantIT.java

https://issues.redhat.com/browse/JBTM-3352
LRA

[JBTM-3352] cleaning lra coordinator api status endpoints

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ActionBean.java

https://issues.redhat.com/browse/JBTM-3351
https://groups.google.com/forum/#!topic/narayana-users/eHxGb6Zc5cY
MAIN AS_TESTS 

[JBTM-3351] clearHeuristics management operation to clear participant heuristics flag

---

scripts/hudson/narayana.bat

!CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !XTS !PERF !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

[SCRIPTS ONLY] .bat script to use github token instead of user/password

---

pom.xml

Updated download.java.net repo to https

---

scripts/hudson/narayana.sh

NO_TEST for 4.17 branch AS_TESTS testing removed

CI SCRIPT: Provide a default for JTA AS Tests

---

txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/junit/InboundCrashRecoveryTests.java

https://issues.redhat.com/browse/JBTM-3079
This replaces the PR #1663 
MAIN XTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

[JBTM-3079] additional test for inbound bridge recovery manager does rollback an inflight txn

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/AbstractRecord.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ActionBean.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java

this is an adjustment to 1130cc8e79 - PR #1653 
https://issues.redhat.com/browse/JBTM-3351
MAIN AS_TESTS 

[JBTM-3351](adjustment) clearHeuristics management operation to clear heuristic flag

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/CommitMarkableResourceRecordRecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/TransactionImporterImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/jca/XATerminatorImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceFailActivate.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/jca/TransactionImporterUnitTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/CrashRecovery2.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/TestXAResourceRecovery.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARecoveryModuleUnitTest.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/TransactionImporterImple.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/transaction/jts/jca/XATerminatorImple.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/jca/TransactionImporterUnitTest.java
XTS/jbossxts/pom.xml
XTS/localjunit/WSTX11-interop/src/main/java/com/jboss/transaction/txinterop/webservices/atinterop/client/SyncParticipantClient.java
XTS/localjunit/pom.xml
scripts/hudson/narayana.sh
txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/InboundBridge.java
txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/InboundBridgeManager.java
txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/InboundBridgeRecoveryManager.java
txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/common/AbstractBasicTests.java
txbridge/src/test/java/org/jboss/jbossts/txbridge/tests/inbound/junit/InboundCrashRecoveryTests.java

https://issues.jboss.org/browse/JBTM-3079
https://issues.jboss.org/browse/JBTM-2734
https://issues.jboss.org/browse/JBTM-2701
https://issues.jboss.org/browse/JBTM-3034
XTS JTA_AS_TESTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

[JBTM-3079][JBTM-2734][JBTM-2701][JBTM-3034] for 4.17

---

rts/lra/lra-proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRACDIExtension.java
rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/Deployer.java
rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/NestedParticipantIT.java
rts/lra/lra-test/lra-test-basic/src/test/java/io/narayana/lra/arquillian/resource/NestedParticipant.java
rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3358
MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3358 Update to MicroProfile LRA 1.0-M2

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedElement.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedXAResource.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedXid.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/RecoveryXids.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryXidsUnitTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARecoveryModuleUnitTest.java

https://issues.redhat.com/browse/JBTM-3361
MAIN TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle

JBTM-3361 recovery for non-unique xids

---

ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/ImportNonUniqueBranchTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/ResourceManager.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceImpl.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceRecordWrappingPluginImpl.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceWrapperImpl.java

https://issues.redhat.com/browse/JBTM-3361
MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3361 include a unit test for unique XIDs

---

rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java

https://issues.redhat.com/browse/JBTM-3364
LRA

[JBTM-3364] LRA recovery url creation to consider deployment path

---

rts/lra/lra-test/lra-test-arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/LRAAnnotationAdjuster.java

https://issues.redhat.com/browse/JBTM-3363
LRA

[JBTM-3363] fixing the timeout adjuster hack to work on OpenJ9

---

scripts/hudson/narayana.sh

AS_TESTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS  !TOMCAT !JACOCO !LRA

[SCRIPTS ONLY] AS_TESTS parameters changes for stabilization based on changes in jbosstm/jboss-as 5_BRANCH

---

scripts/hudson/narayana.sh

!MAIN !TOMCAT AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

Updated to add AS_TESTS PROFILE

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedElement.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedXAResource.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/NameScopedXid.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/RecoveryXids.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoveryXidsUnitTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/XARecoveryModuleUnitTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/ImportNonUniqueBranchTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/ResourceManager.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceImpl.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceRecordWrappingPluginImpl.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceWrapperImpl.java

JBEAP (7.3.x): https://issues.redhat.com/browse/JBEAP-20309
Upstream: https://issues.redhat.com/browse/JBTM-3361
Upstream PR: https://github.com/jbosstm/narayana/pull/1675, https://github.com/jbosstm/narayana/pull/1679 and https://github.com/jbosstm/narayana/pull/1681
XTS AS_TESTS
!CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

[JBEAP-20309] JBTM-3361 - recovery for non-unique xids

---

scripts/hudson/narayana-rebase.sh
scripts/hudson/narayana.bat
scripts/hudson/narayana.sh

MAIN WIN
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

[SCRIPTS ONLY] using GitHub token instead of user/password on commenting PRs 4.17

---

pom.xml
rts/lra/pom.xml
rts/pom.xml

Update of the JUnit version to 4.13.1.
MAIN LRA XTS RTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO

[DEPENDENCY UPDATE] JUnit to version 4.13.1

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/RecoveryXids.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/ImportNonUniqueBranchTest.java

https://issues.redhat.com/projects/JBTM/issues/JBTM-3361
This PR is the back port of the second part of the fix (on master) for JBTM-3361 (pr #1689 ).
XTS MAIN
!AS_TESTS !QA_JTA !QA_JTS_OPENJDKORB
!TOMCAT !RTS !JACOCO !QA_JTS_JACORB !QA_JTS_JDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres oracle

Jbtm 3361 part2

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/RecoveryXids.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/ImportNonUniqueBranchTest.java

Issue (7.3.x): https://issues.redhat.com/browse/JBEAP-20309
Upstream issue: https://issues.redhat.com/browse/JBTM-3361
Upstream PR: https://github.com/jbosstm/narayana/pull/1689
Ported changes from 4.1.7 patch branch: https://github.com/jbosstm/narayana/pull/1692
XTS CORE MAIN
!AS_TESTS  !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

[JBEAP-20309] JBTM-3361 - recovery for non-unique xids - Part 2

---

rts/lra/lra-coordinator-jar/pom.xml
rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery1TestCase.java
rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery2TestCase.java
rts/lra/lra-coordinator-jar/src/test/java/io/narayana/lra/coordinator/TestBase.java
rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3373
LRA

[JBTM-3373] lra-coordinator-jar to use maven failsafe plugin for tests

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/RecoveryCoordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/TestBase.java
rts/lra/service-base/src/main/java/io/narayana/lra/LRAConstants.java
rts/lra/service-base/src/test/java/io/narayana/lra/LRAConstantsTest.java
rts/lra/test/arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/NarayanaLRARecovery.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/FailedLRAIT.java

https://issues.redhat.com/browse/JBTM-3378
LRA

[JBTM-3378] LRA recovery manager on top of LRA coordinator

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/service-base/src/main/java/io/narayana/lra/LRAConstants.java

https://issues.redhat.com/browse/JBTM-3378
a fix follow-up to PR: https://github.com/jbosstm/narayana/pull/1704
LRA

[JBTM-3378] follow-up: improvement of using compiled pattern on getting LRA uid from LRA id

---

ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/nonuniquexids/XAResourceRecordWrappingPluginImpl.java

https://issues.redhat.com/browse/JBTM-3361

[JBTM-3361] double-check locking idiom fix

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/slot/DiskSlots.java

https://issues.redhat.com/browse/JBTM-3386
MAIN TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 …

JBTM-3386 performance tune DiskSlots store backend

---

rts/lra/service-base/src/main/java/io/narayana/lra/LRAConstants.java

https://issues.redhat.com/browse/JBTM-3379
LRA

[JBTM-3379] make participant timeout configurable

---

rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/client/NarayanaLRAClientIT.java

https://issues.redhat.com/browse/JBTM-3387
!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3387 NarayanaLRAClientIT#testGetAllLRAs doesn't close started LRA

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/service-base/src/main/java/io/narayana/lra/LRAConstants.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/FailedLRAIT.java

https://issues.redhat.com/browse/JBTM-3390
LRA

[JBTM-3390] using lraUid instead of lraId when working with LRA uid in the code

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java

https://issues.redhat.com/browse/JBTM-3392
LRA

[JBTM-3392] LRAClient enlist compensator to close JAX-RS client after response is processed

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/coordinator/pom.xml
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery1TestCase.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery2TestCase.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/TestBase.java
rts/lra/coordinator/src/test/resources/arquillian.xml
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ProxyService.java
rts/lra/proxy/test/src/test/java/io/narayana/lra/participant/SpecTest.java
rts/lra/service-base/src/main/java/io/narayana/lra/LRAConstants.java
rts/lra/service-base/src/main/java/io/narayana/lra/logging/lraI18NLogger.java
rts/lra/service-base/src/test/java/io/narayana/lra/LRAConstantsTest.java
rts/lra/test/arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/NarayanaLRARecovery.java

https://issues.redhat.com/browse/JBTM-3393
LRA
(note the other commits are added here to get test running but will be removed when the other PRs will be committed)

[JBTM-3393] narayana LRA client: cleaning and making it more flexible 

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery1TestCase.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/TestBase.java

https://issues.redhat.com/browse/JBTM-3397
LRA
This PR address the issues 1-5 described in the JIRA. Note that JIRA says we will follow up with two more to address:
6. Don't use RecordType.USER_DEF_FIRST0 for LRA participants
7. Use the support in ArjunaCore for managing nested LRAs.

JBTM-3397 Ensure that LRA uses the features provided by ArjunaCore

---

scripts/hudson/narayana.sh

A fix for a copy&paste error at https://github.com/jbosstm/narayana/pull/1730/

[SCRIPTS ONLY] fix for the copy&paste error added by last commit in narayana.sh

---

rts/lra/pom.xml
rts/lra/proxy/api/pom.xml
rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/ClassPathIndexer.java
rts/lra/proxy/test/pom.xml

https://issues.redhat.com/browse/JBTM-3400
LRA

[JBTM-3400] processing WFLY modules classpath with LRA Jandex indexer

---

txbridge/src/main/java/org/jboss/jbossts/txbridge/inbound/InboundBridgeRecoveryManager.java

https://issues.redhat.com/browse/JBTM-3406
MAIN XTS AS_TESTS 
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA

[JBTM-3406] InboundBridge should recover only local tx

---

XTS/WSTX/classes/com/arjuna/mw/wst11/service/JaxWSSubordinateHeaderContextProcessor.java

https://issues.redhat.com/browse/JBTM-3407
MAIN XTS AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA
an additional logging for JAXRS XTS filter 
an follow-up to https://github.com/jbosstm/narayana/pull/1742

[JBTM-3407] additional logging of XTS SOAP processing

---

ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionImple.java
ArjunaJTA/jdbc/tests/classes/com/hp/mwtests/ts/jdbc/basic/ConnectionImpleTest.java

https://issues.redhat.com/browse/JBTM-3409
MAIN

[JBTM-3409] not delist when not enlisted jdbc driver

---

blacktie/pom.xml
pom.xml
rts/at/tx/pom.xml
rts/at/util/pom.xml

BUILD SCRIPT: Changed some urls (including some repos) to https

---

blacktie/pom.xml

BUILD SCRIPT: Changed a url to https

---

rest-tx/util/pom.xml

!MAIN !CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

BUILD SCRIPT: Changed a plugin repo url to https

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/xa/XidImple.java

Issue: https://issues.redhat.com/browse/JBTM-3383
MAIN AS_TESTS QA_JTA
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA

[JBTM-3383] Improve ARJUNA016009: Caught::java.lang.NullPointerException log message

---

narayana-release-process.sh

RELEASE SCRIPT ONLY: Do not access the jobs via a Release view

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/BaseTransaction.java

Added thread name to transaction manager thread pool.
https://issues.redhat.com/browse/JBTM-3402
MAIN QA_JTA PERF XTS AS_TESTS
!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !RTS !TOMCAT !JACOCO !LRA

JBTM-3402 Stop creating unnamed thread pools

---

pom.xml

https://issues.redhat.com/browse/JBTM-3420
MAIN XTS LRA RTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN  !AS_TESTS !TOMCAT !JACOCO

[JBTM-3420] update version of the WildFly Arquillian to prevent spontaneous kills of container

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery1TestCase.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/LRACoordinatorRecovery2TestCase.java

https://issues.redhat.com/browse/JBTM-3418
LRA

JBTM-3418 Entity must not be null for http method PUT

---

tools/maven/conf/settings.xml

BUILD SCRIPT: Override download.java.net with an https url

---

rts/lra/pom.xml

Update MP LRA to 1.0-RC2

---

pom.xml

MAIN QA_JTA
!QA_JTS_OPENJDKORB !QA_JTS_JACORB !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA ! BLACKTIE !QA_JTS_JDKORB

bumping version of org.apache.ant:ant to 1.10.9

---

rts/lra/pom.xml

Update MP LRA to 1.0 (staging repository for CCR)

---

rts/lra/pom.xml
rts/pom.xml

https://issues.redhat.com/browse/JBTM-3426
LRA

[JBTM-3426] Update for Thorntail 2.7.0 in LRA

---

ArjunaJTS/jacorb/etc/common-xdoclet.xml
ArjunaJTS/jacorb/etc/jacorb_jar.manifest
blacktie/pom.xml
pom.xml

https://issues.redhat.com/browse/JBTM-3434
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS QA_JTA QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3434 : Updating slf4j maven dependency

---

tools/pom.xml

https://issues.redhat.com/browse/JBTM-3438
Making the `test-utils` to be deployed to Nexus on release.
MAIN

[JBTM-3438] deploy artifact org.jboss.narayana::test-utils:jar to nexus

---

tools/pom.xml

https://issues.redhat.com/browse/JBTM-3438
upstream PR: https://github.com/jbosstm/narayana/pull/1794
MAIN

[JBTM-3438] deploy artifact org.jboss.narayana::test-utils:jar to nexus 

---

rts/lra/coordinator/pom.xml
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/objectstore/JDBCObjectStoreTest.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/objectstore/TestBase.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/objectstore/VolatileObjectStoreTest.java
rts/lra/coordinator/src/test/resources/alt-jbossts-properties.xml
rts/lra/coordinator/src/test/resources/h2jbossts-properties.xml

This PR resolves the JIRA issue [JBTM-3398](https://issues.redhat.com/browse/JBTM-3398)
LRA JDK11
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF LRA NO_WIN !DB_TESTS

JBTM-3398 Test LRA behaviour on different Object Stores

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/RecoveryCoordinator.java

https://issues.redhat.com/browse/JBTM-3441
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

subresource

---

.github/workflows/lra-test.yml

!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

Remove caching from lra-test.yml

---

qa/config/jdbc_profiles/default/JDBCProfiles

Added more notes on handling Oracle

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/RecoveryXids.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/utils/XAUtils.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/common/JTAEnvironmentBean.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/basic/TestXAROverride.java

https://issues.redhat.com/browse/JBTM-3440
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3440 override isSameRM

---

XTS/WS-C/pom.xml
pom.xml

https://issues.redhat.com/browse/JBTM-3448
MAIN CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle

JBTM-3448 update dependencies for jdk-16 build.

---

ArjunaCore/arjuna/pom.xml
common/pom.xml
pom.xml
rts/lra/client/pom.xml
rts/lra/pom.xml
scripts/hudson/narayana.sh
tools/pom.xml

* not building WildFly on LRA testing
* not building all Narayana artifacts when need to run only LRA testing
* shrinking a bit number of dependencies to download less
LRA

[SCRIPTS ONLY] making LRA test build faster

---

README.md

readme change (ie no testing)
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

Specify that the JDK is required for building

---

scripts/hudson/narayana.sh

XTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

[SCRIPTS ONLY] do not fail on XTS when skipping tests is activated

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/TransactionReaper.java

fix for ReaperElementManager reinsertion behaviour. JBTM-3453
MAIN CORE !TOMCAT !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3447 Improve diagnostics for slow transactions

---

rts/lra/API.adoc
rts/lra/coordinator/pom.xml
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java

https://issues.redhat.com/browse/JBTM-3456
LRA

[JBTM-3456] adding OpenAPI reference of LRA version to LRA Coordinator class

---

rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3459

JBTM-3459 Upgrade MP LRA to 1.0-RC3

---

rts/sra/pom.xml

Task:
https://issues.redhat.com/browse/JBTM-3461
RTS
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !LRA

Changes for JBTM-3461 using quarkus instead of thorntail

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/CoordinatorContainerFilter.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/RecoveryCoordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/internal/LRARecoveryModule.java
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRACDIExtension.java
rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipant.java
rts/lra/service-base/src/main/java/io/narayana/lra/logging/LRALogger.java
rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java

https://issues.redhat.com/browse/JBTM-3474

JBTM-3474 LRA filters log an invalid warning about missing CDI

---

pom.xml

https://issues.redhat.com/browse/JBTM-3466
Using Narayana proper checkstyle ruleset placed in a separate project https://github.com/jbosstm/narayana-checkstyle-config
MAIN BLACKTIE JACOCO RTS LRA AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !XTS !PERF NO_WIN !TOMCAT

[JBTM-3466] using narayana-checkstyle-config for code styling

---

ArjunaJTA/narayana-jta-jakarta/pom.xml

and providing a way to deploy the javadoc/sources artifacts with nexus staging plugin
MAIN

[RELEASE] adding release profile for jakarta jta module

---

ArjunaCore/arjuna/pom.xml
ArjunaJTA/jta/pom.xml
pom.xml
qa/TaskImpl.properties.template
qa/build.xml
qa/config/jdbc_profiles/default/JDBCProfiles
qa/pom.xml
qa/run-tests.xml

This PR fixes JIRA: https://issues.redhat.com/browse/JBTM-3450
Profiles to test:
CORE QA_JTA QA_JTS_OPENJDKORB oracle
Profiles to skip:
!MAIN !TOMCAT !QA_JTS_JACORB !QA_JTS_JDKORB !AS_TESTS !RTS !JACOCO !XTS  !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres

[JBTM-3450] Oracle JDBC drivers updated to version 18.3.0.0 (18c)

---

pom.xml

https://issues.redhat.com/browse/JBTM-3485
MAIN AS_TESTS

[JBTM-3485] upgrade CDI API used in code from 1.2 to 2.0

---

ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/transactional/TransactionalInterceptorBase.java
ArjunaJTA/cdi/pom.xml
ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/TransactionalInterceptorFactoryTest.java
ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/TransactionalTestServiceInterceptorFactory.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java

https://issues.redhat.com/browse/JBTM-3442
MAIN AS_TESTS
@manovotn could you, please, take a look at this PR?

[JBTM-3442] transactional cdi InterceptionFactory

---

ArjunaCore/arjuna/pom.xml
ArjunaJTA/jta/pom.xml

This PR fixes the JIRA [JBTM-3486](https://issues.redhat.com/browse/JBTM-3486)
Test to run:
DB_TESTS oracle
Test to exclude:
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !mysql !db2 !postgres

[JBTM-3486] Updated oracle driver in ArjunaCore.arjuna

---

ArjunaCore/pom.xml
ArjunaJTA/cdi/pom.xml
ArjunaJTA/pom.xml
ArjunaJTS/pom.xml
STM/pom.xml
XTS/pom.xml
code-coverage/pom.xml
common/pom.xml
compensations/pom.xml
ext/pom.xml
osgi/pom.xml
pom.xml
qa/pom.xml
rts/at/bridge/pom.xml
rts/at/integration/pom.xml
rts/at/pom.xml
rts/at/tx/pom.xml
rts/at/util/pom.xml
rts/at/webservice/pom.xml
rts/lra/pom.xml
rts/pom.xml
tools/pom.xml
txbridge/pom.xml
txframework/pom.xml
vertx/pom.xml

This PR addresses JIRA [JBTM-3478](https://issues.redhat.com/browse/JBTM-3478)
Profiles passed:
!MAIN !CORE
Profiles to skip:
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3478] Added SortPom to narayana-all and activated it by default

---

rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java

https://issues.redhat.com/browse/JBTM-3494
Lazily constructs NarayanaLRAClient helper. Doing it this way avoids it's construction if the filter is never used and it also minimises our dependency on CDI.

JBTM-3494 Lazily construct a NarayanaLRAClient helper

---

ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/NarayanaTransactionManager.java
ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionContext.java
ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactionScoped/TransactionScopeLifecycleEventsTest.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java

https://issues.redhat.com/browse/JBTM-3416
MAIN AS_TESTS

[JBTM-3416] emit the @PreDestroyed event for TransactionScoped beans 

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/jdbc/drivers/enterprisedb_driver.java

https://issues.redhat.com/browse/JBTM-3496
MAIN

[JBTM-3496] object store driver class for Postgres Plus DB - EnterpriseDB JDBC Driver

---

narayana-release-process.sh

MAIN CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle

Check some of the release jobs before uploading the binaries

---

CONTRIBUTING.md

https://issues.redhat.com/browse/JBTM-3408
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3408 Include a note about language usage

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/objectstore/JournalStoreTest.java
pom.xml

https://issues.redhat.com/browse/JBTM-3502
AS_TESTS
CORE
!TOMCAT  !RTS !JACOCO XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle !XTS

JBTM-3502 Upgrade artemis to version 2.16.0

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/jdbc/drivers/enterprisedb_driver.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/objectstore/JournalStoreTest.java
ArjunaJTA/narayana-jta-jakarta/pom.xml
pom.xml

https://issues.redhat.com/browse/JBTM-3502
https://issues.redhat.com/browse/JBTM-3496
backport of the following to the 5.11 branch:
14f978f JBTM-3502 Upgrade artemis to version 2.16.0
2d614f8 [JBTM-3496] object store driver class for Postgres Plus DB - EnterpriseDB JDBC Driver
90209fa [RELEASE] adding release profile for jakarta jta module
MAIN CORE TOMCAT AS_TESTS RTS JACOCO
XTS QA_JTA
!QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN
DB_TESTS
!mysql !db2 !postgres !oracle

backport selected fixes to the 5.11 branch

---

README.md

Issue: https://issues.redhat.com/browse/JBTM-3507
NO_TEST

JBTM-3507 Changing old links in README

---

ArjunaCore/arjuna/pom.xml
ArjunaJTA/jta/pom.xml
ArjunaJTA/spi/src/test/resources/module.xml
blacktie/build-release-pkgs.xml
blacktie/codeGeneration/src/main/scripts/generate-executables.xml
blacktie/utils/cpp-plugin/src/main/resources/META-INF/maven/plugin.xml
pom.xml
qa/TaskImpl.properties.template
qa/build.xml
qa/config/jdbc_profiles/default/JDBCProfiles
qa/pom.xml
qa/run-tests.xml
qa/tests/build-core.xml
qa/tests/build-jta.xml
qa/tests/build-jts.xml
qa/tests/scripts/as-tests.xml
scripts/hudson/narayana.sh

QA_JTA QA_JTS_JDKORB
!MAIN !CORE !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

[RELEASE][5.11 branch] fix Narayana version to work with 5.11 SNAPSHOT

---

scripts/pre-release.sh

Keep narayana-tomcat under jbosstm org version updated

---

scripts/hudson/narayana.bat

Reverting the deleted `narayana.bat` file, which was deleted as part of https://github.com/jbosstm/narayana/pull/1873
MAIN CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

Reverting narayana.bat

---

build.sh

Issue: https://issues.redhat.com/browse/JBTM-3516

JBTM-3516 fix passing parameters with spaces in build.sh

---

rts/lra/pom.xml

https://issues.redhat.com/browse/JBTM-3108
!MAIN !CORE !TOMCAT !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB PERF LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3108 enable site plugin

---

scripts/hudson/narayana.sh
scripts/pre-release.sh

!MAIN !CORE TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

Replace the version number of Narayana in the narayana-tomcat checkout

---

qa/config/jdbc_profiles/default/JDBCProfiles

NO_TEST
FYI: @mmusgrov @ochaloup @mayankkunwar @jmfinelli I will merge this

Added some information on what to wait for before proceeding

---

rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipant.java
rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRAParticipantRegistry.java

https://issues.redhat.com/browse/JBTM-3521
LRA
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3521 Make LRAParticipantRegistry constructor public

---

rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/nonjaxrs/LRACDIExtension.java

https://issues.redhat.com/browse/JBTM-3527
LRA

[JBTM-3527] try context class loader when LRA loads participant classes at start

---

rts/lra/test/arquillian-extension/pom.xml

https://issues.redhat.com/browse/JBTM-3528
LRA
JDK11
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF  !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3528: Create release profile for lra-test-arquillian-extension

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java

This PR *TEMPORARY* addresses [JBTM-3513](https://issues.redhat.com/browse/JBTM-3513)
MAIN CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3513] Temporary workaround to fix JBTM-3513

---

rts/lra/test/tck/src/test/resources/arquillian-wildfly.xml

https://issues.redhat.com/browse/JBTM-3534
LRA

[JBTM-3534] pass timeout factor configuration to TCK wildfly arquillian tests

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/ObjectStoreEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/LogRecordWrapper.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/UidWrapper.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/ExposeAllLogsTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/tools/ObjStoreBrowserTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/jca/XATerminatorImpleUnitTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSOSBTestBase.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSObjStoreBrowserTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/ObjStoreBrowserTest.java
osgi/jta/src/main/java/org/jboss/narayana/osgi/jta/internal/ObjStoreBrowserImpl.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/FailedLongRunningAction.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/tools/osb/mbean/LRAActionBean.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/tools/osb/mbean/LRAActionBeanMBean.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/tools/osb/mbean/LRAParticipantRecordWrapper.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/tools/osb/mbean/LRAParticipantRecordWrapperMBean.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/tools/osb/mbean/ObjStoreBrowserLRATest.java

https://issues.redhat.com/browse/JBTM-3524
Implementation of the LRA records to be listed within JMX MBean records.
LRA MAIN JDK11

[JBTM-3524] LRA records to be listed as part of ObjStoreBrowser

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/RecoveryEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java
ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/RecoveryXids.java

and OpenShift scaledown processing to be configurable without JVM restart
https://issues.redhat.com/browse/JBTM-3535
MAIN TOMCAT AS_TESTS RTS XTS QA_JTA QA_JTS_JDKORB  LRA
!JACOCO NO_WIN !PERF !QA_JTS_OPENJDKORB !QA_JTS_JACORB

[JBTM-3535] recovery property required for graceful shutdown

---

build-release-pkgs.xml
rts/lra/test/arquillian-extension/pom.xml

Fixes for release

---

rts/lra/test/pom.xml

https://issues.redhat.com/browse/JBTM-3542
LRA

[JBTM-3542] release org.jboss.narayana.rts:lra-test

---

ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/transactional/TransactionalInterceptorNever.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java

https://issues.redhat.com/browse/JBTM-3543
MAIN CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !LRA NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO

JBTM-3543 Replace confusing log message with something more appropriate

---

qa/config/jdbc_profiles/default/JDBCProfiles

These set up for a specific CI system
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

Removed the docker commands for setting up the databases

---

ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactionScoped/TransactionScopeLifecycleEventsTest.java

https://issues.redhat.com/browse/JBTM-3555
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3555 Add a test for transaction timeouts using CDI

---

scripts/release/utils/http_helper.py

[RELEASE] fix python 3 issue in relase script

---

scripts/release/pre_release.py
scripts/release/update_jira.py
scripts/release/update_upstream.py
scripts/release/utils/http_helper.py
scripts/release/utils/https_helper.py
scripts/release/utils/input_helper.py
scripts/release/utils/jira_helper.py

upgrade release scripts to python 3

[RELEASE] upgrade python release scripts

---

PULL_REQUEST_TEMPLATE.md

!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA NO_WIN !DB_TESTS mysql db2 postgres oracle

Remove the !NO_WIN from the template

---

ArjunaJTA/spi/src/test/java/io/narayana/spi/DbTester.java
ArjunaJTA/spi/src/test/resources/db.properties

[JBTM-3570](https://issues.redhat.com/browse/JBTM-3570)
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3570: test failures in the narayana-spi module

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java
pom.xml

https://issues.redhat.com/browse/JBTM-3572
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3572 use non blocking versions of journal appendDelete calls

---

.mvn/wrapper/settings.xml

CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle

Disable an old maven repo that is not in use

---

scripts/hudson/narayana.sh

CORE !TOMCAT AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

Updating git protocol to https protocol

---

qa/run-tests.xml

This PR addresses [JBTM-3575](https://issues.redhat.com/browse/JBTM-3575)
Build axis:
DB_TESTS oracle
Skipped:
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !mysql !db2 !postgres

[JBTM-3575] Introduced ServiceName when the JDBC object store is tested

---

pom.xml

CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle

JBTM-3576 Update version.org.jboss.openjdk-orb to 8.1.9.Final

---

vertx/module/pom.xml

CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle

Updated to consolidate on the junit version with the main pom.xml

---

ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/drivers/XADataSourceReflectionWrapper.java
common/classes/com/arjuna/common/internal/util/ClassloadingUtility.java

https://issues.redhat.com/browse/JBTM-3580
All tests passed with JDK11.
```
[INFO] stm-vertex-shared .................................. SUCCESS [  1.615 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  43:04 min
[INFO] Finished at: 2022-02-04T16:42:07-05:00
```
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3580 Replace getParameterTypes().length with getParameterCount()

---

scripts/hudson/narayana.sh

https://issues.redhat.com/browse/JBTM-3582
I added a check for running axes that require Java 11 or above (AS_TESTS|RTS|JACOCO|XTS). Note that this should catch the XTS profile which did indeed fail but the LRA axis should pass.
The jdk checks happen in two places:
1. function clone_as which uses our jboss-as 5_BRANCH - this axis can only run on JDK 11 or above
2. function download_as which just grabs either the latest WildFly if the jdk version is 11 or above and otherwise gets the last version that can run with Java 8. For example the LRA axis just needs a JAX-RS compliant container so WildFly 26 is fine
JDK11 !CORE !TOMCAT !AS_TESTS !RTS !JACOCO XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3582 Check that WildFly and java versions are compatible

---

scripts/hudson/narayana.sh

Changed the wording of where the WildFly fork is cloned from

---

rts/at/tx/src/test/java/org/jboss/jbossts/star/test/SRATest.java

Adding SRA test with two participants (annotations) 
[https://issues.redhat.com/browse/JBTM-3599](https://issues.redhat.com/browse/JBTM-3599)
JDK11
CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3599] Test that SRA annotations work with two participants

---

scripts/hudson/narayana.sh

CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle

BUILD SCRIPT: Use the profile name

---

ArjunaJTA/jms/pom.xml
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/JMSContextProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionClosingSynchronization.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionProxy.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/JMSContextIntegrationTest.java
ArjunaJTA/narayana-jta/pom.xml

https://issues.redhat.com/browse/JBTM-3437
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle
(some commits on top of https://github.com/jbosstm/narayana/pull/1793)

JBTM-3437 JMS 2.0 integration

---

narayana-full/pom.xml
scripts/hudson/narayana.sh

JDK11
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB PERF !LRA !DB_TESTS mysql db2 postgres oracle

Use JMS 2 API for javadoc creation and set the WORKSPACE for the performance testing

---

rts/lra/test/pom.xml

https://issues.redhat.com/browse/JBTM-3607
!JDK8 JDK11
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS mysql db2 postgres oracle
Thanks @jmfinelli for the pom changes

JBTM-3607 force participant and coordinator to use distinct stores

---

.github/workflows/lra-test.yml
.gitignore
rts/lra/test/arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/NarayanaLRARecovery.java
rts/lra/test/pom.xml
scripts/hudson/narayana.sh

This should be considered to be merged after #1972.
There are various changes in it, to remove the ones that are in #1972 you can view: https://github.com/jbosstm/narayana/compare/JBTM-3590..tomjenkinson:JBTM-3590-debug
!JDK8 JDK11
CORE !TOMCAT AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS mysql db2 postgres oracle

Local development and CI changes

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/test/basic/pom.xml
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/OpenAPIIT.java
rts/lra/test/pom.xml

https://issues.redhat.com/browse/JBTM-3596
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS mysql db2 postgres oracle
Follows up on https://github.com/jbosstm/narayana/pull/1966

JBTM-3596 Includes a test to verify current behaviour for WildFly for OpenAPI

---

qa/TaskImpl.properties.template
qa/pom.xml

Addresses [JBTM-3633](https://issues.redhat.com/browse/JBTM-3633)
Passed:
!CORE !QA_JTS_OPENJDKORB !QA_JTA
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTS_JACORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3633] netty removed from the QA module

---

ArjunaJTS/orbportability/classes/com/arjuna/orbportability/ORBType.java

Addresses [JBTM-3635](https://issues.redhat.com/browse/JBTM-3635)
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3635] Removed orbix2000, hporb and visibroker

---

ArjunaJTS/idl/idlj-openjdk/pom.xml
ArjunaJTS/idl/pom.xml
ArjunaJTS/integration/pom.xml
ArjunaJTS/jtax/pom.xml
ArjunaJTS/jts/pom.xml
ArjunaJTS/orbportability/pom.xml
ArjunaJTS/pom.xml

Addresses [JBTM-3630](https://issues.redhat.com/browse/JBTM-3630)
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3630] sortpom applied to ArjunaJTS

---

scripts/hudson/narayana.sh

Running on a profile that I hope doesn't take too long, problem is also seen on CORE, XTS,  JACOCO and AS_TESTS
!CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle

CI SCRIPT: Do not try to force --ff-only

---

pom.xml
rts/at/pom.xml
rts/pom.xml

Advertise the current site and use HTTPS for some URLs

---

narayana-release-process.sh

RELEASE SCRIPT: Don't login to docker.io but do login to quay.io early

---

rts/lra/client/pom.xml
rts/lra/client/src/main/resources/META-INF/services/javax.ws.rs.client.ClientBuilder

https://issues.redhat.com/browse/JBTM-3648
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3648 LRA not usable in user deployments

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ClientLRARequestFilter.java
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ClientLRAResponseFilter.java
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/service-base/pom.xml
rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java

https://issues.redhat.com/browse/JBTM-3655
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3655 A few changes required for Quarkus LRA TCK runs

---

XTS/localjunit/xtstest/src/org/jboss/jbossts/xts/servicetests/bean/XTSServiceTestRunnerBean.java

To try to understand https://issues.redhat.com/browse/JBTM-3652 more.
!JDK11 JDK17
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle

Added some logging in tests regarding JBTM-3652

---

ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/ibmorb/recoverycoordinators/ClientForwardInterceptor.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/ibmorb/recoverycoordinators/ClientInitializer.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/ibmorb/recoverycoordinators/JavaIdlRCDefaultServant.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/ibmorb/recoverycoordinators/JavaIdlRCManager.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/ibmorb/recoverycoordinators/JavaIdlRCServiceInit.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/ibmorb/recoverycoordinators/ServerInitializer.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/ibmorb/recoverycoordinators/ServerRecoveryInterceptor.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/javaidl/recoverycoordinators/ClientForwardInterceptor.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/javaidl/recoverycoordinators/ClientInitializer.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/javaidl/recoverycoordinators/JavaIdlRCDefaultServant.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/javaidl/recoverycoordinators/JavaIdlRCManager.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/javaidl/recoverycoordinators/JavaIdlRCServiceInit.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/javaidl/recoverycoordinators/ServerInitializer.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/orbspecific/javaidl/recoverycoordinators/ServerRecoveryInterceptor.java
ArjunaJTS/jts/classes/com/arjuna/ats/jts/logging/jtsI18NLogger.java

Addresses [JBTM-3629](https://issues.redhat.com/browse/JBTM-3629)
Tests that should be run (to avoid wasting resources on our CI, I will wait for a first review before running QA_* tests - Thanks @mmusgrov, I will run the other two tests):
CORE QA_JTA QA_JTS_OPENJDKORB
Skipped:
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3629] Renamed/Deleted log messages related to JacORB

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java

Addresses [JBTM-3645](https://issues.redhat.com/browse/JBTM-3645)
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3645] Made it clear that ObjStoreBrowser should be considered singleton

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/objectstore/TestBase.java

https://issues.redhat.com/browse/JBTM-3654
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3654 Refactor JAX-RS in LRA Coordinator to use discovery

---

rts/lra/client-jakarta/pom.xml
rts/lra/client/pom.xml
rts/lra/coordinator-jakarta/pom.xml
rts/lra/coordinator/pom.xml
rts/lra/jaxrs-jakarta/pom.xml
rts/lra/jaxrs/pom.xml
rts/lra/pom.xml
rts/lra/proxy-jakarta/api-jakarta/pom.xml
rts/lra/proxy-jakarta/pom.xml
rts/lra/proxy/api/pom.xml
rts/lra/service-base-jakarta/pom.xml
rts/lra/service-base/pom.xml

https://issues.redhat.com/browse/JBTM-3595
The PR uses bytecode transformation to generate jakarta versions of the LRA maven artifacts.
JDK17 LRA
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF  !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3595 jakarta transformed LRA artifacts

---

scripts/hudson/narayana.sh

!CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle

JBTM-3664 Change the use of AS_TEST to AS_TESTS

---

build-release-pkgs.xml

NO_TEST
Addresses [this](https://github.com/jbosstm/narayana.io/pull/54#discussion_r945543337) comment.

[SCRIPT_ONLY] Changed 'delete dir' to 'delete file' in ant build script to release pkgs

---

common/pom.xml
osgi/jta/pom.xml
pom.xml

Addresses [JBTM-3687](https://issues.redhat.com/browse/JBTM-3687)
JDK11 JDK17 CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3687] - Migrate Common to Jakarta

---

ArjunaJTA/jms/pom.xml
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/JMSContextIntegrationTest.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/JmsIntegrationTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/integration/JmsRecoveryIntegrationTests.java

https://issues.redhat.com/browse/JBTM-3697

[JBTM-3697] Migrate jms tests to jakarta

---

pom.xml

!CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS mysql db2 postgres oracle

Upgrade Quarkus to 2.12.1.Final

---

ArjunaJTA/jta/pom.xml
scripts/hudson/narayana.sh

https://issues.redhat.com/browse/JBTM-3683
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle
!JDK17

JBTM-3683: Deal with new arqPIv6 profile for jta module

---

scripts/hudson/narayana.sh

https://issues.redhat.com/browse/JBTM-3665
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle

JBTM-3665 Increase the testing of the integrated Narayana with the WildFly version

---

ArjunaJTA/cdi/etc/META-INF/services/jakarta.enterprise.inject.spi.Extension
ArjunaJTA/cdi/pom.xml
ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/TransactionalImplTest.java
ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/StereotypeChangedByExtensionTest.java
ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/TransactionalChangedByExtensionTest.java
ArjunaJTA/cdi/tests/classes/com/hp/mwtests/ts/jta/cdi/transactional/stereotype/extension/TransactionalInterceptorFactoryTest.java
ArjunaJTA/jta/pom.xml
ArjunaJTA/spi/pom.xml
compensations/pom.xml
compensations/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
pom.xml
rts/at/bridge/pom.xml
rts/at/integration/pom.xml
rts/at/webservice/pom.xml
rts/lra/test/pom.xml
rts/sra/src/main/resources/META-INF/services/jakarta.ws.rs.ext.Providers
txframework/pom.xml
txframework/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension

This PR is intended to restore META_INF/services removed from transformation. Those file are been migrated to jakarta
This commits fix cdi errors and rest-AT bridge AnnotationsTestCase.
The wildfly source used is https://github.com/jbosstm/jboss-as/pull/87

JBTM 3588, cdi needs Extension files

---

ArjunaJTA/narayana-jta-jakarta/pom.xml

https://issues.redhat.com/browse/JBTM-3713
To Test
JDK17 CORE QA_JTA
Skipped
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3713 Upgrade jakarta.transaction-api from 2.0.0 to 2.0.1 in ArjunaJTA/narayana-jta-jakarta/pom.xml

---

txframework/src/main/java/org/jboss/narayana/txframework/impl/Participant.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/ServiceInvocationMeta.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/TXDataMapImpl.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/as/TXFrameworkCDIExtension.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/handlers/HandlerFactory.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/handlers/ParticipantRegistrationException.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/handlers/ProtocolHandler.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/handlers/UnsupportedProtocolException.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/handlers/wsba/WSBACoordinatorCompletionParticipant.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/handlers/wsba/WSBAHandler.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/handlers/wsba/WSBAParticipantCompletionParticipant.java
txframework/src/main/java/org/jboss/narayana/txframework/impl/handlers/wsba/WSBATxControlImpl.java

Starting the process to complete [JBTM-2221](https://issues.redhat.com/browse/JBTM-2221)
NO_TEST

[JBTM-2221] Deprecated txframework implementation

---

scripts/hudson/narayana.sh

Sorry, some leftover from previous commit.
NO_TEST

[SCRIPT_ONLY] Replaced git with https when 'git clone' (leftover)

---

narayana-full/src/main/assembly/bin.xml
rts/lra/pom.xml

CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3658 skip building the lra-coordinator-quarkus module

---

qa/pom.xml
qa/run-tests.xml

Addresses [JBTM-3720](https://issues.redhat.com/browse/JBTM-3720)
JDK17 JACOCO
!CORE !TOMCAT !AS_TESTS !RTS !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3720] JACOCO axis fixed

---

build-release-pkgs.xml
narayana-release-process.sh

The commits should be evaluated separately
NO_TEST
/cc @mmusgrov

Release process changes

---

CODEOWNERS
CONTRIBUTING.md
README.md
SECURITY.md

https://issues.redhat.com/browse/JBTM-3715
NO_TEST

JBTM-3715 Improve inclusiveness by building a community of users

---

.github/workflows/lra-test.yml
ArjunaJTA/jta/src/test/resources/arquillian.xml
ArjunaJTS/jts/tests/classes/com/hp/mwtests/ts/jts/remote/transactionserver/TMClient.java
CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md
README.md
STM/README.md
build-release-pkgs.xml
ext/Readme
qa/config/jdbc_profiles/default/JDBCProfiles
scripts/hudson/narayana-rebase.bat
scripts/hudson/narayana-rebase.sh
scripts/hudson/narayana.sh
scripts/pre-release-vars.sh
vertx/README.md

Ensure that the narayana project is following best practices and recommendations in relation to the use of Conscious Language.
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

[JBTM-3718] Conscious Language

---

narayana-full/readme.txt

JBTM-3729 Refer to the zip by tag

---

pom.xml

Update reasteasy version
CORE !TOMCAT AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

Update reasteasy version

---

narayana-release-process.sh

NO_TEST
There are two changes:
* Correct some bash so that it will use "if "
* Allow the upload the quay.io to be controlled on the command line

Changes to the release script

---

narayana-full/pom.xml
pom.xml

https://issues.redhat.com/browse/JBTM-3748
CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERF LRA

JBTM-3748 remove trailing reference to jboss-corba-ots-spi dependency

---

ArjunaJTA/cdi/pom.xml
ArjunaJTA/jdbc/pom.xml
ArjunaJTA/jms/pom.xml
ArjunaJTA/jta/pom.xml
ArjunaJTA/narayana-jta/pom.xml
ArjunaJTA/spi/pom.xml
ArjunaJTS/integration/pom.xml
ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/BaseTransactionManagerDelegate.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/jta/TransactionManagerDelegate.java
ArjunaJTS/integration/src/main/java/com/arjuna/ats/jbossatx/jta/TransactionManagerService.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/spi/SPIUnitTest.java
ArjunaJTS/jtax/pom.xml
ArjunaJTS/narayana-jts-idlj/pom.xml
narayana-full/pom.xml
pom.xml
qa/pom.xml
rts/at/bridge/pom.xml
txbridge/pom.xml

https://issues.redhat.com/browse/JBTM-3722
CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERF LRA DB_TESTS mysql db2 postgres oracle

JBTM-3722 jboss-transactions-spi component upgrade

---

ArjunaJTA/cdi/pom.xml
pom.xml

This PR solves the bug introduced in commit e5e054a81bcb6728b8c4a39cc50f02bce00ff884 (PR #2083)
JDK17
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

Fixed smallrye-converter-api

---

rts/at/tx/pom.xml

Removing duplicated dependency in restat-api project
CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

Removing duplicated dependency

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ClientLRARequestFilter.java
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/service-base/src/main/java/io/narayana/lra/Current.java

https://issues.redhat.com/browse/JBTM-3749
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle
This is the least intrusive way to address also the problem stated in https://issues.redhat.com/browse/JBTM-3552. Let me know if it's sufficient and we can resolve also https://issues.redhat.com/browse/JBTM-3552 with this fix.

JBTM-3749 Changes required for LRA integration in WildFly

---

rts/lra/client/src/main/resources/META-INF/beans.xml
rts/lra/coordinator/src/main/resources/META-INF/beans.xml
rts/lra/jaxrs/src/main/resources/META-INF/beans.xml
rts/lra/proxy/api/src/main/resources/META-INF/beans.xml
rts/lra/proxy/test/src/main/resources/META-INF/beans.xml
rts/sra/src/main/resources/META-INF/beans.xml

https://issues.redhat.com/browse/JBTM-3756
LRA

JBTM-3756 update bean discovery mode in lra-client

---

scripts/hudson/narayana.sh

CORE LRA AS_TESTS QA_JTA
!TOMCAT !RTS !JACOCO !XTS !QA_JTS_OPENJDKORB !PERF !DB_TESTS !mysql !db2 !postgres !oracle
This PR is for improving `narayana.sh`, especially when running it locally. Please note that I set up the `main` branch to be the default of the repo [jboss-as](https://github.com/jbosstm/jboss-as)

[SCRIPT_ONLY] Removed JBOSS_HOME from narayana.sh

---

.github/workflows/lra-test.yml

!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS mysql db2 postgres oracle

CI SCRIPT ONLY: Include files from WildFly standalone logs folder and separate the artifacts from the different Java versions

---

scripts/hudson/narayana.sh

QA_JTA
when QA tests fails should exit the script with an error code.
Other error to be solved

[script] QA_TEST script fix

---

narayana-bom/pom.xml
pom.xml
rts/lra/client/src/main/java/io/narayana/lra/client/LRAParticipantData.java
rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/coordinator/pom.xml
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/coordinator/src/main/resources/META-INF/microprofile-config.properties
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ProxyService.java
rts/lra/service-base/src/main/java/io/narayana/lra/LRAConstants.java
rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/FailedLRAIT.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/NonRootLRAParticipantIT.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/ParticipantDataIT.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/TestBase.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/api/CoordinatorApiIT.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/resource/ParticipantDataResource.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/resource/ParticipantDataResource2.java

https://issues.redhat.com/browse/JBTM-3755
I removed the axes to test because the last commit was a formatting change
I'll follow up with a docs update once it's passed review.

JBTM-3755 Support for passing participant data to LRA callbacks

---

qa/tests/build.xml

(https://issues.redhat.com/browse/JBTM-3769)

[JBTM-3769] split sources and jars in qa external libraries

---

qa/tests/build.xml

Revert "[JBTM-3769] split sources and jars in qa external libraries"

---

narayana-bom/pom.xml
pom.xml
vertx/shared/pom.xml

https://issues.redhat.com/browse/JBTM-3771
IMPORTANT! At the moment, our CI is not able to trigger test axis automatically. As a result, your PR might take some time to be tested. We apologize for the inconvenience and appreciate your understanding. Thanks.
By default the pull request will run with `JDK11`, if you prefix a `!` to `JDK11` then it …

JBTM-3771: Remove vertx in narayana-bom

---

narayana-bom/pom.xml
pom.xml
rts/lra/coordinator/pom.xml

https://issues.redhat.com/browse/JBTM-3770
IMPORTANT! At the moment, our CI is not able to trigger test axis automatically. As a result, your PR might take some time to be tested. We apologize for the inconvenience and appreciate your understanding. Thanks.
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres !oracle
By default the pull request will run with `JDK11`, if you prefix a `!` to …

JBTM-3770: Upgrade smallrye-config

---

pom.xml
rts/at/tx/pom.xml
rts/at/tx/src/test/java/org/jboss/jbossts/star/test/BaseTest.java

Issue: https://issues.redhat.com/browse/JBTM-3758
CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERFORMANCE LRA DB_TESTS mysql db2 postgres oracle JDK17 JACOCO

[JBTM-3758] Missing test for Short Running Actions (SRA) on Quarkus

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqJournalStore.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqObjectStoreAdaptor.java
qa/tests/src/org/jboss/jbossts/qa/junit/testgroup/TestGroup_crashrecovery12.java

https://issues.redhat.com/browse/JBTM-3773
https://issues.redhat.com/browse/JBEAP-24676
There is no functional change hence no need for any testing.
Feel free to reject if you think the new trace level messages are confusing.

JBTM-3773 update Hornetq trace level messages

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/hornetq/HornetqObjectStoreAdaptor.java

NO_TEST
leftover from [JBMT-3773](https://github.com/jbosstm/narayana/pull/2116)

[JBTM-3773] leftover

---

qa/pom.xml

Addresses [JBTM-3777](https://issues.redhat.com/browse/JBTM-3777)
JDK17 CORE !TOMCAT !AS_TESTS !RTS JACOCO !XTS QA_JTA QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS

[JBTM-3777] Transitive dependencies are copied in qa/ext

---

CODEOWNERS

CODEOWNERS removed

---

narayana-bom/pom.xml
rts/lra/proxy/api/pom.xml
rts/lra/proxy/test/pom.xml

https://issues.redhat.com/browse/JBTM-3776

[JBTM-3776] Remove dependencies' scope in the Narayana bom

---

rts/at/tx/src/main/java/org/jboss/jbossts/star/client/SRAParticipant.java

Issue: https://issues.redhat.com/browse/JBTM-3489

[JBTM-3489] REST-AT annotation demo ends in the wrong state

---

rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/ParticipantDataIT.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/resource/ParticipantDataResource2.java

JBTM-3755 
header must be a string
adding data header only when needed

JBTM-3755 converting StringBuilder into String

---

pom.xml

Needed update for quickstart queue fix

arquillian update

---

ArjunaCore/arjuna/pom.xml

[JBTM-3735](https://issues.redhat.com/browse/JBTM-3735)
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA DB_TESTS mysql db2 postgres oracle

[JBTM-3735] removed jdbc versions from arjuna

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/StateManager.java

[JBTM-3790](https://issues.redhat.com/browse/JBTM-3790)

[JBTM-3790] Add creationTimeMillis as bean property to replace internal birthDate local variable

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/StateManager.java

https://issues.redhat.com/browse/JBTM-3790
CORE
Fix for syntax error caused by pr/2149.

JBTM-3790 fix syntax error introduced by last PR

---

rts/at/tx/src/main/java/org/jboss/jbossts/star/client/SRAClient.java

https://issues.redhat.com/browse/JBTM-3791
CORE

JBTM-3791 don't read the entity body twice

---

build-release-pkgs.xml

This PR disables automatic update of the website source.
The Narayana team is currently manually managing the update of the website
A new PR with the new script will follow as soon as it is tested and working.
NO_TESTS

comment out automatic website update

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
rts/lra/test/pom.xml

https://issues.redhat.com/browse/JBTM-3795
LRA

JBTM-3795 recover memory when an LRA terminates

---

narayana-bom/pom.xml
pom.xml
rts/at/tx/pom.xml

Issue: https://issues.redhat.com/browse/JBTM-3785
CORE TOMCAT AS_TESTS RTS !JACOCO XTS QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS
jmfinelli: Testing axis modified

[JBTM:3785] Upgrade Servlet API from 5.0.0 to 6.0.0 in the BOM

---

ArjunaCore/arjuna/pom.xml
narayana-bom-test/pom.xml

https://issues.redhat.com/browse/JBTM-3806

JBTM-3806 enable JUnit 5 plus JUnit 4 testing

---

PULL_REQUEST_TEMPLATE.md

Sorry for the inconvenience, the CI jobs are now automatically started.
NO_TEST

CI triggers automatically axis again

---

CONTRIBUTING.md

Added the new RFE workflow to CONTRIBUTING.md

---

CONTRIBUTING.md

This PR adds information for hacktoberfest:
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO XTS QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS !mysql !db2 !postgres !oracle

hacktoberfest

---

narayana-bom-test/pom.xml
narayana-bom/pom.xml

NO_TEST
This PR addresses Laird's forum question in 'narayana-users' conversation "[Why does the Narayana BOM feature third-party dependencies?](https://groups.google.com/g/narayana-users/c/CCWr8ZBIe_Q)"
I added comment for Narayana BOMs in order to clarify their function

Describe Narayana's BOMs usage and function

---

narayana-full/pom.xml

https://issues.redhat.com/browse/JBTM-3813

JBTM-3813 exclude artemis from javadoc

---

narayana-bom-test/pom.xml

Update h2 version to 2.2.224
CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS QA_JTA QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres !oracle

Update h2 version

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/objectstore/StoreManager.java
common/classes/com/arjuna/common/internal/util/ClassloadingUtility.java
common/classes/com/arjuna/common/logging/commonI18NLogger.java

https://issues.redhat.com/browse/JBTM-3817
This PR reports the reason for store initialisation failures.

Jbtm 3817 Store initialisation code does not report the reason for failures

---

narayana-bom-test/pom.xml
narayana-bom/pom.xml

https://issues.redhat.com/browse/JBTM-3819
CORE !TOMCAT !AS_TESTS !RTS !JACOCO XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3819 sortpom

---

narayana-bom-test/pom.xml
narayana-bom/pom.xml
rts/at/bridge/pom.xml

related to issue https://github.com/quarkusio/quarkus/issues/36882 
CORE !TOMCAT !AS_TESTS RTS !JACOCO XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS

Move jakarta-ejb-api to narayana-bom-test.

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/AdvancedAtomicActionExpiryScanner.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/AdvancedAtomicActionPurgeExpiryScanner.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/BasicActionExpiryScanner.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/BasicActionExpiryScannerTest.java

https://issues.redhat.com/browse/JBTM-3801

JBTM-3801 Add advanced ActionExpiryScanner based on creation date for expiry evaluation

---

ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/BasicActionExpiryScannerTest.java

JBTM-3801 Fix JavaDoc of test class

---

narayana-bom-test/pom.xml
narayana-bom/pom.xml

CORE !TOMCAT !AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS

Move io.quarkus:quarkus-resteay to narayana-bom-test

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParentAbstractRecord.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java

https://issues.redhat.com/browse/JBTM-3816
LRA !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3816 recovery for co-located nested LRAs

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/objectstore/jdbc/accessors/SimplePooledDynamicDataSourceJDBCAccess.java

https://issues.redhat.com/browse/JBTM-3823
Use synchronizedList because it is thread safe.
CORE !TOMCAT !AS_TESTS !RTS !JACOCO! XTS QA_JTA QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS JDK17

[JBTM-3823] fix ArrayIndexOutOfBoundsException in QA

---

CONTRIBUTING.md

The PR includes:
- guidelines for estimating bug fixes (I didn't create a discussion for this item since it is not mandatory, although any engineer can provide estimates)
- license header fix
- minor formatting fix
!LRA !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS !mysql !db2 !postgres !oracle

Ask contributors to provide estimates when fixing issues

---

ArjunaJTS/jtax/pom.xml

NO_TEST
https://groups.google.com/g/narayana-users/c/9JfyanG4XXg/m/4-krX-piAAAJ?utm_medium=email&utm_source=footer

RELEASE SCRIPT: Deploy jtax to nexus

---

rts/pom.xml

https://issues.redhat.com/browse/JBTM-3835
CORE !TOMCAT AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS

JBTM-3835 Move building of `lra` out of the community profile

---

rts/pom.xml

https://issues.redhat.com/browse/JBTM-3834
Note: this PR is against 6.0 branch
CORE !TOMCAT AS_TESTS RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS

JBTM-3834 (6.0) Move building of `lra` out of the community profile

---

narayana-release-process.sh

RELEASE SCRIPT ONLY: Do not do quay.io release or deploy to nexus

---

narayana-release-process.sh

Try to install Narayana and then try to deploy it

---

ArjunaJTS/jtax/pom.xml

BUILD SCRIPT ONLY: Commit sorted pom

---

qa/tests/src/org/jboss/jbossts/qa/JDBCResources01Cleanups/Cleanup01.java
qa/tests/src/org/jboss/jbossts/qa/JDBCResources02Cleanups/Cleanup01.java
qa/tests/src/org/jboss/jbossts/qa/JDBCResources03Cleanups/Cleanup01.java
qa/tests/src/org/jboss/jbossts/qa/JDBCResources04Cleanups/Cleanup01.java

CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS QA_JTA QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS

Remove comparison with ==, use equals instead for string

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParentAbstractRecord.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java

https://issues.redhat.com/browse/JBTM-3845
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3845 keep LRA cache up to date

---

ArjunaCore/pom.xml
ArjunaJTA/cdi/pom.xml
ArjunaJTA/jdbc/pom.xml
ArjunaJTA/jms/pom.xml
ArjunaJTA/jta/pom.xml
ArjunaJTA/narayana-jta/pom.xml
ArjunaJTA/spi/pom.xml
ArjunaJTS/pom.xml
CONTRIBUTING.md
common/pom.xml
compensations/pom.xml
rts/at/pom.xml
rts/lra/pom.xml
tools/pom.xml
txbridge/pom.xml
vertx/pom.xml

https://issues.redhat.com/browse/JBTM-3847 
Enable checkstyle by default
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS

[JBTM-3847] Enable checkstyle by default

---

pom.xml

https://issues.redhat.com/browse/JBTM-3854
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3854 Upgrade Jandex from 3.0.5 to 3.1.7

---

ArjunaJTA/spi/src/test/java/io/narayana/spi/usertx/TestUTSerializability.java
ArjunaJTS/integration/src/test/java/io/narayana/spi/usertx/JndiProvider.java
ArjunaJTS/integration/src/test/java/io/narayana/spi/usertx/SPIUnitTest.java

https://issues.redhat.com/browse/JBTM-3793
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS mysql db2 postgres oracle

JBTM-3793 Moved from https://github.com/jbosstm/jboss-transaction-spi

---

ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/xa/RMFAILOutofRollbackResource.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/xa/XAResourceRecoveryTest.java

https://issues.redhat.com/browse/JBTM-3838
CORE !TOMCAT AS_TESTS !RTS !JACOCO !XTS QA_JTA QA_JTS_OPENJDKORB PERFORMANCE !LRA DB_TESTS mysql db2 postgres oracle

JBTM-3838 Review JTS and JTA way to handle RMFAIL in xa_rollback

---

ArjunaJTS/orbportability/classes/com/arjuna/orbportability/common/ant/IDLBuildList.java
ArjunaJTS/orbportability/classes/com/arjuna/orbportability/common/ant/IDLBuildListElement.java
ArjunaJTS/orbportability/classes/com/arjuna/orbportability/common/ant/IDLCompiler.java

https://issues.redhat.com/browse/JBTM-3855
!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS mysql db2 postgres oracle

JBTM-3855 Deprecate some code for removal

---

tools/src/main/java/io/narayana/perf/Measurement.java

https://issues.redhat.com/browse/JBTM-3853
CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA DB_TESTS mysql db2 postgres oracle

[JBTM-3853] Performance test hanging

---

qa/pom.xml
scripts/hudson/narayana.sh

(possibly partial) https://issues.redhat.com/browse/JBTM-3829
!CORE !TOMCAT !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS mysql db2 postgres oracle

JBTM-3829 jacoco-report throws error (and doesn't fail)

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/tools/ObjStoreBrowserTest.java

https://issues.redhat.com/browse/JBTM-3859

JBTM-3859 MBean for JTA transaction heuristics is imprecise

---

scripts/hudson/narayana.sh

https://issues.redhat.com/browse/JBTM-3867
JDK17

[JBTM-3867] CI: Do not use WildFly latest with Java 11

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/ObjStoreBrowserTest.java

https://issues.redhat.com/browse/JBTM-3859

JBTM-3859 clear MBean cache before probing

---

ArjunaJTA/cdi/pom.xml
ArjunaJTA/jta/pom.xml
ArjunaJTA/spi/pom.xml
XTS/localjunit/pom.xml
compensations/pom.xml
narayana-bom/pom.xml
pom.xml
rts/at/bridge/pom.xml
rts/at/integration/pom.xml
rts/at/pom.xml
rts/at/webservice/pom.xml
rts/lra/coordinator/pom.xml
txbridge/pom.xml

https://issues.redhat.com/browse/JBTM-1801
CORE !TOMCAT AS_TESTS RTS !JACOCO XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS mysql db2 postgres oracle

Jbtm 1801 Move all test properties into root pom.xml

---

code-coverage/pom.xml
compensations/pom.xml

https://issues.redhat.com/browse/JBTM-3877
NOTE: this PR is against 6.0 branch
CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERFORMANCE LRA DB_TESTS
JDK17

[JBTM-3877] Compensation is removed from WildFly, disable integration tests in Narayana 6.0

---

CONTRIBUTING.md

[JBTM-3856](https://issues.redhat.com/browse/JBTM-3856)
NO_TEST

[JBTM-3856] Mentioned Semantic Versioning Specification (SemVer) in CONTRIBUTING.md

---

.gitignore
PULL_REQUEST_TEMPLATE.md
narayana-full/pom.xml
scripts/hudson/narayana.sh

https://issues.redhat.com/browse/JBTM-3887
CORE !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS

[JBTM-3887] Remove tomcat dependencies and references from Narayana

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/transaction/arjunacore/TransactionImple.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/lastresource/LastResourceDisallowTestCase.java

https://issues.redhat.com/browse/JBTM-3882
CORE !TOMCAT !AS_TESTS !RTS! JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS! mysql !db2 !postgres !oracle

JBTM-3882 Report the reason for one phase enlist failures

---

scripts/pre-release.sh

RELEASE SCRIPT ONLY: Tag the quickstart repo

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/ActionManager.java

[JBTM-3897](https://issues.redhat.com/browse/JBTM-3897)

[JBTM-3897] Removed 'getTimeAdded' and related class 'Lifetime'

---

narayana-release-process.sh

NO_TESTS
related to https://issues.redhat.com/browse/JBTM-3888

Updated with latest release steps and checks for 6.0 branch

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/ActionManager.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/atomicaction/TxStatsUnitTest.java

[JBTM-3899](https://issues.redhat.com/browse/JBTM-3899)

[JBTM-3899] Fixed getNumberOfInflightTransactions

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/ActionManager.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/atomicaction/TxStatsUnitTest.java

Style changes following JBTM-3899 and JBTM-3897
NO_TEST

[STYLE] AtomicManager and TxStatsUnitTest reformatted

---

README.md

https://issues.redhat.com/browse/JBTM-3906
NO_TEST
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3906 Support guarantees

---

rts/lra/test/basic/src/test/resources/META-INF/services/jakarta.ws.rs.ext.Providers

(cherry picked from commit dd2f32eed87065f975e29282d59c2f0110d8f545)
CORE AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERFORMANCE LRA DB_TESTS mysql db2 postgres oracle
Pull requests build and run with JDK11 and JDK17. Add the prefix `!` to disable these defaults. Include the text `JDK21` to build and run with JDK21
If it is determined that nothing needs to be tested for the pull request then you need to concatenate the two sets of characters: `NO_` …

[JBTM-3902] move duplicate provider definition into test resources

---

pom.xml

https://issues.redhat.com/browse/JBTM-3909
NO_TESTS

JBTM-3909: Disable the flag autoReleaseAfterClose for maintenance branch 6.0

---

pom.xml

https://issues.redhat.com/browse/JBTM-3909
NO_TESTS

JBTM-3909: Disable the flag autoReleaseAfterClose for maintenance branch 5.11

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java

JBTM-3910 Add condition to check the participant was enlisted while executing joinLRA
https://issues.redhat.com/browse/JBTM-3910
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS

JBTM-3910 Add condition to check the participant was enlisted

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/RecoveryEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/RecoveryEnvironmentBeanMBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/TransactionReaper.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoverAtomicAction.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryManager.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryModule.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/AtomicActionRecoveryModule.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java
ArjunaCore/arjuna/pom.xml
ArjunaCore/arjuna/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_BytemanControlledRecord.btm
ArjunaCore/arjuna/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_FailTest.btm
ArjunaCore/arjuna/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_PeriodicRecovery.btm
ArjunaCore/arjuna/tests/byteman-scripts/reaper.btm
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/RecoverySuspendTest.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/resources/BytemanControlledRecord.java
narayana-bom-test/pom.xml

[JBTM-3894](https://issues.redhat.com/browse/JBTM-3894)

JBTM-3894 The new PoC is now working as the Narayana team requested

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATestBase.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRAWithParticipantsTest.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/tools/osb/mbean/ObjStoreBrowserLRATest.java
rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java

https://issues.redhat.com/browse/JBTM-3924
This is a backport of https://issues.redhat.com/browse/JBTM-3911 for 6.0 branch
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS

Jbtm 3924 (6.0) Replace synchronized in favor of Reentrant Lock in LRAService joinLRA method

---

rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/client/LRAAsyncIT.java

[JBTM-3928](https://issues.redhat.com/browse/JBTM-3928)
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS
!JDK11

Update LRAAsyncIT to use thread safe logic

---

ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/resources/arjunacore/XAResourceRecord.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/common/JTAEnvironmentBean.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/common/JTAEnvironmentBeanMBean.java
ArjunaJTA/jta/classes/com/arjuna/ats/jta/logging/jtaI18NLogger.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/common/FailureXAResource.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/twophase/XAResourceRecordUnitTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/xa/JTATest.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/SimpleIsolatedServers.java
ArjunaJTS/integration/src/test/java/com/arjuna/ats/jta/distributed/TestResource.java
ArjunaJTS/jtax/classes/com/arjuna/ats/internal/jta/resources/jts/orbspecific/XAResourceRecord.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/xa/JTSTest.java
qa/tests/src/org/jboss/jbossts/qa/CrashRecovery12Resources/Resource01.java

[JBTM-3843](https://issues.redhat.com/browse/JBTM-3843)
Full pass:
!CORE !RTS !QA_JTA !QA_JTS_OPENJDKORB !DB_TESTS !XTS !LRA  !AS_TESTS 
No needed:
!JACOCO !PERFORMANCE

[JBTM-3843] Rollback is no longer invoked in all cases

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/DummyRecoveryModule.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/RecoverySuspendLoggingCheckTest.java

Bug in when displaying a warning

[JBTM-3894] Fixed a bug when displaying a warning

---

rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATestBase.java

https://issues.redhat.com/browse/JBTM-3356
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres oracle !JDK17

JBTM-3356 Verify that unacknowledged AfterLRA callbacks are redelivered

---

rts/lra/client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRAWithParticipantsTest.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/objectstore/TestBase.java
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/proxy/api/src/main/java/io/narayana/lra/client/internal/proxy/ProxyService.java
rts/lra/proxy/test/src/test/java/io/narayana/lra/participant/SpecTest.java
rts/lra/test/arquillian-extension/src/main/java/io/narayana/lra/arquillian/appender/MpLraTckAuxiliaryArchiveAppender.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/Deployer.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/TestBase.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/client/LRAIT.java
rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/resource/LRAParticipant.java
rts/lra/test/crash/src/test/java/io/narayana/lra/arquillian/LRACoordinatorRecoveryIT.java

https://issues.redhat.com/browse/JBTM-3934
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres !oracle

JBTM-3934 Move NarayanaLRAClient into an internal package

---

CONTRIBUTING.md

Adds a note about release notes.
NO_TEST

Added guidance on release notes

---

rts/lra/client/src/main/java/io/narayana/lra/client/internal/NarayanaLRAClient.java
rts/lra/coordinator/pom.xml
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/RecoveryCoordinator.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParentAbstractRecord.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LRAParticipantRecord.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/model/LongRunningAction.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/domain/service/LRAService.java
rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/internal/RecoveringLRA.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/BytemanHelper.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATest.java
rts/lra/coordinator/src/test/java/io/narayana/lra/coordinator/domain/model/LRATestBase.java
rts/lra/coordinator/src/test/resources/scripts/transition-active-failure.btm
rts/lra/jaxrs/src/main/java/io/narayana/lra/filter/ServerLRAFilter.java
rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java

https://issues.redhat.com/browse/JBTM-3945
@marcosgopen This PR adds checks for object store write failures. I have only included tests for starting and enlisting with LRAs but I have another dozen or so fault injection test scenarios to write (I'll document them on the JBTM) but the required code changes are in this PR and any bugs I uncover with the extra failure scenarios should be less intrusive so another member of the team can review those while you are away.
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS !mysql !db2 !postgres oracle
!JDK11 !JDK21

JBTM-3945 handle store write errors

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/AtomicActionRecoveryModule.java

[JBTM-3894](https://issues.redhat.com/browse/JBTM-3894)
AtomicActionRecoveryModule needs to try recovery again when there are problems

[JBTM-3894] AtomicActionRecoveryModule needs to try recovery again when there are problems

---

ArjunaCore/arjuna/pom.xml

Removed duplicated dependency

---

pom.xml
qa/pom.xml

!CORE !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS mysql db2 postgres oracle
Pull requests build and run with JDK17 and JDK21. Add the prefix `!` to disable these defaults.
If it is determined that nothing needs to be tested for the pull request then you need to concatenate the two sets of characters: `NO_` `TEST` as a single word and provide the result into the description.
Please be aware that none of this configuration …

Update to JaCoCo 0.8.12

---

ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/RecoverySuspendTest.java

JBTM-3894: Removed useless instruction

Removed useless instruction

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/OSBTypeHandler.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/UidWrapper.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/ExposeAllLogsTest.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/NotExposeAllLogsTest.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/ObjStoreBrowserTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceMBeansFailAfterPrepare.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/tools/ObjStoreBrowserTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/jca/XATerminatorImpleUnitTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSOSBTestBase.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSObjStoreBrowserTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/ObjStoreBrowserTest.java

https://github.com/jbosstm/jboss-as/pull/95/
https://issues.redhat.com/browse/JBTM-3973
CORE AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS

JBTM-3973  ObjectStoreBrowser doesn't allow to register external OSBTypeHandler

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/OSBTypeHandler.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/UidWrapper.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/ExposeAllLogsTest.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/NotExposeAllLogsTest.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/tools/ObjStoreBrowserTest.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable/TestCommitMarkableResourceMBeansFailAfterPrepare.java
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/tools/ObjStoreBrowserTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/jca/XATerminatorImpleUnitTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSOSBTestBase.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/JTSObjStoreBrowserTest.java
ArjunaJTS/jtax/tests/classes/com/hp/mwtests/ts/jta/jts/tools/ObjStoreBrowserTest.java

https://issues.redhat.com/browse/JBTM-3973
CORE AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERFORMANCE !DB_TESTS

Jbtm 3973 backport to 6.0 maintenance branch

---

scripts/hudson/narayana-rebase.sh

[Script only] remove reference to branch 4.17

---

ArjunaJTA/jta/classes/com/arjuna/ats/jta/common/JTAEnvironmentBean.java

https://issues.redhat.com/browse/JBTM-3975
CORE AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS

JBTM-3975 Add the privileged block to invoke loadAndInstantiateClass

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/AbstractRecord.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java
ArjunaJTS/jts/classes/com/arjuna/ats/internal/jts/resources/ExtendedResourceRecord.java

https://issues.redhat.com/browse/JBTM-3881
CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS !mysql !db2 !postgres !oracle !JDK21

backport of JBTM-3881 to the 7.1 branch

---

ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/AtomicActionRecoveryModule.java

https://issues.redhat.com/browse/JBTM-3980
CORE AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS

[JBTM-3980][JBTM-3894] Fixed bug in AtomicActionRecoveryModule

---

scripts/hudson/narayana.sh

[BUILD SCRIPT] (7.1 branch) fail at end when testing as

---

scripts/hudson/narayana.sh

!CORE AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS  JDK21

[BUILD SCRIPT] fail at end when testing as

---

CONTRIBUTING.md

Guidance on what to expect from pull requests

---

tools/maven/conf/settings.xml

BUILD SCRIPT: Override a few repos with https urls

---

tools/maven/conf/settings.xml

BUILD SCRIPT ONLY: Use a mirror

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/RecoveryEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/AtomicActionRecoveryModule.java
ArjunaCore/arjuna/pom.xml
ArjunaCore/arjuna/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_SwitchAutomatically.btm
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/RecoverySuspendTest.java
ArjunaJTA/jta/pom.xml

[JBTM-3982](https://issues.redhat.com/browse/JBTM-3982)

Boolean introduced

---

ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/RecoveryEnvironmentBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/RecoveryEnvironmentBeanMBean.java
ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/recovery/RecoveryManager.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/AtomicActionRecoveryModule.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/PeriodicRecovery.java
ArjunaCore/arjuna/classes/com/arjuna/ats/internal/arjuna/recovery/RecoveryManagerImple.java
ArjunaCore/arjuna/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_BytemanControlledRecord.btm
ArjunaCore/arjuna/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_FailTest.btm
ArjunaCore/arjuna/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_PeriodicRecovery.btm
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/RecoverySuspendLoggingCheckTest.java
ArjunaCore/arjuna/tests/classes/com/hp/mwtests/ts/arjuna/recovery/RecoverySuspendTest.java
ArjunaJTA/jta/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_BytemanControlledXAResource.btm
ArjunaJTA/jta/tests/byteman-scripts/RecoverySuspendTest/recoverySuspendTest_FailTest.btm
ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/recovery/RecoverySuspendTest.java

[JBTM-3981](https://issues.redhat.com/browse/JBTM-3981)

Overload suspendScan

---

pom.xml
rts/lra/test/arquillian-extension/src/main/java/io/narayana/lra/arquillian/spi/NarayanaLRARecovery.java

https://issues.redhat.com/browse/JBTM-3985

Jbtm 3985 backport to 6.0

---

scripts/hudson/narayana.sh

SCRIPT modification to add an env. variable to use more parameters during WFLY's build process
!CORE AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS

[SCRIPT] added env. variable to use more parameters during WFLY's build process

---

.github/workflows/core-test.yml

GitHub Action to run CORE profile with testing

---

.github/workflows/core-test.yml

GitHub actions conditional

---

pom.xml

CORE AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERFORMANCE DB_TESTS mysql db2 postgres oracle
Pull requests build and run with JDK17 and JDK21. Add the prefix `!` to disable these defaults.
If it is determined that nothing needs to be tested for the pull request then you need to concatenate the two sets of characters: `NO_` `TEST` as a single word and provide the result into the description.
Please be aware that none of this configuration affects …

BUILD SCRIPT: Update to jboss-parent 49

---

narayana-release-process.sh
pom.xml

NO_TEST
Updated where to deploy snapshots to and updated to allow the narayana-release-process.sh script to start to work for Snapshots where tagging is not expected

Updated snapshot deployment and place to deploy to

---

CONTRIBUTING.md

New DCO paragraph in CONTRIBUTING.md
NO_TEST

New wording for the DCO paragraph

---

ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionProxy.java
ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionProxy.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/ConnectionProxyTests.java
ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/SessionProxyTests.java

See issue: https://issues.redhat.com/browse/JBTM-4005

JBTM-4005: Session leak when Synchronization is in aborted state

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

NO_TEST
Added directly to our repo. That being said we need to agree how to approach https://github.com/jbosstm/narayana/compare/main...tomjenkinson:narayana:CODE_OF_CONDUCT?expand=1#diff-fa698b8cfb8bf9319712cd7801032f486e81e8425448f46592a47e83c6d54452R59

[Governance] Add the code of conduct

---

scripts/hudson/narayana.sh

[leftover] renaming PERF profile to PERFORMANCE
!CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB PERFORMANCE !DB_TESTS

[leftover] Update PERF profile to PERFORMANCE

---

rts/at/webservice/pom.xml

[JBTM-3997] restat webservice leftover

---

docs/pom.xml
pom.xml

[JBTM-4008] Excluding docs from the release process and link its pom to narayana-all

---

ArjunaCore/arjuna/pom.xml
ArjunaJTA/jta/pom.xml
ArjunaJTA/spi/pom.xml
ArjunaJTS/jts/pom.xml
pom.xml
rts/at/tx/pom.xml
tools/pom.xml

Jbtm 3997 other fixes

---

ArjunaJTS/orbportability/pom.xml
XTS/WS-C/pom.xml
XTS/WS-T/pom.xml
XTS/WSAS/pom.xml
XTS/WSCF/pom.xml
XTS/WSTX/pom.xml
XTS/bridge/pom.xml
XTS/pom.xml
XTS/recovery/pom.xml
XTS/sar/pom.xml
pom.xml

[JBTM-3997] Some adjustments to which modules are deployed

---

vertx/pom.xml

[JBTM-3997] vertx removed from the release process
